utils.go
Based on https://github.com/gofiber/fiber/blob/master/docs/routing.md#parameters we should be able to register a route of `/api/values/:id` but we can't.
There is a bug on your `utils.getRegex`. The `strings.Split` there may return a first segment of empty string, please read the documentation of [strings.Split](https://golang.org/pkg/strings/#Split).
**Screenshot before this PR**
**Screenshot after this PR**
Thanks,
[Gerasimos Maropoulos](https://twitter.com/makismaropoulos). Author of the [Iris](https://iris-go.com) web framework.
=> Fix panic on routing with parameters

static.go
When we try to serve not-exists dir, segmentation violation occured.
```go
app.Static("./publi") // typo
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7dc998]
goroutine 1 [running]:
github.com/gofiber/fiber.getFiles.func1(0x8c277e, 0x7, 0x0, 0x0, 0x957d80, 0xc000167b60, 0x8, 0x8)
/home/koyamaso/pkg/mod/github.com/gofiber/fiber@v1.3.4/utils.go:67 +0x38
path/filepath.Walk(0x8c277e, 0x7, 0xc000067da8, 0xc0000b6140, 0x8758c0)
```
This PR makes the error message clearer. Like below.
```
2020/02/07 01:48:07 Static: lstat ./publi: no such file or directory
```
This framework is great and I want to use it proactively. Thanks!
=> Fix panic on serving not-exists dir

application.go, request.go
Error strings should be all lowercase.
Reference:
https://github.com/golang/go/wiki/CodeReviewComments#error-strings
=> Error strings to lowercase

application.go, request.go, request_test.go, response.go, router.go
https://github.com/gofiber/fiber/issues/126
```go
//
// Recover ( disabled by default, unless a custom Recover handler is set )
// We might enable Recover by default with "500 Internal Server Error" in the future
//
func main() {
app.Get("/", func(c *fiber.Ctx) {
panic("I panic")
})
app.Recover(func(c *fiber.Ctx) {
c.Status(500).Send(c.Error()) // => 500 "I panic"
})
app.Listen(3000)
}
```
```go
//
// Context error
//
package main
import "github.com/gofiber/fiber"
func main() {
app.Post("/api/register", func (c *fiber.Ctx) {
if err := c.JSON(&User); err != nil {
c.Next(err)
}
})
app.Get("/api/user", func (c *fiber.Ctx) {
if err := c.JSON(&User); err != nil {
c.Next(err)
}
})
app.Put("/api/update", func (c *fiber.Ctx) {
if err := c.JSON(&User); err != …
```
=> Add Recover

application.go, application_test.go, go.mod, go.sum, response.go
Add `Render` for alpha testing, 6 template engines are available:
- [.template](https://golang.org/pkg/text/template/)
- [.ace](https://github.com/yosssi/ace)
- [.amber](https://github.com/eknkc/amber)
- [.jet](https://github.com/CloudyKit/jet)
- [.mustache](github.com/cbroglie/mustache)
- [.raymond](https://github.com/aymerick/raymond)
The function uses the correct engine based on the file extension.
```go
func main() {
app.Get("/", func(c *fiber.Ctx) {
data := map[string]interface{}{
"name": "John",
"age":  "35",
}
var err error
//err = c.Render("views/test.template", data)
//err = c.Render("views/test.ace", data)
//err = c.Render("views/test.amber", data)
//err = c.Render("views/test.jet", data)
//err = c.Render("views/test.raymond", data)
err = …
```
=> Add template engines: Render(file, data)

.github/README.md, .github/README_de.md, .github/README_es.md, .github/README_ja.md, .github/README_ko.md, .github/README_pt.md, .github/README_ru.md, .github/README_zh-CN.md
There were some useless spaces in the different READMEs.
Some of these were on empty lines and others were between a `func` and the opening parenthesis.
For example, some anonymous functions were declared like this:
```golang
func () { ... } // note the extra space after `func`
```
And it's now:
```golang
func() { ... } // no more extra space after `func`
```
I think the fact that in the examples, a function is *sometime* declared with a space after the `func` could be confusing for beginners in Go (we never know). So I have removed them.
=> Removing some useless spaces in the READMEs

.github/README.md, .github/README_de.md, .github/README_es.md, .github/README_fr.md, .github/README_id.md, .github/README_ja.md, .github/README_ko.md, .github/README_pt.md, .github/README_ru.md, .github/README_tr.md, .github/README_zh-CN.md
After copying this example from the logger middleware
```
// Optional logger config
config := logger.LoggerConfig{
Format:     "${time} - ${method} ${path}\n",
TimeFormat: "Mon, 2 Jan 2006 15:04:05 MST",
}
// Logger with config
app.Use(logger.New(config))
```
and running it I got the error `./main.go:18:12: undefined: logger.LoggerConfig`, changing `.LoggerConfig` to `.Config` fixed the issue as I imagine there was a name change on the API recently.
Similarly, in the example for the recovery middleware there is a `recover.LoggerConfig` instead of `recover.Config`. 
I've renamed all occurances of `LoggerConfig` in the README files to `Config` to fix these issues so the examples can be copy and pasted without errors. I thought I'd fix it for you guys instead of just telling you about it, my …
=> Fixed inconsistency in middleware examples in README

app.go
Fixed,
```
Fiber xx listening on xx
```
Even if there was an error
=> Fix listen message printing when error

.github/README.md, .github/README_de.md, .github/README_es.md, .github/README_fr.md, .github/README_he.md, .github/README_ja.md, .github/README_ko.md, .github/README_nl.md, .github/README_pt.md, .github/README_ru.md, .github/README_tr.md, .github/README_zh-CN.md
- added README_heb.md for hebrew translation.
- did not touch license description.
- need to add IL flag to `static/flags` folder inside https://github.com/gofiber/docs. (https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.6/flags/4x3/il.svg)
**If someone can do it for me or guide me how to do it, I will appreciate it.**
- updated number of translations in all readme files.
- vscode auto-format markdown tables in all readme files.
=> Add README Hebrew translation

app.go
Hi Guys,
Thanks for your great work! It seems like BodyParser is generating error when there are unknown fields in the form/query. For example:
```
type User struct {
Email string `form:"email"`
Password string `form:"password"`
}
```
If I send the request with these parameters:
email: abc@gmail.com
password: abc
token_type: jwt
It will generate error `schema: invalid path "token_type"`
I think it should be ignored peacefully. Let me know how you think :)
=> Schema Decoder: Ignore unknown fields by default

ctx.go
If the query string is `id=1&name=tom&hobby=basketball&hobby=football`, then can be parsed and get all `hobby` param。
```
type User struct {
Id  int
Name string
Hobby []string
}
```
=> update: ctx.BodyParser

app.go
When not providing a `Content-Length` when passing a `Body` it will throw an `EOF` error in `app.Test()`
=> Add Content-Length to app.Test()

app.go
Current `Settings` when creating a new **App** allow to enable or disable the «startup message», which is shown when the server is started.
This message, like in most frameworks, displays a «banner» of the library (in this case «FIBER» in ASCII art), and a message with info about the address the server is currently listening.
The thing is the listening info is pretty informative and usually we want to show it (at least we know that way when the server is ready), but the «banner» before, most of the times is just decorative.
Or we want to replace it with another banner or info (as example, if we're developing an app that uses «Fiber» but we want to add instead a «banner» of the project using it, its version, some initial comments, etcetera).
So I added a pair of extra settings just for …
=> Feature: Add Settings StartupBanner & HideStartupBanner

app.go, app_test.go, ctx.go, ctx_test.go, router.go, router_test.go, utils.go
- Update Version: `v1.10.2`
- Add/Remove code comments
- Add response body to `404`: `Cannot %method %path`
- Add more benchmarks & tests
- Fix Static Content-Type https://github.com/gofiber/fiber/issues/420
- Update router behaviour on `c.Next()` by returning a `404` if no match https://github.com/gofiber/fiber/issues/430
- Add `ctx.SendStream` with `io.Reader` support
=> Router updates

ctx.go, ctx_test.go
Ran into a bug with `ctx.Render`
=> 🩹 fix ctx.Render when using Go Templates

ctx.go, ctx_test.go
It may raise panic when the hostname does not even contain one dot.
=> Check index to avoid slice bounds out of range panic

app.go
- Windows now supports the `Prefork` option using `REUSEADDR` instead of `REUSEPORT`
- Fix closing child processes when master exits https://github.com/gofiber/fiber/issues/501
=> Add Prefork support for Windows

app.go
added the possibility to access the handler
=> 🚀 How about compatibling with httpexpect #485

middleware/compress.md
Under Custom Config example `CompressWithConfig(<param>)` , `param` should be `middleware.CompressConfig` instead of `middleware.LoggerConfig`
=> Doc: Incorrect Config in Custom Config example

middleware/compress.go, middleware/request_id.go
`Compress()` did not support `CompressConfig` param while `CompressWithConfig()` is deprecated since v1.12.3.
`RequestID()` did not support `RequestIDConfig` param while `RequestIDWithConfig()` is deprecated since v1.12.3.
=> support config param in Compress() and RequestID()

app.go, prefork.go
1. Don't define the prefork flag
2. Don't expose the prefork-child flag in the flag usage message
Closes #522
=> 🩹 Improve flag handling

ctx.go, ctx_test.go
[Here](https://github.com/zerbitx/gnockgnock/blob/master/gnocker/gnocker.go#L199) is my rather specific use case.  This test helper app will be dynamically configured to mock 3rd party apis, so it would be convenient to see what params are available at run time.
=> 🔥 Feature Add ParamList Method to context

app_test.go, ctx.go, router.go
While `ctx.matched` false after scanning route chain, function `setMethodNotAllowed` should be called.
=> 💡 add ctx.matched to determine if request matched a non USE route.

path.go, path_test.go
`getAllocFreeParams` should use corresponding `len(paramsDummy)`.
=>  💯 improve path.go coverage

ctx.go, ctx_test.go
NEW
```go
Benchmark_Ctx_SendString_For_Reset
Benchmark_Ctx_SendString_For_Reset-8    100000000               11.8 ns/op             0 B/op          0 allocs/op
Benchmark_Ctx_SendString_For_Reset-8    100000000               11.6 ns/op             0 B/op          0 allocs/op
Benchmark_Ctx_SendString_For_Reset-8    100000000               12.0 ns/op             0 B/op          0 allocs/op
Benchmark_Ctx_SendString_For_Reset-8    100000000               11.9 ns/op             0 B/op          0 allocs/op
Benchmark_Ctx_Reset_Body
Benchmark_Ctx_Reset_Body-8      169810179                7.03 ns/op            0 B/op          0 allocs/op
Benchmark_Ctx_Reset_Body-8      170163852                7.05 ns/op            0 B/op          0 allocs/op
Benchmark_Ctx_Reset_Body-8      168444130 …
```
=> Improve ctx.Send and ctx.SendBytes performance

ctx.go, ctx_test.go
I made adjustments to `ctx.JSON`, which can improve performance by about ~~30%~~ 20%. 
And the impacts are:
- Regardless of whether json serialization is successful or not, `response body` will be reset
- ~~The json serialization result will append an extra `\n`(see [reason in stdlib](https://github.com/golang/go/blob/release-branch.go1.14/src/encoding/json/stream.go#L211-L217)) , which I personally think will not have a destructive effect~~
This PR retains the old `ctx.JSONOld` for benchmark comparison. You can execute `go test -v -run=^$ -bench="Benchmark_Ctx_JSON(O|$)" -benchmem -count=4
`View results:
```bash
go test -v -run=^$ -bench="Benchmark_Ctx_JSON(O|$)" -benchmem -count=4
goos: darwin
goarch: amd64
pkg: github.com/gofiber/fiber
Benchmark_Ctx_JSON
Benchmark_Ctx_JSON-8 2703946 …
```
=> Improve json

ctx.go, ctx_test.go
OLD:
```go
Benchmark_Ctx_Attachment-12      2717662       430 ns/op     128 B/op        2 allocs/op
Benchmark_Ctx_Attachment-12      2781739       443 ns/op     128 B/op        2 allocs/op
Benchmark_Ctx_Attachment-12      2628789       436 ns/op     128 B/op        2 allocs/op
```
NEW:
```go
Benchmark_Ctx_Attachment-12      4048429       292 ns/op     208 B/op        3 allocs/op
Benchmark_Ctx_Attachment-12      4125378       292 ns/op     208 B/op        3 allocs/op
Benchmark_Ctx_Attachment-12      4093616       294 ns/op     208 B/op        3 allocs/op
```
=> 🚀 Better performance for ctx.Attachment

app.go, prefork.go
Currently, `Fiber` uses `utils.GetArgument(flagChild)` to determine whether the current process is a child process from prefork. According to #522 and #469, we know that users have some side effects when using `flag.Parse()`.
My current approach is to use environment variables to determine whether the current process is a child process. When spawning a child process, add `FIBER_PREFORK_CHILD=1` environment variable for inter-process communication. This has several advantages:
- No longer affects anything related to the flag, so there is no need for the hijacking code added in #542 (some are copied from the standard library)
- `FIBER_PREFORK_CHILD` this environment variable is basically impossible to conflict with the user’s environment variables
As for the global variable names that …
=> use prefork child env

ctx.go, ctx_test.go, utils.go
co-authored-by @ReneWerner87 
And `func quoteString` now is put in `Fiber core`'s util file, maybe it should be moved to `gofiber/utils` package someday @Fenny .
Add a test assert for `ctx.Download` incidentally.
=> 🚨 extract func quoteString() for ctx.Attachment and ctx.Download

app_test.go, prefork.go, prefork_test.go, router_test.go, utils_test.go
```bash
go test -count=1 -cover
PASS
coverage: 93.9% of statements
```
I did some trick on `prefork.go` test
```go
cmd := exec.Command(os.Args[0], os.Args[1:]...)
if testPreforkMaster {
// When test prefork master,
// just start the child process
// a cmd on all os is best
cmd = exec.Command("date")
}
```
I'm wondering if this will be fine.
=> Improve coverage

ctx.go
OLD:
```
Benchmark_Ctx_IPs-8      5335536               221 ns/op              48 B/op          1 allocs/op
Benchmark_Ctx_IPs-8      5490664               219 ns/op              48 B/op          1 allocs/op
Benchmark_Ctx_IPs-8      5296419               218 ns/op              48 B/op          1 allocs/op
Benchmark_Ctx_IPs-8      5501774               227 ns/op              48 B/op          1 allocs/op
```
NEW:
```
Benchmark_Ctx_IPs-8      6307110               187 ns/op              48 B/op          1 allocs/op
Benchmark_Ctx_IPs-8      6372991               190 ns/op              48 B/op          1 allocs/op
Benchmark_Ctx_IPs-8      6499392               188 ns/op              48 B/op          1 allocs/op
Benchmark_Ctx_IPs-8      6374119               188 ns/op              48 B/op …
```
=> 🚀 improve ctx.Ips performance

ctx.go, ctx_test.go
OLD:
```
Benchmark_Ctx_QueryParser-8       152832              7445 ns/op            1832 B/op         62 allocs/op
Benchmark_Ctx_QueryParser-8       157682              7515 ns/op            1832 B/op         62 allocs/op
Benchmark_Ctx_QueryParser-8       158262              7495 ns/op            1832 B/op         62 allocs/op
Benchmark_Ctx_QueryParser-8       159984              7468 ns/op            1832 B/op         62 allocs/op
```
NEW:
```
Benchmark_Ctx_QueryParser-8       214756              5021 ns/op             912 B/op         39 allocs/op
Benchmark_Ctx_QueryParser-8       232807              5064 ns/op             912 B/op         39 allocs/op
Benchmark_Ctx_QueryParser-8       233775              5111 ns/op             912 B/op         39 allocs/op
Benchmark_Ctx_QueryParser-8 …
```
=> 🚀 improve ctx.QueryParser performance

app_test.go, ctx.go
`ctx.matched` should be reset to false when acquired
=> 🔔 fix ctx matched bug

ctx.go
According to #625 , I did some investigation and found that both `ctx.Render` and `logger` middleware use `bytebufferpool`, so `ctx.Render` can't use `ctx.SendBytes()` because it sets response body without copying it.
I think this fix can close #625.
=> 👷 fixed ctx.Render bug

middleware/logger.go, middleware/logger.md, middleware/logger_test.go
The default value of TimeZone is "Local", using the system time zone.
You can also specify "UTC" and "America / New_York" and "Asia / Chongqing", etc.
**Example:**
```go
app.Use(middleware.Logger(middleware.LoggerConfig{
TimeFormat: "2006-01-02 15:04:05",
TimeZone:   "UTC",
}))
app.Get("/", func(ctx *fiber.Ctx) {
ctx.Write("hello world")
})
if err := app.Listen(3000); err != nil {
log.Fatalln(err)
}
```
**Output:**
```text
#29499 - 2020-07-21 05:15:29 200 - 0s         GET /
```
=> 🔥 Add logger middleware time zone support

app.go, app_test.go, group.go, router.go, router_test.go
- compress route handers when it is identical with pre-one
- use routes slice to store all registered routes
- Get route shares handlers with Head route which is spawned by itself
=> 🚀 compress same route's handler and sort routes when registering

ctx.go
we expect that the header value of the content type are already small in 90% of cases
=> ⚡ Improve ctx.BodyParser speed -> remove toLower

app.go, app_test.go, router.go, utils.go
correction of wrong methods for USE and GET with automatic HEAD routing
=> 💉  Sync route method metadata

middleware/compress.go, middleware/compress_test.go, middleware/logger.go, middleware/logger_test.go, middleware/request_id.go, middleware/request_id_test.go
When option is invalid to the middleware factory, raise panic instead of fatal.
Panic can be tested but fatal can't.
=> :goal_net: use panic instead of log.Fatal

ctx.go, ctx_test.go
fix #670
if value of X-Forwarded-For header is empty, ctx.Ips() should be empty too
=> 🩹 when X-Forwarded-For is empty, ctx.Ips() should be empty

ctx.go, ctx_test.go, utils.go
Move logics of checking if the etag is stale to `utils` and replace the existing `parseTokenList` function. And also, we don't need to allocate a string slice to store all etags. Instead, we could just check in place to see if it matches the etag.
=> 🧹 Refactor etag stale checking

ctx.go, ctx_test.go, utils.go
While we are on the `regexp` topic, I found another place that's using it for `no-cache` value check. The regular expression is pretty straightforward, so I implemented a function to do the same thing -- if the string has `no-cache`, and its previous non-space char is either nothing or comma, and same with the char after.
I also added a benchmark to make sure this improves the performance:
AFTER:
```
$ go test -v -run=^$ -bench=Benchmark_Ctx_Fresh_WithNoCache -benchmem -count=4
goos: darwin
goarch: amd64
pkg: github.com/gofiber/fiber
Benchmark_Ctx_Fresh_WithNoCache
Benchmark_Ctx_Fresh_WithNoCache-12      10466191               117 ns/op               0 B/op          0 allocs/op …
```
=> 🚀 Don't use regexp for no-cache value check

middleware/compress.go, middleware/compress_test.go
Initialize all compress handlers beforehand, instead of creating one each time the middleware is used.
The current [Benchmark_Middleware_Compress](https://github.com/gofiber/fiber/blob/066b93460c675219a2e826e990676ddfa301a093/middleware/compress_test.go#L148) doesn't show any difference because the `Compress` middleware is outside of the `b.N` loop.
I moved:
```
app.Use(Compress())
app.Get("/", func(c *fiber.Ctx) {
c.SendFile(compressFilePath(CompressLevelDefault), true)
})
```
into the benchmark loop on my machine, and here is the diff:
```
BEFORE
$ go test -v ./... -run=^$ -bench=Benchmark_Middleware_Compress -benchmem -count=4
PASS
ok      github.com/gofiber/fiber        0.118s
goos: darwin
goarch: amd64 …
```
=> 🧹 Pre-initialize all compress handlers

app.go, ctx.go, ctx_test.go, path.go, path_test.go, router.go, router_test.go, utils.go, utils_test.go
🌵  hybrid routing with tree and fast router:
for performance reasons, a new layer has been added to reduce the number of routes to be checked
NEW:
```go
Benchmark_Router_NotFound-12                  4345894       249 ns/op      80 B/op       2 allocs/op
Benchmark_Router_NotFound-12                  5195691       252 ns/op      80 B/op       2 allocs/op
Benchmark_Router_NotFound-12                  4069700       262 ns/op      80 B/op       2 allocs/op
Benchmark_Router_Handler-12                   6323901       200 ns/op      16 B/op       1 allocs/op
Benchmark_Router_Handler-12                   5701125       207 ns/op      16 B/op       1 allocs/op
Benchmark_Router_Handler-12                   5515296       204 ns/op      16 B/op       1 allocs/op
Benchmark_Router_Handler_Strict_Case-12 …
```
=> 🚀  Improve routing behavior

app.go
In a test environment, you might not call `Listen`, `Listener`, or `Tests` and directly test on the main `handler`. But with the new hybrid tree implementation by @ReneWerner87 we do not update the server values. This PR will fix that.
=> ⚙ init on Handler call

.github/README.md, .github/README_ar_SA.md, .github/README_de.md, .github/README_es.md, .github/README_fr.md, .github/README_he.md, .github/README_id.md, .github/README_ja.md, .github/README_ko.md, .github/README_nl.md, .github/README_pt.md, .github/README_ru.md, .github/README_tr.md, .github/README_zh-CN.md, .github/README_zh-TW.md
Added my fiber-cache middleware to the 3rd party middlewares section of the readmes ([codemicro/fiber-cache](https://github.com/codemicro/fiber-cache)). I also sorted the list alphabetically.
~~**Commit formatting** 
Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/~~ I sort of attempted to do this and then failed massively.
=> Add fiber-cache middleware to README(s)

app.go
https://github.com/gofiber/fiber/issues/736
=> 🎈 prepare for v1.15.0

router.go, router_test.go
Fix for star route bug
```go
panic: runtime error: slice bounds out of range [1:0]
goroutine 19 [running]:
github.com/gofiber/fiber.(*Route).match(0xc000090fd0, 0xa225b0, 0x0, 0x0, 0x0, 0x1, 0xd6, 0xe0, 0x0)
/root/go/src/github.com/gofiber/fiber/router.go:62 +0x305
github.com/gofiber/fiber.(*App).next(0xc0000f3560, 0xc00007ae60, 0xc00007ae60)
/root/go/src/github.com/gofiber/fiber/router.go:101 +0x134
github.com/gofiber/fiber.(*App).handler(0xc0000f3560, 0xc0006ec000)
/root/go/src/github.com/gofiber/fiber/router.go:145 +0x170
github.com/valyala/fasthttp.(*Server).serveConn(0xc000086480, 0x7d1de0, 0xc0005ed2e8, 0x0, 0x0)
/root/go/src/github.com/valyala/fasthttp/server.go:2168 +0x11ac
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00007abe0, 0xc000645480) …
```
=> 🦟 Fix star routes

filesystem/filesystem.go, filesystem/filesystem_test.go
* Updated filesystem middleware to be compatible with v15 by using `c.Request()` instead of `c.FastHTTP()`
* Fixed filesystem middleware tests. It seems the previous syntax was using `utils.AssertEqual(test, actual, expected)` when it should be `utils.AssertEqual(test, expected, actual)`
=> 🐛 Fix filesystem tests, make compatible with v15

app.go, utils/README.md, utils/bytes_test.go, utils/common.go, utils/convert.go, utils/convert_test.go, utils/http_test.go
```go
// go test -benchmem -run=^$ -bench=Benchmark_ -count=2
Benchmark_ToLowerBytes/fiber-16                 42847654                25.7 ns/op             0 B/op          0 allocs/op
Benchmark_ToLowerBytes/fiber-16                 46143196                25.7 ns/op             0 B/op          0 allocs/op
Benchmark_ToLowerBytes/default-16               17387322                67.4 ns/op            48 B/op          1 allocs/op
Benchmark_ToLowerBytes/default-16               17906491                67.4 ns/op            48 B/op          1 allocs/op
Benchmark_ToUpperBytes/fiber-16                 46143729                25.7 ns/op             0 B/op          0 allocs/op
Benchmark_ToUpperBytes/fiber-16                 47989250                25.6 ns/op             0 B/op          0 allocs/op …
```
=> 🛠 update utils

app_test.go, ctx.go, middleware/logger/logger.go, router.go
☠️ Improve error handling flow
Co-authored-by: Fenny <fenny@gofiber.io>
Co-authored-by: Kiyon <kiyon@gofiber.io>
=> ☠️ Improve error handling flow

middleware/cors/README.md
fix: Updated line 32 `AllowHeader` to `AllowHeaders` as it appears to be a typo.
=> 📚 Doc: typo line 32 `AllowHeader` to `AllowHeaders`

middleware/expvar/README.md, middleware/expvar/expvar.go, middleware/expvar/expvar_test.go
It's wrapper of fasthttp/expvarhandler.
This middleware provides a standardized interface to public variables, such as operation counters in servers. It exposes these variables via HTTP at /debug/vars in JSON format.
But it's name is conflicted with standard package `expvar`. So I am wondering whether change its name to `vars`.
=> 🆕  add expvar middleware

ctx.go, middleware/csrf/csrf.go
`Max-Age` is the new standard since 2009, some browsers do not support this yet so. You can test it here https://mrcoles.com/media/test/cookies-max-age-vs-expires.html
Or read more here: https://mrcoles.com/blog/cookies-max-age-vs-expires/
https://github.com/gofiber/fiber/issues/858
Also fix csrf https://github.com/gofiber/fiber/issues/861 to default to`Strict` if no `SameSite` is provided in config.
=> 🍪 add max-age to cookie

middleware/csrf/csrf.go
Fixes #861
When passing a partial cookie like to csrf.New, the cookie's Name and SameSite are not set to their default values. Caused by [this](https://github.com/gofiber/fiber/blob/v2.0.5/middleware/csrf/csrf.go#L75) line:
```go
if cfg.Cookie == nil {
cfg.Cookie = ConfigDefault.Cookie
if cfg.Cookie.Name == "" {
cfg.Cookie.Name = "_csrf"
}
if cfg.Cookie.SameSite == "" {
cfg.Cookie.SameSite = "Strict"
}
}
```
If cfg.Cookie *is* passed, it expects you to have SameSite and Name included. With my fix, you can pass `&Cookie{Name: "_csrf"}` and `SameSite` will still be set to the default.
=> 🐛 Fix passing partial cookie to csrf.New

app_test.go, ctx.go, ctx_test.go, helpers.go, helpers_test.go
This fixes warnings found by the `deadcode` and `gosimple` scanners using the latest golangci-lint
```
helpers.go:310:6: `isIPv6` is unused (deadcode)
func isIPv6(address string) bool {
^
ctx_test.go:1329:33: S1025: the argument is already a string, there's no need to use fmt.Sprintf (gosimple)
utils.AssertEqual(t, "index", fmt.Sprintf("%s", file))
^
app_test.go:124:35: S1019: should use make([]string, 5000) instead (gosimple)
logHeaderSlice := make([]string, 5000, 5000)
^
ctx.go:711:6: S1003: should use strings.Contains(v, ",") instead (gosimple)
if strings.Index(v, ",") > -1 && equalFieldType(out, …
```
=> :art: Fix gosimple and deadcode lint warnings

middleware/favicon/favicon.go, middleware/favicon/favicon_test.go
Right now, each favicon response sets the `Cache-Control` header to `public, max-age=31536000` (1 year). In some cases this could be a little bit high if you are changing it etc. and the header is not replaced by a reverse proxy.
With this change, the favicon middleware allows the configuration of the `Cache-Control` header. The default behavior is  to keep the setting of `max-age=31536000 `, but you could fine-tune it.
✅ done 
Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: …
=> 🔥add the option to set a custom Cache-Control value for a favicon response

app.go
This PR introduces the `ReduceMemoryUsage` flag to the app config that is pulled to the underlying `fasthttp` server. The default value is `false` to keep the old behavior.
The implementation of `ReduceMemoryUsage` is here: https://github.com/valyala/fasthttp/blob/01acd76daf36a86fabc2b73fd5fc1deb3ec10fec/server.go#L285
Refs: #866 / https://github.com/gofiber/fiber/issues/866#issuecomment-704818583
✅ done
=> 🔥 make the fasthttp `ReduceMemoryUsage` flag public

middleware/compress/compress.go
Avoid the magic numbers to make it easier to read. Right now the integer values of the `const` are used instead of the `const` constants.
✅ done
=> ♻️ compression: avoid magic numbers in compression level check

app.go, app_test.go, router.go
Right now, each static request returns the file without any `Cache-Control` header. If you are using `app.Static` to serve your assets, the browser won't cache it. This PR introduces a way to set the `cache control` header (if the file was found) on the file response to set a custom `max-age` to e.g. cache it 1 year.
A general use case for 
```go
app.Static("/public", "./public")
```
could be to serve your CSS and JS assets. Right now, there is no `Cache-Control` header present on the file-response. With this change, the `Cache-Control`-header can be configured through something like this
```go …
```
=> 🔥set a `Cache Control` header for static ressources

middleware/compress/compress.go, middleware/compress/compress_test.go
@Fenny this is more of an idea than a PR.
I believe it would help a lot if we used custom types for specific configurations:
- It enforces people to use a value that matches the type.
- We can limit only to the proper or "right" values.
- It works nicely with auto completion tools.
- It helps maintain a stricter interface and gives us more control.
If you agree I can make similar changes to the rest of the middleware and then take it from there.
=> Add custom types to compress middleware

app.go
Implements one of the options in #843 for a child PID display.
=> 📦 Add child PID display when prefork enabled

middleware/basicauth/basicauth.go, middleware/basicauth/basicauth_test.go
- Split nested ifs to simpler statements
- Make the tests run in parallel (perhaps we should do this in all test cases under the middlewares)
=> Refactor basicauth middleware

middleware/requestid/requestid.go, middleware/requestid/requestid_test.go
- Adds a minor (clarity) only change to the defaults.
- Adds an assertion that is missing from a test.
=> Minor requestid middleware change

ctx.go, ctx_test.go
bench compare result:
```
benchmark                    old ns/op     new ns/op     delta
Benchmark_Ctx_BaseURL-12     58.0          2.24          -96.14%
benchmark                    old allocs     new allocs     delta
Benchmark_Ctx_BaseURL-12     1              0              -100.00%
benchmark                    old bytes     new bytes     delta
Benchmark_Ctx_BaseURL-12     32            0             -100.00%
```
=> improve base uri for ctx

middleware/requestid/README.md, middleware/requestid/requestid.go, middleware/requestid/requestid_test.go
This PR adds the assigned request ID to the locals to allow for retrieval in the handler of an endpoint.
Tests and the README have also been updated.
=> 🔥 Add request ID to locals

middleware/csrf/README.md, middleware/csrf/csrf.go, middleware/csrf/csrf_test.go
Will fix https://github.com/gofiber/fiber/issues/953 and adds support for `cookie:<key>` extraction.
=> 🩹 add memory storage for csrf

ctx.go, ctx_test.go
Co-authored-by: Fenny <fenny@gofiber.io>
Co-authored-by: navossoc <navossoc@gmail.com>
Fix the current behaviour of the ctx.Accepts method.
=> 🐛 Fix (*Ctx).Accepts

app.go, internal/encoding/ascii/valid.go, middleware/compress/compress.go, utils/common.go
During reading some code and getting know with the repo I adjusted multiple comments that were marked by the linter as warnings.
=> 🎨 Adjust multiple comments to comply with the linter

middleware/csrf/csrf.go
- Skip non GET/POST http method
- Delete token if matched
- Use cfg.Expiration instead of cfg.CookieExpires
=> 👷 Improve csrf middleware

middleware/compress/compress_test.go
Adjusted one of the compression tests. Previously it didn't compress results at all. It just checked if 200 is returned without verifying compression results.
=> 🚨 Add missing header and compression result assertion in different compression levels test

ctx.go, ctx_test.go
`QueryParser()` which parses query arguments into the struct which user provided along with `query` tag.
And there's a tag option - `required`.
Query arguments with no field that is required by the struct tag, `QueryParser()` returns an error.
However if there's no query argument, `QueryParser()` returns `nil` which can make user confused.
So I think the simplest way to catch this is that removing the argument length based condition.
As far as I know, it is for the performance that no query arguments mean nothing to parse so pass it with empty query string.
But `required` fields are expected to be set, …
=> queryparser: query args count based condition removed

ctx.go, ctx_test.go
`QueryParser()` which parses query arguments into the struct which user provided along with `query` tag.
And there's a tag option - `required`.
Query arguments with no field that is required by the struct tag, `QueryParser()` returns an error.
However if there's no query argument, `QueryParser()` returns `nil` which can make user confused.
So I think the simplest way to catch this is that removing the argument length based condition.
As far as I know, it is for the performance that no query arguments mean nothing to parse so pass it with empty query string.
But `required` fields are expected to be set, …
=> :bug: queryparser: query args count based condition removed

middleware/filesystem/filesystem.go, middleware/filesystem/filesystem_test.go
Based on a user's request on issue #834 then was implemented now we have a new method called SendFile on filesystem middleware.
```go
package main
import (
"net/http"
"github.com/gofiber/fiber/v2/middleware/filesystem"
"github.com/gofiber/fiber/v2/middleware/logger"
)
func main() {
app.Use(logger.New())
app.Use("/:path", func(c *fiber.Ctx) error {
return filesystem.SendFile(c, http.Dir("./assets"), c.Params("path")+".html")
})
app.Listen(":3000")
}
```
=> 🚀 feat: filesystem middleware work routes with params

middleware/basicauth/basicauth_test.go, middleware/cache/cache_test.go
Fix ineffectual assignment and remove unused variable.
Here is the result of [golangci-lint](https://github.com/golangci/golangci-lint) of middleware:
```
middleware/basicauth/basicauth_test.go:82:9: ineffectual assignment to `err` (ineffassign)
resp, err := app.Test(req)
^
middleware/cache/cache_test.go:32:2: SA4006: this value of `resp` is never used (staticcheck)
resp, err := app.Test(httptest.NewRequest("GET", "/", nil))
^
middleware/logger/logger.go:368:4: SA9003: empty branch (staticcheck)
if _, err := cfg.Output.Write([]byte(err.Error())); err != nil {
^
```
=> ♻️ refactor: ineffectual assignment and unused variable

path.go, path_test.go
#1016
```go
// this matches http://localhost:3000/123/456/test
app.Get("/:id/test", func(c *fiber.Ctx) error {
return c.SendString(c.Path())
})
```
this route should not match, this is corrected with this pull request
=> 🐛 Fix wrong route matching for not greedy parameter

.github/README.md, .github/README_de.md, .github/README_es.md, .github/README_fr.md, .github/README_he.md, .github/README_id.md, .github/README_ja.md, .github/README_ko.md, .github/README_nl.md, .github/README_pt.md, .github/README_ru.md, .github/README_sa.md, .github/README_tr.md, .github/README_zh-CN.md, .github/README_zh-TW.md
I wrote a small middleware to enable the use of virtual hosts by comparing the Host header with the Hostname specified in the Config. I plan on extending the middleware to match Host's by regex as well.
=> :seedling: Add fiber_vhost middleware

middleware/csrf/README.md, middleware/csrf/config.go, middleware/csrf/csrf.go
- Fixed `csrf.go`: removed L39-L41
- Additional changes(minor)
-  Fixed comment for CookieName(`_csrf` to `csrf_` as default value)
-  Fixed comment for CookieSameSite
=> fixed cookie error in csrf.go🚑

router.go
Fasthttp already [validates](https://github.com/valyala/fasthttp/blob/master/fs.go#L368-L371) this option.
=> 👷 Remove redundant validation of CacheDuration when checking static config

middleware/limiter/README.md
The README import example was about "session" but the middleware is about "limiter".
=> Update README limiter

helpers.go, helpers_test.go
```go
package main
import (
"log"
)
func main() {
return c.JSON("Main App")
})
api := app.Group("api")
api.Get("/", func(c *fiber.Ctx) error {
return c.JSON("API")
})
v1 := api.Group("v1")
v1.Get("/", func(c *fiber.Ctx) error {
return c.JSON("V1 Api")
})
account := v1.Group("account")
account.Get("/", func(c *fiber.Ctx) error {
return c.JSON("v1 account")
})
for _, routes := range app.Stack() {
for _, route := range routes {
log.Println(route.Method, route.Path)
}
}
}
```
Will produce things from
```hs
2020/12/24 …
```
=> 👷 Auto add '/' prefix for Group

app.go, ctx_test.go, middleware/cors/cors_test.go, prefork_test.go, router.go, router_test.go
with this pull request i want to solve issue #1081 and improve the startup process of fiber with many registered routes
with 4002 handler -> from ~2.3seconds to ~4ms
Test-code: 
https://github.com/gofiber/fiber/issues/1081#issue-770782185
but without the print in every registered handler
**NEW**:
with 4002 handlers:
with 2 handlers:
**OLD**:
with 4002 handlers
with 2 handlers
=> ⚡ Accelerate start process for many routes #1081

internal/schema/decoder.go, router.go, utils/assertions.go
Updating some lines so them could respect go-lint style. No changes in functionality was made
Replaced explicit comparison to "true" and "false" statements where they was unnecessary. 
Replaced unnecessary `Sprintf` func when obj have `String` method
=> 🎨 Style: adjusted lines according go-lint

app.go, app_test.go, router.go
I've added option to to skip app.Static middleware. Mechanism is identical with proxy.Config.Next function from `proxy` middleware.
This can be feature is crucial for example when you want to serve different static files based on whether the user is authenticated.
Or when you just want to protect static file from unauthenticated users.
=> ✨ add Next function to app.Static config

middleware/cache/cache.go, middleware/cache/cache_test.go
The intention of this PR is to address the issue raised here: [1116](https://github.com/gofiber/fiber/issues/1116)
Move ``config.Next`` after ``ctx.Next``, so we can determine whether to cache or not after handling biz logic.
=> ajust config.Next position

app.go, app_test.go, helpers.go, helpers_test.go, prefork.go, prefork_test.go
Solve #1154 
```go
package main
import (
"log"
)
func main() {
app := fiber.New(fiber.Config{
Prefork: true,
Network: fiber.NetworkTCP6,
})
return c.SendString("Hello IPv6 👋")
})
log.Println(app.Listen("[::]:3000"))
}
```
By adding `Network` option, users can decide which network stack(`tcp`, `tcp4`, `tcp6`) to use.
=> 🔥 Add network option

middleware/filesystem/README.md
[Go embedding](https://golang.org/pkg/embed/) was released in Go 1.16 yesterday. This PR is to add an example for how to use it with the filesystem middleware
=> add embed example for go 1.16

app.go, app_test.go, helpers.go
Now we use hardcode `false` to `app.startupMessage` in `app.Listener`, so when even param `ln` is a tls listener,  `app.startupMessage` also displays `http://xxx`.
This PR fixes the bug via detecting `ln` type.
=> 👷 Fix hardcode tls to startupMessage in app.Listener

middleware/favicon/favicon.go, middleware/favicon/favicon_test.go
This change exists to support go 1.16 embedded filesystems and other network filesystems that can't simply be read as a file from a system path.
Since go 1.16 just dropped with embedded filesystem support, I thought fiber would benefit from fully supporting alternate filesystems. The filesystem middleware already supports any filesystem but I noticed the favicon middleware was still built to simply read from a system path.
=> 🔥 Add optional FileSystem config to middleware/favicon

middleware/session/session_test.go, middleware/session/store.go
This pr try to fix this issue: https://github.com/gofiber/fiber/issues/1184
``ctx.Cookies`` will look up coookie in response header if cookie is not found in request header
=> 🐛fix: lookup cookie in response header

middleware/csrf/csrf.go, middleware/csrf/csrf_test.go
Bug fixes and improvements to csrf middleware:
Fixed bug where token was deleted from manager storage but cookie was not removed so it was not re-issued.
Re-structured handler switch statement to assume that anything not defined as 'safe' by RFC7231 needs protection.
Removed code deleting token from storage.
Add (re)generate token if not set on all methods.
=> 🩹 Fix: CSRF middleware cookie<>storage bug squashed and other improvements

middleware/logger/logger.go, middleware/logger/logger_test.go
```shell
23:37:45 | 200 |    20ms |       127.0.0.1 | GET     | /js/chunk-vendors.29fe8993.js.map 
==================
WARNING: DATA RACE
Write at 0x00c0004c2ac8 by goroutine 28:
github.com/gofiber/fiber/v2/middleware/logger.New.func2()
github.com/gofiber/fiber/v2@v2.6.0/middleware/logger/logger.go:165 +0x1138
github.com/gofiber/fiber/v2.(*App).next()
github.com/gofiber/fiber/v2@v2.6.0/router.go:126 +0x441
github.com/gofiber/fiber/v2.(*App).handler()
github.com/gofiber/fiber/v2@v2.6.0/router.go:154 +0x1d2
github.com/gofiber/fiber/v2.(*App).handler-fm()
github.com/gofiber/fiber/v2@v2.6.0/router.go:142 +0x54
github.com/valyala/fasthttp.(*Server).serveConn()
github.com/valyala/fasthttp@v1.19.0/server.go:2166 …
```
=> fix logger [WARNING: DATA RACE]

middleware/cache/cache.go, middleware/cache/cache_test.go
I noticed that expiration timestamp is still the same after cache entry has been expired. It leads to situation when right after the entry has been expired, all the next requests that were made right after the eviction are not cached since the expiration time is always behind the expiration deadline.
```
-> call - miss
-> call - hit
-> call - hit
-> call - hit
...
(wait for expiration)
...
(now we'll make the calls right after each other)
-> call - miss
-> call - miss
-> call - miss
....
```
This PR contains one-liner fix and updated test.
=> 🐛 Cache Middleware - Update expiration for expired entry

middleware/cache/cache.go, middleware/cache/cache_test.go
This PR is for investigating and fixing the problem with a race condition that is shown by flaky test:
```
=== RUN   Test_Cache_Expired
Error:     cache_test.go:76: Cache should not have expired: 1615964974123514694, 1615964974123857398
--- FAIL: Test_Cache_Expired (2.00s)
```
**Upd**: details in comments
=> 🐛 Cache Middleware - Race condition in the cache expiration logic

middleware/csrf/config.go, middleware/session/config.go, middleware/session/session.go
Fix incorrect comment lines in 2 files:
- middleware/csrf/config.go
- middleware/session/config.go
One question left: in csrf middleware, default value is `Strict`, but in session, its `Lax` (see [line 163-170](https://github.com/iredmail/fiber/blob/master/middleware/session/session.go#L163)). Should we set it to `Strict` too in session by default?
=> Fix incorrect comment lines.

ctx.go, ctx_test.go
I added a method to Ctx and its tests. The method is `ParamsInt`. It helps developers get an integer directly from the request
It is very common to send integers like IDs directly in the route as parameters. I added an utility function, `ParamsInt` to directly get an integer from the Ctx that is passed on each request. It returns zero and an error if the param cannot be found OR if the param is not a valid integer
Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: …
=> ✨ Add method to get an integer directly from the Ctx params (route params)

middleware/cache/cache.go, utils/deprecated.go
Right now, the cache middleware uses methods from utils that are marked as deprecated. I've changed them to use the underlying and not deprecated methods.
Also: removed the _not-used-and-deprecated_ methods from utils.
✅ 
=> Refactor cache middleware to not-use the deprecated methods 

middleware/session/session.go, middleware/session/store.go
The mutex lock never unlock if the subsequent code return error
This PR mainly to fix deadlock and prevent memory leak issue on `acquireCookie`, allow cookie to release back to pool if `cookie.ParseBytes` return error
=> 🐛 fix: deadlock on session

middleware/monitor/README.md, middleware/monitor/monitor.go
removed print statement for a warning from the monitor.go file in middleware
=> :recycle: Removed Printed Warning

middleware/csrf/README.md
Just fixing a mistake.
The import statement for crsf middleware shows session currently. I assume this is a mistake but if not please correct me
=> 📚 Doc: Correct Session to Crsf in Import Statement

middleware/proxy/config.go, middleware/proxy/proxy.go, middleware/proxy/proxy_test.go
Adding buffer size configuration to proxy middleware.
Probably default should be propagate from fiber server configuration, but I didn't know how to do it
=> [middleware/proxy] add buffer size configuration

middleware/etag/etag.go, middleware/etag/etag_test.go
Skip the middleware if an Etag response header already exists.
This change should be compatible with ```ctx.Fresh()```, you can set the custom header and call it to do the verification.
Also added a test to make sure that the If-Match and 412 responses for Put requests aren't messed up by the middleware to avoid problems with future changes.
Some things to consider:
We could export the ETag generation as a function so users could call it inside their handlers and compare it to return the 412 on their own, currently, there's no way to achieve that easily without using custom tags. However IMO returning the updatedAt as a custom Etag and using that is way more practical so we could keep it like this. …
=> ✨ Etag middleware support to custom etags

middleware/logger/logger.go
Currently, loggger middleware doesn't do anything if it fails to write to the given io.writer. It might be a good idea to at least log something to inform the user there is a problem.
I think it might be a good idea to print the error to stderr to inform the user there is  a problem with logger (rather than doing nothing) also some logging package like logrus do the same thing(you can see the code here   [link to logrus code](https://github.com/sirupsen/logrus/blob/b50299cfaaa1bca85be76c8984070e846c7abfd2/entry.go#L295) )
=> 🐛 Print logger's error to stderr if given io.writer failed

.github/README.md
Just changing broken [https://docs.gofiber.io/middleware/limiter](https://docs.gofiber.io/middleware/limiter) to [https://docs.gofiber.io/api/middleware/limiter](https://docs.gofiber.io/api/middleware/limiter)
=> 🩹 Fix broken Rate Limiter link

app.go, app_test.go, group.go
After mounting an `App` instance or `Group` to an existing instance (root), the handlerCount of the root is not being updated. I came across this issue when I noticed that the startup message showed `Handlers=0` even though my app had mounted a router with multiple handlers.
For example...
```go
router := New()
router.Get("/doe", func(c *Ctx) error {
return c.SendStatus(StatusOK)
})
app := New()
app.Mount("/john", router)
```
... currently results in the following startup message.
You get the same result when mounting the `router` to a Group.
I fixed this by simply adding the handlerCount of the mounted instance to the root App's own handlerCount in the corresponding Mount-function of the App and Group struct.
**Side note**
When writing the tests I noticed that when registering a …
=> 🩹Fix: Startup message doesn't show correct amount of Handlers after mounting

app.go, app_test.go, client.go, ctx.go, ctx_test.go, helpers.go, helpers_test.go, router.go, router_test.go
`fiber.New()` changes the package variables `getBytes` and `getString`, and these are used a lot across the app. This may cause data race problems, as mentioned in the issue #1313, as well as other problems like: when using 2 apps, a second of fiber may override these functions, causing the first app to use incorrect configurations.
In order to avoid sharing app configuration between two created apps, I have moved the `getBytes` and `getString` from the package to the app struct, and fixed the usages of these functions.
- Create the test to show the problem
- Deletes `getBytes` and `getString` function: they should not be package variables.
- Adds `getBytes` and `getString` to the `App` struct
- Default `getBytes` and `getString` uses the same defaults as before: `utils.GetBytes` and …
=> Fix app test parallel

middleware/timeout/README.md
`ctx.Send` sends byte data instead of the text so we need to use `ctx.SendString`, also if an error isn't returned from the function it gives the error `Cannot use 'handler' (type func(ctx *fiber.Ctx)) as the type fiber.Handler`
=> 📝update handler example in timeout

middleware/filesystem/README.md, middleware/filesystem/filesystem.go, middleware/filesystem/filesystem_test.go
Resolves #1308
This adds a parameter called `PathPrefix` to `filesystem.Config` that is prepended to any filepath being read from `filesystem.Root`. This is intended to be used with Go 1.16's `embed.FS`.
A new test has been added to cater for this parameter, and the README has been updated to use this parameter in the section about `embed`.
:)
=> 🔥 Add `PathPrefix` parameter to `filesystem` middleware

ctx.go, ctx_test.go
we should enable `ZeroEmpty` by default
=> 🏗️ chore: enable decoder's ZeroEmpty by default

middleware/limiter/README.md
```Duration``` and ```Store``` are deprecated, so we should show ```Expiration``` and ```Storage``` in example
=> 📚 Change deprecated struct elements

middleware/pprof/pprof.go, middleware/pprof/pprof_test.go
I think the redirected path can be optimized.
For example, if the path is `/debug/pprof/block/`, it better to redirect to `/debug/pprof/block` instead of `/debug/pprof`.
=> fix pprof redirect path

middleware/session/README.md, middleware/session/data.go, middleware/session/session.go, middleware/session/session_test.go
Added a sess.Keys() method who retrive all keys from current session
Related to [retrieve all keys](https://github.com/gofiber/fiber/issues/1333), for short, `sess.Keys()` is a simple way to get all keys from session and iterate over it or debug.
=> feat(middlewares): session keys

ctx.go, ctx_test.go
Resolved #1249 
This adds an additional field called `userContext` which is of type` context.Context`.
It could be set by user.
=> 🔥 Adding user context

middleware/session/README.md, middleware/session/config.go, middleware/session/session.go, middleware/session/session_test.go, middleware/session/store.go, middleware/session/store_test.go
Try to support the need of https://github.com/gofiber/fiber/issues/1110.
I refer to [gofiber/session](https://github.com/gofiber/session) and [fasthttp/session](https://github.com/fasthttp/session) to implement this requirement.
=> 🔥 Customize the source of session_id

middleware/cache/README.md, middleware/cache/cache.go, middleware/cache/cache_test.go, middleware/cache/config.go
Cache middleware to returns `S-Cache` header to show cache status, `hit`, `miss` or `unreachable`
Not using `X-Cache` because I think some CDN uses this value?
=> 🔥 Feature: add cache header to show cache status

internal/msgp/errors.go, internal/uuid/dce.go, internal/uuid/marshal.go, internal/uuid/sql.go, internal/uuid/uuid.go
**Hi!**
I changed all places, where we using `fmt.Errorf` to `errors.New`, because it work much faster without any allocations.
Method `Errorf` needed, when we, for example, pull out the type of variable, or use `Unwrap` method 
So the same situation with `fmt.Sprintf` and `strings.Join`. The last one is better to use: 
Here `d` is a global int variable 
We have 1 allocation with method `Join` because of using int to string conversation 
There are actually many places where we can do this, but it will impair the readability of the code like this:
```Go
- return uuid, fmt.Errorf("invalid urn prefix: %q", s[:9])		
+ return uuid, errors.New(`invalid urn prefix: "` + s[:9] + `"`)
```
Perhaps error handling is not worth the quickest solution.
=> Improve errors handling

middleware/session/README.md, middleware/session/session.go, middleware/session/session_test.go
Please provide enough information so that others can review your pull request:
Added a sess.ExpiresIn() method who set a custom expiration for a session.
Explain the details for making this change. What existing problem does the pull request solve?
Related to #1298 , for short, sess.ExpiresIn() use a custom session expiration insted of default value.
=> 🔥 feat: expiration per session

error.go, error_test.go
This pull request solves exposes the internal errors so that they can be used publicly.
The problem is described in https://github.com/gofiber/fiber/issues/1375.
=> Expose internal errors.

middleware/proxy/README.md, middleware/proxy/config.go, middleware/proxy/proxy.go, middleware/proxy/proxy_test.go
In some cases, we often need to disable certificate validation, so I add `WithTlsConfig` function for proxy.
This function can be used before `Forward`, for example:
```
proxy.WithTlsConfig(tls.Config{
InsecureSkipVerify: true,
})
```
=> add tls config for http client in proxy middleware

middleware/session/session.go, middleware/session/session_test.go, middleware/session/store.go, middleware/session/store_test.go
Fix: Session.Regenerate does not set Session.fresh to be true.
Fix: Session should be regenerated if the session can not be found in the storage.
This PR is intended to close #1395 issue and #1408 issue.
Tests have been added.
Some old tests have been modified.
If there are some questions, I will answer them.
=> Fix: Session middleware issues

app.go, ctx.go, ctx_test.go
Add TrustedProxies feature to prevent HTTP header spoofing. This PR is intended to close #1300 issue.
=> 🔥 Feature: Add TrustedProxies feature

middleware/session/session.go
This PR is intended to close the #1419 issue.
The explanation of the bug is in the following comment.
https://github.com/gofiber/fiber/issues/1419#issuecomment-875422869
=> Fix: copy the data in buffer instead of using original data.

ctx.go, ctx_test.go
I have added an option to specify default value when using ParamsInt, similar to Params method.
This allows us to remove the boilerplate code when default value needs to be applied on error but still keeps the behavior when no default is supplied. 
=> ✨ Add ability to specify default value for ParamsInt

ctx.go, ctx_test.go
Now when we use `filber.Ctx.BodyParser` to deserialize JSON, it uses `filber.Ctx.fasthttp.Request.Body` method internally to take the raw body data, which works fine in most cases.
But when the request body is gzip-compressed, `filber.Ctx.fasthttp.Request.Body` takes the compressed data and there is no way to deserialize it directly.
So in this PR I changed the method inside `filber.Ctx.BodyParser` that takes the request body to `filber.Ctx.Body` method, which automatically detects the encoding of the request body and decompresses it itself. I have also added test cases for compression requests.
=> 🐛 fix parse gzipped body

app.go, utils/bytes_test.go, utils/common.go, utils/convert.go, utils/convert_test.go, utils/strings.go
Removing the use of deprecated functions `GetString`, `GetBytes`, and `ImmutableString`, and altering `convert_test.go` to test the non-deprecated equivalent conversion functions.
This change improves code quality by removing the use of deprecated functions in the framework.
=> ♻️ Refactor: Remove use of deprecated functions

app.go, ctx.go
Add json decoder to config 
This pull request is in reference to [#1452](https://github.com/gofiber/fiber/issues/1452)
=> 📝 Update: Add JSONDecoder to config

ctx.go, utils/http.go, utils/http_test.go
`ctx.BodyParser` was not able to parse vendor specific content types like `application/vnd.api+json; version=1` even though its a valid type of JSON
This solves #1505 
Benchmark details related to this change
```
Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -bench ^(Benchmark_ParseVendorSpecificContentType)$ github.com/gofiber/fiber/v2/utils
goos: darwin
goarch: amd64
pkg: github.com/gofiber/fiber/v2/utils
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Benchmark_ParseVendorSpecificContentType/vendorContentType-12         	23002122	        52.34 ns/op	      16 B/op	       1 allocs/op …
```
=> :bug: Fix: ctx.BodyParser was not able to parse vendor specific content type

middleware/encryptcookie/README.md, middleware/encryptcookie/config.go, middleware/encryptcookie/encryptcookie.go, middleware/encryptcookie/encryptcookie_test.go, middleware/encryptcookie/utils.go
This PR adds a new middleware to encrypt cookie values to increase security
([Similar middleware in Laravel](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Cookie/Middleware/EncryptCookies.php))
Middleware decrypts request cookies and encrypts response cookies.
If a user manually changes the cookie value to something invalid cookie value will convert to `""`.
```go
app.Use(encryptcookie.New())
c.Cookie(&fiber.Cookie{
Name:  "SomeThing",
Value: "A Secret Value Here",
})
// ...
})
```
The middleware uses `AES-256-GCM` by default, and generates a new encryption key on each run but we should always use a secret encryption key like this:
```go
app.Use(encryptcookie.New(
encryptcookie.Config{
Key: …
```
=> 🔥 Feature: Add encrypt cookies middleware

middleware/session/session_test.go, middleware/session/store.go, middleware/session/store_test.go
Should fix #1492 
returned session should not have gotten their ID refreshed if `s.Storage.Get(id)` return nil, otherwise it is unable for session to be `Save()`
=> :bug: session should not regenerate the ID in case Get() returned nil

ctx.go, ctx_test.go
Fix #1518
I've not much experience in FastHTTP, especially in Mutability nature, so this fix put user-defined `context.Context` into `*fasthttp.RequestCtx` with constant key `__local_user_context__`, instead of `fiber.Ctx` struct field, and keeping the `fiber.Ctx` API intact
=> :bug: Fix Mutability issue of UserContext in fiber.Ctx

internal/gopsutil/common/common_windows.go, internal/gopsutil/load/load.go, internal/gopsutil/load/load_bsd.go, internal/gopsutil/load/load_darwin.go, internal/gopsutil/load/load_fallback.go, internal/gopsutil/load/load_freebsd.go, internal/gopsutil/load/load_linux.go, internal/gopsutil/load/load_openbsd.go, internal/gopsutil/load/load_solaris.go, internal/gopsutil/load/load_test.go, internal/gopsutil/load/load_windows.go, middleware/monitor/README.md, middleware/monitor/index.html, middleware/monitor/monitor.go
Now we have same features as [express-status-monitor](https://github.com/RafalWilinski/express-status-monitor).
=> Add one minute load avg for monitor middleware

middleware/limiter/README.md, middleware/limiter/config.go, middleware/limiter/limiter.go, middleware/limiter/limiter_test.go
Related issue: https://github.com/gofiber/fiber/issues/1512
Hi, I saw the issue, and I wanted to contribute.
=> 🔥 Feature: limiter middleware new skip options implemented

middleware/logger/config.go
**Support logger coloring for custom logging formats**
Add a function to check for a valid custom format. A valid format is one having both `${status}` and `${method}`. Fixed #1467
=> ✨ support logging color for custom logging formats

middleware/filesystem/README.md, middleware/filesystem/filesystem.go, middleware/filesystem/filesystem_test.go, middleware/filesystem/utils.go
Fixes: #1546 
```go
github.com/fufuok/fiber/middleware/filesystem# go test -v
=== RUN   Test_FileSystem
=== RUN   Test_FileSystem/Should_be_returns_status_200_with_suitable_content-type
=== RUN   Test_FileSystem/Should_be_returns_status_200_with_suitable_content-type#01
=== RUN   Test_FileSystem/Should_be_returns_status_200_with_suitable_content-type#02
=== RUN   Test_FileSystem/Should_be_returns_status_404
=== RUN   Test_FileSystem/Should_be_returns_status_404#01
=== RUN   Test_FileSystem/Should_be_returns_status_200
=== RUN   Test_FileSystem/Should_be_returns_status_403
=== RUN   Test_FileSystem/Should_list_the_directory_contents
=== RUN   Test_FileSystem/Should_list_the_directory_contents#01
=== RUN …
```
=> Fix: file opening path and directory browsing path of filesystem

ctx.go, ctx_test.go
This PR fixes #1499.
As described in the bug, after the `sendFile()` is called, `c.OriginalURL()` doesn't get restored. This PR fixes that issue.
Note: This is my first PR in this project, let me know if it needs any changes :v:
=> :bug: Fix `c.OriginalURL()` changed after `SendFile`

app_test.go, router.go, router_test.go
=> Fix: static file routing path rewrite.

middleware/csrf/README.md, middleware/csrf/config.go
Default is "Strict", it should be "Lax"
Browser defaults are Lax. Fiber using a default of "Strict" is unadvisable as it will cause unexpected behavior. Strict requires HTTP first-party context and disregards requests initiated by third parties. So after navigating to the site from a third party site the safe HTTP methods (GET, HEAD, or OPTIONS) will not set the cookie. For example, a login page would not work by default when navigating to it from google or any other non-first party link.
"With Strict, the cookie is only sent to the site where it originated. Lax is similar, except that cookies are sent when the user navigates to the cookie's origin site. For example, by following a link from an external site. None specifies that cookies are sent on both originating and cross-site …
=> fix(middleware/csrf): CookieSameSite default "Lax"

middleware/monitor/README.md, middleware/monitor/config.go, middleware/monitor/monitor.go, middleware/monitor/monitor_test.go
Add disable html support to monitor middleware.
=> Add disable html support to monitor middleware.

middleware/logger/config.go, middleware/logger/logger.go, middleware/logger/utils.go
- Add NO_COLOR compatibility.
- Use /dev/stdout as default output stream. (fixes: https://github.com/gofiber/fiber/issues/1642)
- Fix coloring with custom formats. (fixes: https://github.com/gofiber/fiber/issues/1609)
=> Improvements for logger middleware

.github/README.md, .github/README_de.md, .github/README_es.md, .github/README_fa.md, .github/README_fr.md, .github/README_he.md, .github/README_id.md, .github/README_it.md, .github/README_ja.md, .github/README_ko.md, .github/README_nl.md, .github/README_pt.md, .github/README_ru.md, .github/README_sa.md, .github/README_tr.md, .github/README_zh-CN.md, .github/README_zh-TW.md, app.go, app_test.go, client.go, group.go, helpers.go, middleware/basicauth/basicauth_test.go, prefork.go, router.go
Set route name by last created route or group.
**Example Use:**
_Code:_
```go
func main() {
app.Get("/", func(c *fiber.Ctx) error { 
...
})
app.Name("index")
app.Get("/doe", func(c *fiber.Ctx) error { 
...
}).Name("homgfgfe")
app.Trace("/tracer", func(c *fiber.Ctx) error {
...
}).Name("tracert")
app.Delete("/delete", func(c *fiber.Ctx) error {
...
}).Name("delete")
a := app.Group("/a")
a.Name("fd.")
a.Get("/test", func(c *fiber.Ctx) error {
...
}).Name("test")
data, _ := json.MarshalIndent(app.Stack(), "", "  ")
fmt.Print(string(data))
app.Listen("localhost:8080")
}
```
_Output:_
```
[
[
{
"method": "GET",
"name": "index",
"path": "/",
"params": null
},
{
"method": "GET",
"name": "homgfgfe",
"path": "/doe",
"params": null
},
{
"method": "GET",
"name": "fd.test",
"path": …
```
=> Add route naming feature.

ctx.go, ctx_test.go
Close #1629 .
Usages
```
func handleSomething(c *fiber.Ctx) error {
// Print true when request came from localhost
fmt.Println(c.IsFromLocal())
return nil
}
```
=> 🔥Feature: add function to check if request came from localhost

middleware/csrf/csrf.go, middleware/csrf/csrf_test.go
This PR closes #1666 
when the following is true
``if manager.getRaw(token) == nil ``
err will be nil otherwise it would have returned on line 40.
So we must set the error before calling `cfg.ErrorHandler(c, err)`
=> 🔧 fix(middleware/csrf): unmatched token returns nil error

app.go, app_test.go
We need to get handler count in some cases (like custom startup message). So i added method to get handler count.
=> Add method the get registered handler count.

app.go, app_test.go, group.go, router.go
It seems that https://github.com/gofiber/fiber/pull/1672 add a function named HandlersCount.
But the field of App struct is called hanlderCount, so I rename them to handlersCount.
=> :bug:fix: rename handlerCount to handlersCount

.github/README_zh-CN.md
Make Chinese translation more elegant.
=> :pencil:docs(zh-CN): improve Chinese translation

ctx.go, ctx_test.go, middleware/logger/README.md, middleware/logger/logger.go, middleware/logger/logger_test.go
**Ctx:**
- Add GetRespHeader.
- Add GetReqHeaders methods.
**Logger Middleware:** 
- Add TagReqHeaders. (closes: https://github.com/gofiber/fiber/issues/1532)
=> Add GetRespHeader, GetReqHeaders and TagReqHeaders for logger mw

middleware/encryptcookie/README.md, middleware/encryptcookie/config.go
=> 🩹 Fix: Add `csrf_` to default encrypt cookie exception (#1631)

app.go, app_test.go
=> :sparkles:feat: add function NewErrors to create multiple new errors

middleware/logger/README.md, middleware/logger/config.go, middleware/requestid/README.md
=> Fix typos in middleware

.github/README_id.md
Translate untranslated words:
- download -> unduh
- WebSocket support -> Mendukung WebSocket
- Route Naming -> Penamaan Route
- default -> bawaan
=> 📝 docs: translate some words to bahasa(ID)

app.go, ctx.go, ctx_test.go
**✨feature: Pass all locals to ctx.Render**
This will by default pass all locals set user ctx.Local to the Template engine.
This could be usefull for setting variables using a middleware.
=> ✨feature: Pass all locals to ctx.Render

app.go, app_test.go, group.go, router.go
Add Route method like [Chi router](https://github.com/go-chi/chi#router-interface).
**Signature:**
`Route(prefix string, fn func(router Router), name ...string) Router`
**Using Example:** 
```
app.Route("/test", func(router fiber.Router) {
router.Get("/john", func(c *fiber.Ctx) error {
return c.SendString("doe")
}).Name("john")
}, "test.")
```
=> :fire: Feature: Add Route() method like Chi router.

ctx.go, ctx_test.go
**Benchmarks:**
_Old_
```
Benchmark_Ctx_Body_With_Compression-4      	  849862	      1233 ns/op	     145 B/op	       7 allocs/op
Benchmark_Ctx_BodyParser_JSON-4            	 4025719	       313.4 ns/op	      32 B/op	       2 allocs/op
Benchmark_Ctx_BodyParser_XML-4             	  314671	      3698 ns/op	    1160 B/op	      24 allocs/op
Benchmark_Ctx_BodyParser_Form-4            	  464664	      3494 ns/op	     360 B/op	      13 allocs/op
Benchmark_Ctx_BodyParser_MultipartForm-4   	  715200	      2160 ns/op	     328 B/op	      12 allocs/op
Benchmark_Ctx_QueryParser-4                	  244102	      4782 ns/op	     856 B/op	      38 allocs/op
Benchmark_Ctx_QueryParser_Comma-4          	  226207	      5551 ns/op	     928 B/op	      44 allocs/op
```
_New_
``` …
```
=> :fire: Feature: Add ReqHeaderParser.

app.go, app_test.go
If error message's type happens interface{}, It can return multiple error strings etc.
```go
func main() {
app := New(fiber.Config{
ErrorHandler: func(c *fiber.Ctx, err error) error {
code := fiber.StatusInternalServerError
var messages interface{}
if e, ok := err.(*fiber.Error); ok {
code = e.Code
messages = e.Message
}
return c.Status(code).JSON(fiber.Map{
"status_code": code,
"status_text": utils.StatusMessage(code),
"messages":    messages,
})
},
})
return NewErrors(fiber.StatusBadRequest, "validatien error 1", "validation error 2")
})
app.Listen(":3000")
}
```
```json
{
"messages": [
"validatien error 1",
"validation error 2"
],
"status_code": 400,
"status_text": "Bad Request"
}
```
---
```go
func main() {
app := New(fiber.Config{
ErrorHandler: …
```
=> Fix NewErrors() and Improve NewError()

client.go, client_test.go
RetryIf function for client agent.
```go
func (a *Agent) RetryIf(retryIf RetryIfFunc) *Agent {
a.HostClient.RetryIf = retryIf
return a
}
```
Examples:
```go
agent.Get("https://example.com").RetryIf(func (req *fiber.Request) bool {
return req.URI() == "https://example.com"
}
```
=> :sparkles:feat: add retryIf function to client agent

app_test.go, group.go
If we use group in group, name of first group won't appear.
**Code:**
```go
func main() {
a := app.Group("/a").Name("a.")
b := a.Group("/b").Name("b.")
b.Get("/hello/", func(c *fiber.Ctx) error {
return c.SendString("d")
}).Name("c")
data, _ := json.MarshalIndent(app.Stack(), "", "  ")
fmt.Print(string(data))
}
```
**Old Output:**
```go
[
[
{
"method": "GET",
"name": "b.c",
"path": "/a/b/hello/",
"params": null
}
],
[
{
"method": "HEAD",
"name": "",
"path": "/a/b/hello/",
"params": null
}
],
...
]
```                                                                                                                                                                                     
**New Output:**
```json
[
[
{
"method": "GET",
"name": "a.b.c",
"path": "/a/b/hello/", …
```
=> :bug: fix: route naming when to use group in group.

app.go
Fixed documentation typo of JSONDecoder field in Config (server settings) structure.
json library for **encoding** => json library for **decoding**
=> :memo: Fix: typo

middleware/limiter/limited_fixed.go, middleware/limiter/limited_sliding.go
- The variable 'expire' doesn't imply why it is different from 'expiration', so I made its name more specific.
- Comments mentioning it were changed accordingly.
=> Doc(limiter): clarify variable name 'expire'

app.go, app_test.go, router.go
For HTML <a> element's download attribute, serverside header response must include "Content-Disposition: attachment" for cross origin request.
=> Add direct download option when serving static files

ctx.go, ctx_test.go
Adds the ability to restart the route handling e.g. after an internal redirect.
Fixes #1731
The example from #1731 is changed in the following way:
```go
package main
import "github.com/gofiber/fiber/v2"
func main() {
app.Get("/new", func(c *fiber.Ctx) error {
return c.SendString("new")
})
app.Use(func(c *fiber.Ctx) error {
c.Path("/new")
// instead of c.Next() as this would execute the catch-all handler
// note that this example works because GET /new is registered first. Infinit loops are possible with RestartRouting.
return c.RestartRouting()
})
app.Use(func(c *fiber.Ctx) error {
// …
```
=> 🔥 Feature: Add ability to restart route handling

error.go, error_test.go
probably solves https://github.com/gofiber/fiber/issues/1751 and https://github.com/gofiber/fiber/issues/1738
=> :bug: add missing json errors

internal/memory/memory.go
10ms interval time causes big performance degradation. So i made it 1 second. Potentially closes https://github.com/gofiber/fiber/issues/1371. 
**Before:**
```
Running 10s test @ http://127.0.0.1:5000
12 threads and 100 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     2.99s     1.91s    6.69s    52.54%
Req/Sec       -nan      -nan   0.00      0.00%
396049 requests in 10.00s, 94.05MB read
Requests/sec:  39612.49
Transfer/sec:      9.41MB
```
**After:**
```
Running 10s test @ http://127.0.0.1:5000
12 threads and 100 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     2.12s     1.24s    4.61s    55.31%
Req/Sec       -nan      -nan   0.00      0.00%
602860 requests in 10.00s, 143.16MB read
Requests/sec:  60310.52
Transfer/sec:     14.32MB
```
=> :zap: change default gc interval of internal/memory

middleware/cache/cache.go
Hello. There's a problem with mutex lock in fiber cache middleware. See the example below:
```
package main
import (
"github.com/gofiber/fiber/v2/middleware/cache"
_ "net/http/pprof"
"time"
)
func main() {
app.Use(cache.New(cache.Config{
Next: func(c *fiber.Ctx) bool {
if c.Route().Path == "/health" {
return false
}
return true
},
}))
app.Get("/health", func(c *fiber.Ctx) error {
return c.SendString("ok")
})
app.Get("/test", func(c *fiber.Ctx) error {
time.Sleep(5 * time.Second)
return c.SendString("sleep-test")
})
if err := app.Listen(":9001"); err != nil {
panic(err)
}
}
```
Try accessing /test and /health endpoints. Health endpoint will respond only when Test endpoint has finished. Thus, the slowest endpoint becomes the bottleneck for …
=> Fix cache mutex lock

internal/go-json/encoder/code.go, internal/go-json/encoder/encoder.go
https://github.com/goccy/go-json/releases/tag/v0.9.4
=> 🤖 bump: goccy/go-json to 0.9.4

middleware/proxy/proxy.go, middleware/proxy/proxy_test.go
fixes https://github.com/gofiber/fiber/issues/1762
=> Fix: incorrect scheme on proxy.Do (#1762)

utils/strings.go, utils/strings_test.go
This PR fix a edge case of `utils.Trim(" ", ' ')` returning `" "` instead of `""`.
close #1774
fix edge case `utils.Trim(" ", ' ')` and `Trim("  ", ' ')`
not a fan of emojis, choose whatever you like when merging.
=> fix: `utils.Trim` should trim all string content

app.go, app_test.go
fix https://github.com/gofiber/fiber/issues/1767
backward compatible
=> 🩹 fix: backwards incompatible change to fiber.Error

utils/bytes.go, utils/bytes_test.go, utils/strings.go, utils/strings_test.go
=> fix: utils.TrimBytes should trim all content

ctx_test.go, helpers.go, helpers_test.go
Pull request should fix the problem from #1574
=> Fix for "Why net.Addr is fiber.testAddr, not *net.TCPAddr?🤗 #1574"

ctx.go, ctx_test.go, middleware/proxy/proxy.go, middleware/proxy/proxy_test.go
This PR fixes two issues.
1.  Restore original URL after proxy.Do [issue](https://github.com/gofiber/fiber/issues/1786)
The proxy.Do method changes the c.OriginalURL() while setting the requestURI  `req.SetRequestURI(addr)`
Since  `proxy.Do` can be used inside the fiber handlers, it will change the origialURL() since the reference to the context is passed.  To fix this behaviour, I am resetting it once the proxy is done.
2. The similar [issue](https://github.com/gofiber/fiber/issues/1499) was raised for `sendFile` and  a fix was merged. However. I find that the fix is not working.
Because of the current …
=> Restore Original URL of the context after changing it

app.go
closes https://github.com/gofiber/fiber/issues/1406 and https://github.com/gofiber/fiber/pull/1570
=> :memo: fix doc inconsistents of storage

internal/go-json/cmd/generator/main.go
`$ go generate ./...` generates panic as import paths have changed over time.
This commit free this command execution from panics.
When running `$ go generate ./...`, the command panics with the following error message :
```
panic: open <parent_of_fiber_root_directory>/fiber/internal/encoder/vm/vm.go: no such file or directory
goroutine 1 [running]:
main.main()
<parent_of_fiber_root_directory>/fiber/internal/go-json/cmd/generator/main.go:314 +0x6c
exit status 2
internal/go-json/cmd/generator/main.go:311: running "go": exit status 1
```
The culprits reside in the filepath.Join() statements in :
```go …
```
=> 🐛 Fix go-json generator.

router.go, router_test.go
- Reduces reads from / writes to slices
- Reduces reads from maps
- Increases sorting speed
=> :zap: Optimize App.buildTree()

ctx.go, ctx_test.go
closes #1802
The PR solves the issue of parsing query params that contains array key in `[]` format. Following type of keys are parsed and the tests are added:
- `data[]=john&data[]=doe`
- `data[0][name]=john&data[0][age]=10&data[1][name]=doe&data[1][age]=12` // This will be parsed to a struct
- `data.0.name=john&data.0.age=10&data.1.name=doe&data.1.age=12`
=> :adhesive_bandage: Allow parsing of square bracket query param

internal/go-json/decoder/int.go, internal/go-json/decoder/stream.go, internal/go-json/decoder/string.go, internal/go-json/encoder/compiler_norace.go, internal/go-json/encoder/compiler_race.go
The updates in json library [seems](https://github.com/goccy/go-json/blob/master/CHANGELOG.md#v096---20220322) to justify a patch release as well.
=> :up: bump goccy/go-json to 0.9.6

utils/bytes.go, utils/bytes_test.go, utils/strings.go, utils/strings_test.go
My original assumptions were wrong, but along the way I improved the tests/benchmarks and fixed a bug in `EqualFold`.
=> :bug: utils: fix EqualFold and docs

app_test.go, middleware/cache/cache_test.go, middleware/logger/logger_test.go, router.go
**This pull request alters the routing behaviour of Fiber to return an instance of `*fiber.Error` when a handler cannot be found to service a given request.** Prior to this commit, Fiber formed a plain-text response on-the-fly that cannot be modified by users of the framework.
This change means that errors resulting from no matching handlers being found would be routed via `fiber.App.config.ErrorHandler`, just like other errors are within Fiber.
**This change allows users to customise the look of their 404 page**, for example, to serve a proper HTML page instead of serving plain-text.
**Additionally, this would remove the need to add a custom 404 handler to the end of the call stack [as documented here](https://docs.gofiber.io/extra/faq#how-do-i-handle-custom-404-responses), which …
=> RFC: Return an instance of `*fiber.Error` when no handler found

app.go, app_test.go, group.go
Fix for "🐛 Sub fiber's error handlers not working #1839"
=> Fix for "🐛 Sub fiber's error handlers not working #1839"

ctx.go, ctx_test.go
**Signature:**
`func (c *Ctx) AllParams() map[string]string`
**Benchmark Result:**
`Benchmark_Ctx_AllParams-4   	 2544381	       530.9 ns/op	     336 B/op	       2 allocs/op`
**Closes:**
https://github.com/gofiber/fiber/issues/1816
=> :sparkles: feature: add AllParams method

ctx.go, ctx_test.go
**Closes:** https://github.com/gofiber/fiber/issues/1850
**Example:**
```go
// /user/fiber?data[0][name]=john&data[0][age]=10&test=doe
c.RedirectToRoute("user", Map{
"name":    "fiber",
"queries": map[string]string{"data[0][name]": "john", "data[0][age]": "10", "test": "doe"},
})
```
**Benchmark Results:**
```
Benchmark_Ctx_RedirectToRoute-4   	 3782589	       306.6 ns/op	      16 B/op	       1 allocs/op
Benchmark_Ctx_RedirectToRouteWithQueries-4   	  981728	      1315 ns/op	     376 B/op	       4 allocs/op
```
I didn't use "url" lib because of it makes extra allocations (+5 allocs). I think this way is faster and more elegant.
=> :sparkles: feature: support adding queries to RedirectToRoute

ctx.go
This pr fixes a typo in the ParamsInt() function.
=> ✏️ Typo fix in ParamsInt()

ctx.go, ctx_test.go
=> Fix cannot process array of values in `application/x-www-form-urlencoded` request

utils/README.md, utils/common.go, utils/common_test.go
This is my attempt to make the function faster and also handled the empty string case.
If I understood correctly from the report, this function actually turned out faster.
=> utils: ConvertToBytes: empty string case

client.go, middleware/cache/cache.go, middleware/cache/cache_test.go
Even if `ExpirationGenerator` was provided in cache config, `Expiration` was used anyway.
fixes #1869
=> :bug:  Fix expiration time in cache middleware

middleware/favicon/favicon.go
Increase readability / follow best practices.
=> Refactor favicon middleware, avoid magic numbers.

app.go
Spliting []dump into dumps, and editing the dump[1] to = req.URL.String(), so we can tests itens that depends on querys from the request.
=> Spliting dump request to add Query 🐛 🚩 

middleware/session/session.go
Session middleware should always update client cookie so that cookie expires at the same time as session.
=> fix middleware/session update cookie.

app_test.go, client.go
it seems there are no big problem in client since it was created. so we should remove the warning.
closes https://github.com/gofiber/fiber/issues/1923
=> :broom: client: remove beta warning

middleware/logger/logger.go
This change affects TagLatency in middleware logging. 
Currently if you don't change the default format the latency output is using millisecond as rounding, however if you configure a custom logging message format it outputs using time.Duration (string) serialization.
I can enumerate two problems:
- Standard between the two options (Default and Custom Format)
- time.Duration will output characters in UTF8 and UNICODE (UTF-16) according to its serialization unit (microseconds)
This PR suggests replacing time.Duration serialization to millisecond, the same used in DefaultFormat.
=> Logging Middleware - TagLatency doesn't have standard format between modes

ctx.go, ctx_test.go
**Hello, This PR is binds the param string to a struct**
**Parse path parameters and body parameters using a struct**
```go 
app.Put("/user/:id", func(ctx *Ctx) error {
type User struct {
// uri
ID uint `uri:"id" validate:"required"`
// body
Username string `json:"username" validate:"required"`
Age      int    `json:"age"`
}
var (
d = new(User)
)
// params parser
_ = ctx.ParamsParser(d)
// body parser
_ = ctx.BodyParser(d)
// then validate
validate.Struct(d)
return nil
})
```
=> add: params parse

middleware/proxy/proxy_test.go, path.go, path_test.go
Add possibility for parameters before custom verb
=> Closes #1931 "🤗 How to get path param before a custom verb?"

app.go, app_test.go, color.go, listen.go, listen_test.go, middleware/logger/logger.go, middleware/logger/logger_test.go, middleware/logger/utils.go
close https://github.com/gofiber/fiber/issues/1890
=> :sparkles: feature: customizable colors

hooks.go, hooks_test.go, prefork.go
Add Hooks that can get the PID of a child process forked from the master process.
Currently, in the Prefork mode of fiber, the PID of the child process forked from the master process cannot be obtained, so CPU Affinity cannot be set automatically using commands such as taskset.
To maximize performance in Prefork mode, each child process should be pinned to a specific CPU core.
To make this possible, I will add a new Hooks.
```go
func main() {
app := fiber.New(fiber.Config{
Prefork: true,
})
app.Hooks().OnFork(func(pid int) error {
fmt.Printf("Forked child process %d\n", pid)
return nil
})
return c.SendString("Hello, World 👋!")
})
app.Listen(":3000")
}
```
```
Forked child process 18331
Forked child process 18332
Forked child process 18333
Forked …
```
=> 🔥 Add OnPrefork Hooks so you can get the PID of the child process.

app.go, app_test.go, listen.go, listen_test.go
When the app name contains non-ascii chars (that are stored on more than 1 byte) , the padding around it in the startup message becomes incorrect. The veritable length of the app name can be obtained by getting the length of the underlying rune slice, like `len([]rune(s))`.
I added a test (`Test_App_Master_Process_Show_Startup_MessageWithAppNameNonAscii`) that creates an app with a name containing accentuated letters.
=> :art: Fix padding around app name in startup message when containing non-ascii characters

.github/workflows/test.yml, ctx.go, ctx_test.go, helpers.go, router.go, router_test.go
Some benchmarks make extra allocs after https://github.com/gofiber/fiber/pull/1928 because of new context's type is interface. This PR aims to fix these benchmarks.
**Comparision of master/v3-fix-benchmarks**
```sh
Benchmark_AcquireCtx-4                                                                    5              0              -100.00%
Benchmark_Ctx_Accepts-4                                                                   0              0              +0.00%
Benchmark_Ctx_AcceptsCharsets-4                                                           0              0              +0.00%
Benchmark_Ctx_AcceptsEncodings-4                                                          0              0              +0.00%
Benchmark_Ctx_AcceptsLanguages-4 …
```
=> v3: fix benchmark results

app.go, app_test.go
details are explained in #1996
add a `defer` in `app.Test` so `runtime.Goexit` can be handled.
=> fix infinitely `app.Test`

middleware/proxy/proxy.go, middleware/proxy/proxy_test.go
Fix proxy overwrote the wrong scheme
close #2001
=> 🐛 bug: fix proxy overwrote the wrong scheme

app.go, client.go, group.go, internal/fasttemplate/template.go, internal/fwd/reader.go, internal/go-ole/guid.go, internal/gopsutil/common/common.go, internal/gopsutil/common/common_windows.go, internal/gopsutil/cpu/cpu_solaris.go, internal/gopsutil/net/net_linux.go, internal/gopsutil/net/net_windows.go, internal/isatty/isatty_windows.go, internal/msgp/defs.go, internal/msgp/elsize.go, internal/msgp/errors.go, internal/msgp/extension.go, internal/msgp/file.go, internal/msgp/read_bytes.go, internal/msgp/write.go, internal/msgp/write_bytes.go, internal/schema/doc.go, internal/template/html/html.go, internal/uuid/dce.go, internal/uuid/hash.go, internal/uuid/version4.go, internal/wmi/swbemservices.go, internal/wmi/wmi.go, listen.go, middleware/cache/manager_msgp.go
- Add missing copyrightes for some files.
- Run `gofmt -s .`
=> :memo: docs: gofmt & add missing copyright texts

app.go, ctx.go, ctx_test.go, utils/xml.go, utils/xml_test.go
=> :sparkles: feature: add XML to context.

app.go, hooks.go
Hook methods aren't shown in https://pkg.go.dev/github.com/gofiber/fiber/v2#pkg-overview. This PR fixes it by making `hook` -> `Hook`.
=> :memo: docs: make Hooks public

middleware/monitor/config.go, middleware/monitor/config_test.go
Fix monitor middleware ignores custom settings if default title is used.
close #2019
=> 🐛 monitor middleware - fix ignore custom settings

utils/strings.go
replace `utils.EqualFold` signature from `func EqualFold(b, s string) bool` to `func EqualFold[S byteSeq](b, s S) bool`
and add a private interface to utils.
```golang
type byteSeq interface {
~string | ~[]byte
}
```
this will make `utils.EqualFold` support comparing bytes like `bytes.EqualFold`
And golang compiler will go monomorphization, which we will have a zero performance cost.
We can also make function like `Trim*` to be generic functions too but I'd like to just change this first for discussion.
Use emojis on commit messages so it provides an easy way of identifying the purpose …
=> ✨ v3 (enhancement): add `[]byte` support to `utils.EqualFold`

client.go, client_test.go
test may fail with race problem.
```text
==================
--- FAIL: Test_Client_Unsupported_Protocol (0.00s)
testing.go:1319: race detected during execution of test
--- FAIL: Test_Client_Agent_Custom_Response (0.01s)
testing.go:1319: race detected during execution of test
--- FAIL: Test_Ctx_ClientHelloInfo (0.00s)
testing.go:1319: race detected during execution of test
--- FAIL: Test_Client_Agent_RetryIf (0.00s)
testing.go:1319: race detected during execution of test
--- FAIL: Test_Client_Agent_Dest/enough_dest (0.00s)
testing.go:1319: race detected during execution of test
testing.go:1319: race detected during execution of test
--- FAIL: Test_Client_Agent_MaxRedirectsCount (0.01s)
--- FAIL: …
```
=> client: fix `Agent` use after free

app.go, ctx.go, ctx_test.go
=> fixes #2016 - make IP() and IPs() more reliable

ctx.go, ctx_test.go
Try to fix case sensitivity for parameters in GetRouteURL.
close #1907 
=> 🐛 bug: Case sensitivity for parameters in GetRouteURL

app.go, app_test.go, ctx.go, ctx_test.go, listen.go
should fix https://github.com/gofiber/fiber/issues/2025 but not tested yet.
=> :bug: bug: make tlsHandler public to use it with Listener

middleware/csrf/README.md, middleware/csrf/config.go, middleware/csrf/csrf.go, middleware/csrf/csrf_test.go, middleware/csrf/extractors.go
This PR Fixes #2051 
- It makes cfg.Extractor an exported field
- It renames built-in extractor creation functions so they are exported
- It updates godocs comments and README.md with the new behavior
- A test was written with a custom extractor
- It remains downwardly compatible
=> 🚀 [Feature]: middleware/csrf custom extractor

path.go, path_test.go
It was causing regex matching problem to remove `\` chars from regex constraint data for regex matchers like `\\d{4}-\\d{2}-\\d{2}`. To fix this, we don't remove escape chars for regex parameters. Also we no longer need to add escape chars before routing-specific characters for regex constraints.
=> :bug: bug: fix regex constraints

helpers.go, helpers_test.go, listen.go, listen_test.go
We can't reuse old listeners for prefork. So it means, we're not able to use prefork with Listener(). I removed this part because of it's broken. 
`Fasthttp also doesn't support it.`
Fixes https://github.com/gofiber/fiber/issues/1254
=> :bug: bug: remove prefork support from custom listeners

middleware/envvar/README.md, middleware/envvar/envvar.go, middleware/envvar/envvar_test.go
=> 🐛 Fix: EnvVar middleware parses base64 incorrectly

middleware/logger/README.md, middleware/logger/config.go, middleware/logger/default_logger.go, middleware/logger/logger.go
- Don't create mutex in each request.
- Use pointer to define LoggerData. Otherwise, we always copy it
=> v3: fix logger benchmarks

path.go, path_test.go
Fix route patterns like:
- `/:lang<len(2)>/videos/:page<range(1,1000)>/`
- `/:lang/videos/:page<range(1,1000)>/`
- `/:lang<len(2)>/videos/:page/`
Fixes https://github.com/gofiber/fiber/issues/2076
=> :bug: bug: fix constraints when to use multiple params

middleware/cache/README.md, middleware/cache/cache.go, middleware/cache/cache_test.go, middleware/cache/config.go
We may need to cache some methods according to our needs. I think we should be able to set methods to cache.
=> :broom: update: add methods configuration for cache middleware

ctx.go, ctx_test.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Explain the _details_ for making this change. What existing problem does the pull request solve?
`ctx.SendStream(r)` with huge size reader will cause huge memory usage and may cause out of memory instead of streaming response.
```golang
package main
import (
"fmt"
"io"
"net"
)
type zeroReader struct {
max     int
current int
}
func (r *zeroReader) Read(p []byte) (int, error) {
fmt.Println("read", len(p), float64(r.current)/float64(r.max), r.current, r.max)
if r.current >= r.max {
return 0, io.EOF
}
toRead := r.max - r.current
if toRead > len(p) {
toRead = len(p)
}
for i := 0; i < toRead; …
```
=> fix `ctx.SendStream(io.Reader)` huge memory usage

router.go
=> :pencil2:  fix typo

ctx_test.go
=> :white_check_mark: test: fix Test_Ctx_ParamParser route param

internal/gopsutil/net/net_darwin.go, middleware/proxy/README.md, middleware/proxy/config.go, middleware/proxy/proxy.go, middleware/proxy/proxy_test.go
Fixes https://github.com/gofiber/fiber/issues/2116
- In some scenarios the user need set up some complex client config via custom client
- The case of a global client only gives the user no way to set up special configurations for only one middleware
so this pr allow to use custom client and  distinguish global client and custom client in proxy mw and compatible with previous logic.
Use emojis on commit messages so it provides an easy way of identifying the purpose or …
=> :sparkles: feat:  support to set client in proxy mw

ctx.go, router.go, router_test.go
Improve benchmarks related to next, handler
- Benchmark_Router_Handler-2 191.4 ns/op -> v3-fix-benchmarks
- Benchmark_Router_Handler-2 276.3 ns/op -> v3-beta 
- Benchmark_Router_Handler-2 164.6 ns/op -> master
=> v3: fix benchmark results related to handler, next

ctx.go, ctx_test.go, helpers.go, utils/http.go
`application/javascript` MIMEtype has been changed to `text/javascript` as per [RFC 9239](https://www.rfc-editor.org/rfc/rfc9239#name-text-javascript) which obsoletes [RFC 4329](https://www.rfc-editor.org/rfc/rfc4329).  As per this RFC, `text/javascript` is now COMMON whereas all the other media types including `application/javascript` have been marked as OBSOLETE.
=> Switch to text/javascript as per RFC9239

middleware/session/data.go
This pull requests fixes possible memory leak in session middleware while golang/go#20135 is not resolved
Fixes #2149
=> 🐛 Fix: Reset d.Data instead of deleting keys in it

ctx.go, ctx_test.go
Fix the problem when the server is behind more than 2 proxies and c.BaseURL(), c.Protocol(), c.Hostname() will return the list instead of the first variable.
```go
func LoginHandler(c *fiber.Ctx) error {
fmt.Println("BaseURL: "+c.BaseURL())
fmt.Println("Protocol: "+c.Protocol())
fmt.Println("Hostname: "+c.Hostname())
}
```
```
BaseURL: https, https://hello.world.com, hello.world.com
Protocol: https, https
Hostname: hello.world.com, hello.world.com
```
So this PR will fix these functions to return only first variable from list
```
BaseURL: https://hello.world.com
Protocol: https
Hostname: hello.world.com
```
Fixes https://github.com/gofiber/fiber/issues/2151
Use emojis on commit messages so it provides an easy way of identifying the purpose or …
=> 🩹 Fix: handle multiple X-Forwarded header

ctx.go, ctx_test.go, utils/ips.go, utils/ips_test.go
This commit makes `c.IP()` and `c.IPs()` faster, especially when IP validation is enabled.
Benchmarks on my machine after this commit:
```
> go test -v -run=ctx_test.go -bench=Benchmark_Ctx_IP
goos: darwin
goarch: amd64
pkg: github.com/gofiber/fiber/v2
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Benchmark_Ctx_IPs
Benchmark_Ctx_IPs-12                                             5892488               202.4 ns/op            48 B/op          1 allocs/op
Benchmark_Ctx_IPs_v6
Benchmark_Ctx_IPs_v6-12                                          3978466               302.2 ns/op           128 B/op          1 allocs/op
Benchmark_Ctx_IPs_With_IP_Validation
Benchmark_Ctx_IPs_With_IP_Validation-12                          4453332               268.4 ns/op            48 B/op          1 allocs/op …
```
=> 🚀 Make IP validation 2x faster

internal/memory/memory.go, internal/memory/memory_test.go, internal/storage/memory/config.go, internal/storage/memory/memory.go, internal/storage/memory/memory_test.go, middleware/limiter/limiter_fixed.go, middleware/limiter/limiter_sliding.go, utils/time.go, utils/time_test.go
until then it was not clear for which internal memory storage is used, this i tried to describe better and optimize the code for it
the code of the storages have been updated
i also provided functionalities which create timestamps more performant when needed
=> Improve memory storage

app.go
Remove this change (https://github.com/gofiber/fiber/pull/1909).
Fix test when using query string parameter.   
When you use `/foo?bar=boo`, your test case should able to QueryParser parameter from fiber.Ctx:
```
func ListResource(c *fiber.Ctx) error {
mrf := new(models ResouceFilter)
if err = c.QueryParser(mrf); err != nil {
return sendError(c, http.StatusBadRequest, err)
}
```
=> [Bug] Fix query string parameter pass to fiber context

middleware/cache/README.md, middleware/cache/cache.go, middleware/cache/cache_test.go, middleware/cache/config.go
Added noCache function for checking Cache-Control: no-cache in the request header
If the request header contains Cache-Control: no-cache it will skip getting the cached entry and proceeds to cache the response.
=> 🚀 [Feature]: Cache-Control: no-cache

middleware/recover/config.go, middleware/recover/recover.go
Use `Stack()` in `runtime/debug`, not in `runtime`, to get the panic stack trace info cuz the one in `runtime/debug` is a more convenient wrapper provided by Go team to print stack trace info, see https://github.com/golang/go/issues/12363, besides, the current implementation only prints the first 1024 bytes, which might result in the missing vital information in the content after 1024 bytes, and the new approach resolves this issue by printing the full stack trace info.
=> :recycle: Leverage runtime/debug to print the full stack trace info

middleware/pprof/README.md, middleware/pprof/config.go, middleware/pprof/pprof.go, middleware/pprof/pprof_test.go
In systems with multiple ingress endpoints all sharing the same load balancer and base URL, it is common to place servers behind a URL prefix. To facilitate this, this PR allows the pprof middleware to define a URL Prefix during configuration so that the endpoints are served on an appropriate URL.
=> Add URL prefix to pprof middleware

app.go, app_test.go, group.go
Express-like multiple-prefix support for Use methods.
=> :sparkles: feature: add multiple-prefix support to app.Use() and group.Use()

utils/convert.go
Fixes https://github.com/gofiber/fiber/issues/2180
This is also 2 ns/op faster than old way.
=> :broom: update: replace UnsafeBytes util with suggested way

ctx.go
We had a discussion about this in https://github.com/gofiber/helmet/pull/74.
=> ctx: make Secure() also report whether a secure connection was established to a trusted proxy

app.go, helpers.go, mount_test.go
Between version v2.23.0 and v2.24.0 the behavior of Mount changed with regard to how the child's ErrorHandler is used. Before v2.24.0 if the child's error handler was not set, then it used the parent's error handler. From v2.24.0 to v2.39.0 (most recent as of this PR) the behavior is to use the child's error handler (which, even when it isn't explicitly set, is set to the DefaultErrorHandler by `New()`).
This change fixes that issue and provides a way for others to fix similar issues as they arise by checking if the value was explicitly configured.
=> Track Configured Values

middleware/logger/config.go, middleware/logger/logger.go, middleware/logger/logger_test.go
=> :sparkles: Add callback function for middleware/logger

middleware/logger/README.md
=> :memo: Update middleware/logger docs

mount.go, mount_test.go
Fix mounting scenarios like 
```go
app := New()
dynamic := New()
apiserver := New()
apiroutes := apiserver.Group("/v1")
apiroutes.Get("/home", func(c *Ctx) error {
return c.SendString("home")
})
dynamic.Mount("/api", apiserver)
app.Mount("/", dynamic)
```
=> :bug: bug: fix mounting when mount prefix is `/`

middleware/filesystem/README.md, middleware/filesystem/filesystem.go
In #2246 middleware/filesystem was changed to handle url encoded values on it's own. This change is not necessary. A documentation update is enough.
=> :memo: middleware/filesystem does not handle url encoded values on it's own

ctx.go, ctx_test.go
Presently, if a bind value passed when calling `c.Render` has the same key as a default value passed in middleware using `c.Bind`, the default value overwrites the value set with `c.Render`. Here is a [small demonstration](https://github.com/cwinters8/fiber-overwritten-bind) of the behavior. If you run that program, you will see that instead of the expected "Home" value being rendered in the h1 tag, the "default" value that was set with `c.Bind` is rendered.
This PR addresses the described issue of overwritten bind variables.
I indicated "Bug fix" here as I have made a change that *seems* to be non-breaking on the surface, because it changes an unintended behavior to the intended behavior. However, I have seen cases in the past where changes like this actually end up breaking someone's …
=> 🩹 Fix: Unintended overwritten bind variables

middleware/logger/logger_test.go, middleware/logger/tags.go
Fixes https://github.com/gofiber/fiber/issues/2232
=> optimize: set byteSent log to 0 when use SetBodyStreamWriter

path.go, path_test.go
Fixes https://github.com/gofiber/fiber/issues/2251
=> :bug: bug: fix regex constraints that contain comma

app.go, ctx.go, ctx_test.go
- Do not use empty `*net.IPNet` in case of an error of `net.ParseCIDR`
- Add test for `ctx.IsProxyTrusted()`
- Optimize `ctx.IsProxyTrusted()` by caching method call
=> :adhesive_bandage: Fix: Properly handle error of "net.ParseCIDR" in "(*App).handleTrustedProxy"

app.go, app_test.go
Fixes https://github.com/gofiber/fiber/issues/2257
=> optimize: add more detail error message in serverErrorHandler

middleware/logger/logger_test.go, middleware/logger/tags.go
Fixes https://github.com/gofiber/fiber/issues/2258
=> optimize: latency use lowest time unit in logger middleware

path.go, path_test.go
https://github.com/gofiber/fiber/issues/2138
=> Match function

app.go, app_test.go, middleware/compress/compress_test.go, middleware/pprof/pprof_test.go, middleware/proxy/proxy_test.go
Cases found by running semgrep with an empty .semgrepignore file
semgrep --lang=go -e '$O.Test($X, $Y)'
Make `app.Test` accept a `time.Duration` timeout instead of an timeout specified in milliseconds.
=> 🚀 v3 Feature: Make app.Test accept a time.Duration timeout

middleware/limiter/README.md
Noticed a small alignment issue while going through the docs.
=> 📝docs(middleware): fix alignment in limiter example

middleware/logger/config.go
=> Fix: logger color output

client_test.go, ctx.go
Fixes https://github.com/gofiber/fiber/issues/2291
=> :adhesive_bandage: bug: use `app.getString, app.GetBytes` instead of `utils.UnsafeString, utils.UnsafeBytes` in `ctx.go`

ctx.go, ctx_test.go, helpers.go
This pull request adds a new feature to the codebase - an Integer Query URL Parser. This parser extracts all integers found in the query parameters of a given URL. The parser takes in a single argument, the URL, and returns a list of integers found in the query parameters. This feature can be useful for extracting and analyzing data from web analytics and other online tracking systems. The code has been tested and is ready for review and integration into the main branch.
=> 🔥 write integer Query Parser.

.github/README.md
There is a redundant space between the sentence component and the punctuation in the documentation. This PR removes it.
=> Doc: Remove the redundant space beside a comma

utils/ips.go, utils/ips_test.go
Deleted redundant check for an ipv4 address octet block that is bigger than 255 in utils/ip.go. Also added a testcase for octetblocks that are bigger than 255.
=> 🚨 added testcases and minor algorithm improvment

.github/README.md, .github/README_ckb.md, .github/README_de.md, .github/README_es.md, .github/README_fa.md, .github/README_fr.md, .github/README_he.md, .github/README_id.md, .github/README_it.md, .github/README_ja.md, .github/README_ko.md, .github/README_nl.md, .github/README_pt.md, .github/README_ru.md, .github/README_sa.md, .github/README_tr.md, .github/README_uk.md, .github/README_zh-CN.md, .github/README_zh-TW.md
Figures in README.md are mostly broken with 404 response. This PR corrects them with the new link.
Note that this commit introduces a trailing space removal due to the `.editorconfig` configuration in `.github`.
Fixes #2311
=> 📚 Doc: Correct the figure link in READMEs

middleware/earlydata/README.md, middleware/earlydata/config.go, middleware/earlydata/earlydata.go, middleware/earlydata/earlydata_test.go
Add earlydata middleware to add support for TLS 1.3's early data ("0-RTT") feature.
=> 🚀 Feature: Add earlydata middleware

middleware/filesystem/README.md
=> 📝 docs(filesystem): clean duplicated namespace for example

middleware/encryptcookie/README.md
It's simpler to generate encryption key on CLI
=> openssl rand -base64 32

middleware/earlydata/README.md, middleware/earlydata/config.go, middleware/earlydata/earlydata.go, middleware/earlydata/earlydata_test.go
Add earlydata middleware to add support for TLS 1.3's early data ("0-RTT") feature.
This is a v2 backport of https://github.com/gofiber/fiber/pull/2270.
=> 🚀 Feature: Add earlydata middleware (v2 backport)

middleware/proxy/README.md, middleware/proxy/proxy.go, middleware/proxy/proxy_test.go
Add proxy forward from spesific domain. Hope this helps with the subdomain routing problem and balancer problom in https.
Fixes #2295 #2307
=> add forward from domain

ctx.go, ctx_test.go
Hi!
Before this PR, I wrote this feature for integer variable #2306.
Now I wrote this feature for float64 variables,
With this parser, you can easily extract float values from URL queries. Pass the desired key and the URL string to the parser, and it will return the float value associated with that key. This eliminates the need for manual string parsing and makes retrieving the values you need easier.
=> 🔥 Feature: add queryFloat parser

ctx.go, ctx_test.go
Hi!
Before this PR, I wrote this feature for integer variables https://github.com/gofiber/fiber/pull/2306 And float variables #2328.
Now I wrote this feature for boolean variables,
With this parser, you can easily extract bool values from URL queries. You can pass the desired key and the URL string to the parser, which will return the boolean value associated with that key. This eliminates manual string parsing and makes retrieving the values you need easier.
=> 🔥 Feature: add queryBool parser

middleware/basicauth/basicauth.go, middleware/basicauth/basicauth_test.go
Fix for test basic header as described in RFC 7617, like
Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
Also avoid string buffer alloc in `strings.ToLower` if  string not in lower case, like `Basic`
=> Basic auth alloc

middleware/cors/cors.go, middleware/cors/cors_test.go
This change will replace the `HeaderAccessControlAllowOrigin` response header with `*` rather than reflecting the Origin of the requestor, preventing user exposure to cross origin attacks as mentioned in the issue.
Fixes # [2338](https://github.com/gofiber/fiber/issues/2338)
=> fix cors * behavior #2338

middleware/proxy/README.md, middleware/proxy/proxy.go, middleware/proxy/proxy_test.go
Fixes issue reported on Discord
=> Feature: Add DoRedirects, DoTimeout and DoDeadline to Proxy middleware

internal/storage/memory/memory.go
The fix is to protect the access to s.db and save the result to a local variable.
Description
Fixed inconsistency and also potential data race in proto/table_unmarshal.go:
u.reqFields is read/written 4 times in proto/table_unmarshal.go; 3 out of 4 times it is protected by u.lock.Lock(); 1 out of 4 times it is read without a Lock, which is in func unmarshal() on L260.
A data race may happen when unmarshal() and other func like computeUnmarshalInfo() are called in parallel.
In order to avoid potential data race here, I use u.lock.RLock(); defer u.lock.RUnlock() to make sure that all usages of items is in critical section.
Fixes #2360
Type of change
[ ] Bug fix (non-breaking change which fixes an issue)
[ ] Breaking change (fix or feature that would cause existing functionality to not work …
=> 🐛 [Bug-Fix]: add lock to avoid data race #2360

docs/api/middleware/requestid.md, middleware/requestid/config.go, middleware/requestid/requestid_test.go
https://github.com/gofiber/fiber/issues/2143 allows to use any as key for c.Locals(key, v). The RequestID middleware should be consistent with that.
This allows to use a custom type for context keys, like for other keys. The RequestID is likely read back somewhere else along other context keys.
Fixes #2356
=> :bug: requestid.Config.ContextKey is interface{}

middleware/requestid/requestid.go
origin issue: https://github.com/gofiber/fiber/issues/2350
=> 🚀 [Feature]: middleware/requestid: don't call "Generator" func on existing request ID header

docs/api/app.md
The MountPath coding example showed examples of code such as 
```go
two := New()
...
```
I changed them to make it 
```go
two := fiber.New()
...
```
=> corrected coding typos in MountPath docs section

ctx.go, ctx_test.go, helpers.go, helpers_test.go
Correct the invalid behavior of the `ctx.Accepts` method
Fixes #2383
=> Fix #2383, accepts mimeType

ctx.go, ctx_test.go, docs/api/ctx.md
As discussed, we have [here](https://github.com/gofiber/fiber/pull/2329#issuecomment-1487527990); changed the default value from true to false for the QueryBool function.
=> 💊 Change default value of Querybool from true to false.

middleware/logger/logger.go, middleware/logger/logger_test.go
Fixes #2396, the data race problem in the logger middleware
=> middleware/logger: Fix #2396, data race logger middleware

app.go, app_test.go, docs/api/app.md
The Fiber app offers two shutdown options: `Shutdown` and `ShutdownWithTimeout`. Both of these options internally use a private `shutdownWithContext` method, which is more versatile for those using Fiber. By making `shutdownWithContext` public, we allow developers to create the best strategy for shutting down the app.
=> :rocket: Feature: Public ShutdownWithContext

.github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/feature-request.yaml, .github/ISSUE_TEMPLATE/question.yaml, docs/api/middleware/cache.md, docs/api/middleware/compress.md, docs/api/middleware/cors.md, docs/api/middleware/csrf.md, docs/api/middleware/earlydata.md, docs/api/middleware/encryptcookie.md, docs/api/middleware/envvar.md, docs/api/middleware/etag.md, docs/api/middleware/expvar.md, docs/api/middleware/favicon.md, docs/api/middleware/filesystem.md, docs/api/middleware/idempotency.md, docs/api/middleware/limiter.md, docs/api/middleware/logger.md, docs/api/middleware/monitor.md, docs/api/middleware/pprof.md, docs/api/middleware/proxy.md, docs/api/middleware/recover.md, docs/api/middleware/requestid.md, docs/api/middleware/session.md, docs/api/middleware/skip.md, docs/api/middleware/timeout.md
This fixes several typos in the ISSUE_TEMPLATES, as well as making the middleware documentation markdowns more consistent
=> :books: Docs: Fix typos, and make middleware documentation more consistent

docs/api/middleware/cache.md, docs/api/middleware/monitor.md, docs/api/middleware/proxy.md, docs/api/middleware/skip.md, docs/api/middleware/timeout.md
- Fixed an import issue in `monitor.md` (that was added with #2408, Sorry about that!)
- Added `cache` package to the `custom key and expire time` example
- Added `proxy` package to the `DoDeadline` example
- Added `log.Fatal` to `skip` and `timeouŧ` examples
=> :books: Docs: Fix import and comma issues

middleware/cors/cors.go, middleware/cors/cors_test.go
The issue was that the condition to run `AllowOriginsFunc` was checking `if allowOrigin == ""`, however, `allowOrigin` is, by default if left empty, set to `*` and thus this condition was never being met.
Added a test to cover this case.
Also updated comments on tests around this feature to be more accurate.
Fixes #2422
=> 🐛 fix(cors): Changed condition for 'AllowOriginsFunc'

internal/template/html/html.go, middleware/cache/config.go, middleware/csrf/config.go, middleware/idempotency/idempotency.go, middleware/limiter/config.go, middleware/proxy/proxy.go, middleware/session/config.go, middleware/timeout/timeout.go
=> :rocket: Consistent way of logging and fix middleware log format

docs/api/middleware/filesystem.md, middleware/filesystem/filesystem.go, middleware/filesystem/filesystem_test.go
add filesystem config contentTypeCharset support
Fixes #2434
=> [Feature]: Add filesystem config contentTypeCharset support

utils/convert.go, utils/convert_s2b_new.go, utils/convert_s2b_old.go
Ref. https://github.com/valyala/fasthttp/blob/d2f97fc426ed451e64dc8e35e7f87a1d4a2d7bde/s2b_old.go.
Ref. https://github.com/valyala/fasthttp/blob/d2f97fc426ed451e64dc8e35e7f87a1d4a2d7bde/s2b_new.go.
=> utils: add Go 1.20+ way of converting string to byte slice

mount.go, mount_test.go
=> 🐛 Fix mount route positioning

utils/convert.go, utils/convert_b2s_new.go, utils/convert_b2s_old.go
Ref. https://github.com/valyala/fasthttp/blob/d2f97fc426ed451e64dc8e35e7f87a1d4a2d7bde/b2s_old.go.
Ref. https://github.com/valyala/fasthttp/blob/d2f97fc426ed451e64dc8e35e7f87a1d4a2d7bde/b2s_new.go.
=> utils: add Go 1.20+ way of converting byte slice to string

.github/README.md, .github/README_az.md, .github/README_ckb.md, .github/README_it.md, .github/README_uk.md, .github/README_zh-TW.md
Corrected typo with double '}' in README, README_az, README_ckb, README_it, README_uk, README_zh-TW
=> 📒  Correcting a syntax error in the README

listen.go
Added missed terminal reset, so all future logs not yellow now.
I'm not sure which emotes to choose, lol.
=> fix: reset terminal colors after print routes

internal/gopsutil/common/sleep.go
It was reported in the gopsutil a possible memory leak for the Sleep function, the fix is to in case of the timer being cancelled by the context, checking if the timer isn't stopped and stoping it.
Fixes #2482 
=> :bug: fix: treat case for possible timer memory leak

middleware/limiter/limiter_sliding.go, middleware/limiter/limiter_test.go
Fix Sliding Window limiter when SkipSuccessfulRequests/SkipFailedRequests is used.
Issue [(#2483)](https://github.com/gofiber/fiber/issues/2483)
=> Fix Sliding Window limiter when SkipSuccessfulRequests/SkipFailedRequests is used.

ctx.go
I noticed 2 functions (those being `GetReqHeaders` and `GetRespHeaders`) use `string(...)` instead of `c.app.getString` to convert a byte array to a string
```go
c.Request().Header.VisitAll(func(k, v []byte) {
headers[string(k)] = c.app.getString(v)
})
c.Response().Header.VisitAll(func(k, v []byte) {
headers[string(k)] = c.app.getString(v)
})
```
Using `c.app.getString` is around 16-19% faster, and allocates less. (See benchmark spreadsheets below. Both `c.app.getString`, and `string(...)` was tested on both functions, 100 times.)
Benchmark result for using `string(...)` on `GetReqHeaders`: [GetReqHeaders.xlsx](https://github.com/gofiber/fiber/files/11622573/GetReqHeaders.xlsx)
_(Average 1,756,668 Iterations, 700 ns/op, 357 B/op, 5 allocs/op)_
Benchmark result for using `c.app.getString` …
=> :recycle: Refactor: use c.app.getString instead of string(...)

app.go, app_test.go, group.go, hooks_test.go, router.go
Edited app.Name() method to add a name parameter to reach route unless already assigned. This required looping over app.stack which feels ineffecient but it was the only method of accessing all of the routes that I could find
Resolves #2467 
=> :bug: bug: fix middleware naming and returned values of group methods

docs/api/middleware/logger.md, middleware/logger/config.go, middleware/logger/logger.go, middleware/logger/logger_test.go
https://github.com/gofiber/fiber/issues/2372
=> :rocket: Add DisableColors to set the default output format

ctx_test.go, docs/api/ctx.md, helpers.go, helpers_test.go
Updates the getOffer helper function so that content negotiation follows https://www.rfc-editor.org/rfc/rfc9110#name-content-negotiation-fields, specifically that quality values are considered (also where q=0 type is not acceptable) and that specificity is also considered in a tie, as a final tie breaker client order is used.
Fixes #2387 
=> 🐛fix: update getOffer to consider quality and specificity

.github/workflows/vulncheck.yml
The go team now have an official `govulncheck` action. This heavily simplifies our CI file.
=> Migrate to Golang official govulncheck action

app.go, hooks_test.go, listen.go, prefork.go
Hooks doesn't work properly in prefork mode because of we run them all in child processes. This PR allows them to be used on child or master processes. 
=> :bug: bug: fix onListen hooks when they are used with prefork mode

ctx.go, ctx_test.go, docs/api/ctx.md
This PR adds a new function called `Queries()` to the `Ctx` struct. This function returns a map of query parameters and their values.
=>  🚀 FEATURE: add queries function

.github/workflows/linter.yml, .github/workflows/vulncheck.yml
Disabling caching and using "check-latest" allows setup-go to work properly when being used with `govulncheck`.
I was waiting for the golang team to fix the official action, but it's been over 1 week to add one config option.
=> Disable caching when running govulncheck

docs/api/middleware/logger.md, middleware/logger/config.go, middleware/logger/logger.go
#2493  introduces DisableColors, but it's default value is set to true, which contradicts the documentation:
https://docs.gofiber.io/api/middleware/logger#config
```go
// DisableColors defines if the logs output should be colorized
//
// Default: false
DisableColors bool
```
https://docs.gofiber.io/api/middleware/logger#default-config, as well as https://github.com/gofiber/fiber/blob/master/middleware/logger/config.go#L94
```go
var ConfigDefault = Config{
Next:         nil,
Done:         nil,
Format:       "[${time}] ${status} - ${latency} ${method} ${path}\n",
TimeFormat:   "15:04:05",
TimeZone:     "Local",
TimeInterval: 500 * time.Millisecond,
Output:       os.Stdout,
DisableColors: true,
}
```
and therefore, coloring is disabled by default, and can only be enabled by explicitly …
=> :adhesive_bandage: Fix: default logger color behaviour

docs/api/ctx.md
Typo in ctx.md where parsing is misspelled as pausing. Just a minor issue, no existing issues
=> :pencil2: Fix: typo in ctx.md

app.go, docs/api/log.md, helpers.go, hooks.go, internal/template/html/html.go, listen.go, log/default.go, log/default_test.go, log/fiberlog.go, log/fiberlog_test.go, log/log.go, middleware/cache/config.go, middleware/cors/cors.go, middleware/csrf/config.go, middleware/idempotency/idempotency.go, middleware/limiter/config.go, middleware/proxy/proxy.go, middleware/session/config.go, middleware/timeout/timeout.go, prefork.go
Adding an interface for extending the log library
```go
// AllLogger is the combination of Logger, FormatLogger, CtxLogger and ControlLogger.
// Custom extensions can be made through AllLogger
type AllLogger interface {
Logger
FormatLogger
CtxLogger
ControlLogger
WithLogger
}
```
Pre-set log levels in advance
```go
// Logger is a logger interface that provides logging function with levels.
type Logger interface {
Trace(v ...interface{})
Debug(v ...interface{})
Info(v ...interface{})
Warn(v ...interface{})
Error(v ...interface{})
Fatal(v ...interface{})
Panic(v ...interface{})
}
```
Provides a way to print logs, with default standard output on the console
```go
fiberlog.Info("Hello World!")
fiberlog.Trace("Hello World!")
fiberlog.Debug("Hello World!")
fiberlog.Warn("Hello World!") …
```
=> 🚀 Add Logger interface and fiberlog

docs/api/ctx.md
In the documentation, we have a wrong output of the queries function.
In docs, it said the `Queries` function returns `map[string]string, error`, but it just returns `map[string]string`.
=> 📚 Docs: fix bad documentation on queries function

docs/guide/validation.md
The old validation guide hosted on the docs was a bit outdated. It was good but, it was only for a single object type validation. Instead with this PR I have changed this. Now the validator can handle any type of object and validate within ease.
I have also made easy examples about how to make custom error message format when a context does not fit our validation scheme.
- Improved validation guide
- Custom error message format for validator (near choice)
- A function capable of handling all type of objects data to validate against
- Improvements towards the debug tests and output showcases
- Easy showcase about how to make an custom tag format validation
- I have alot of comments in my code
- Well formated OUTPUT console to provide a better way of understanding
- Easy and adaptable code
=>  - fixed validation-guide

ctx.go, ctx_test.go, docs/api/ctx.md, helpers.go, helpers_test.go, middleware/session/session_test.go
Currently the Ctx.Body() implementation doesn't parse multi content-encoding body, so in order to attend [RFC9110](https://www.rfc-editor.org/rfc/rfc9110#section-8.4-5), the Body method was changed, and a new wrapper method to body raw was made.
Fixes #2085
=> fix: Decompress request body when multi Content-Encoding sent on request headers

internal/gopsutil/net/net_linux.go, internal/gopsutil/process/process_posix.go, middleware/filesystem/filesystem.go
Suggested way by https://pkg.go.dev/os#IsNotExist
=> filesystem: refactor: use `errors.Is` instead of `os.IsNotExist`

middleware/logger/logger_test.go, middleware/logger/tags.go
TagLatency to match gin-gonic/gin defaultLogFormatter, specifically %13v instead of %7v.
With %7v:
```console
| 4.834µs |
| 1.136834ms |
| 1.000066333s |
```
With %13v, like gin https://github.com/gin-gonic/gin/blob/62b50cfbc0de877207ff74c160a23dff6394f563/logger.go#L143:
```console
|       4.333µs |
|    1.133916ms |
|  1.000057458s |
```
And, adds Test_Logger_WithLatency, which proves that the logger would show he smallest unit that makes sense. (except for ns, which is probably too fast for most systems to test).
Fixes #2561
=> 💄 feat(middleware/logger): latency match gin-gonic/gin formatter

docs/api/middleware/proxy.md, middleware/proxy/proxy.go, middleware/proxy/proxy_test.go
=> 🩹 Fix: rename WithTlsConfig method to WithTLSConfig

middleware/logger/logger.go, middleware/logger/logger_test.go
fixes middleware/logger default latency output format to match TagLatency
Fixes #2561 
=> 🐛 fix(middleware/logger): default latency output format

middleware/cache/cache.go, middleware/logger/tags.go
From the Go docs:
> "If the map is nil, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/Cw_wnqYzemu
=> ♻️ Refactor: Remove redundant nil check

docs/guide/routing.md, path_testcases_test.go
=> Replaced double quotes with backticks in all route parameter strings 

middleware/logger/tags.go
Extra spacing when printing response code has been removed when printing with colors.
Fixes #2604
=> [Bug]: Logger Middleware: Enabling color changes padding for some fields #2604 

middleware/filesystem/filesystem.go
```golang
package main
import (
"net/http"
"github.com/gofiber/fiber/v2/middleware/filesystem"
)
func main() {
app.Use(
"/",
filesystem.New(filesystem.Config{
Root: http.Dir("./try-a"),
}),
filesystem.New(filesystem.Config{
Root: http.Dir("./try-b"),
}),
)
app.Listen(":http")
}
```
```sh
$ tree
.
├── main.go
├── try-a
└── try-b
└── index.html
3 directories, 2 files
```
**Wrong response code 404**
```sh
$ curl -I http://localhost/index.html
HTTP/1.1 404 Not Found
Date: Wed, 13 Sep 2023 04:16:23 GMT
Content-Type: text/html
Content-Length: 201
Last-Modified: Wed, 13 Sep 2023 04:00:02 GMT
```
=> [middleware/filesystem]: Set response code

middleware/adaptor/adaptor.go, middleware/adaptor/adaptor_test.go
The main purpose of this PR is to replace `io.ReadAll()` with `io.Copy()` in the Adaptor middleware. The io.ReadAll() although common practice in `net/http` examples will load the whole `body` into memory. This can cause Fiber to use more memory than required and/or affect performance of applications depending on this middleware.
Also added some benchmarks to compare keep track of performance from small to medium size content.
=> 🐛 fix(middleware/adaptor): Reduce memory usage by replacing io.ReadAll() with io.Copy()

ctx.go, ctx_test.go
When we call func c.IPs() parse header x-forwarded-for in some case return invalid data
ex:
```go
app := New()
c := app.AcquireCtx(&fasthttp.RequestCtx{})
defer app.ReleaseCtx(c)
c.Request().Header.Set("x-forwarded-for", "1.1.1.1,8.8.8.8 , /n, \n,1.1, a.c, 6.,6., , a,,42.118.81.169,10.0.137.108")
var res string
b.ReportAllocs()
b.ResetTimer()
for n := 0; n < b.N; n++ {
ips := c.IPs()
res = ips[len(ips)-2]
}
utils.AssertEqual(b, "42.118.81.169", res) // failed in this case. invalid value return: ,42.118.81.169
```
=> :bug: fix parse ips return invalid in abnormal case

ctx.go
I've simplified the function by breaking it down into three trivially simple steps:
Step One: We check if no arguments are provided in the `override` parameter, in which case we have no choice but to return `c.method`. If arguments are provided, we proceed to step two.
Step Two: We take the first string from `override` and validate if it's a valid HTTP Method name. If it's not, it's evident that we need to return the current method from the context. If it is valid, we move on to step three.
Now, in step three, we have a valid HTTP Method in the `override` parameter. We save this method and its code to the context and return the method's name as a string.
This pull request doesn't fix any bugs, but it improves the code's readability.
I decided to submit these changes because my younger …
=> ♻️ Refactor Ctx.Method func to improve code readability

ctx.go, ctx_test.go, docs/api/ctx.md, middleware/idempotency/idempotency.go, middleware/idempotency/response.go, middleware/idempotency/response_msgp.go, middleware/logger/tags.go
Fixes https://github.com/gofiber/fiber/issues/2594
=> ctx: change signatures of GetReqHeaders and GetRespHeaders

app_test.go, ctx_test.go, middleware/adaptor/adaptor_test.go, middleware/favicon/favicon_test.go, middleware/session/session_test.go, middleware/session/store_test.go
=> refactor: use utils.AssertEqual instead of t.Fatal on some tests

ctx.go, ctx_test.go
Fixes https://github.com/gofiber/fiber/issues/2644
=> :bug: bug: fix PassLocalsToView when bind parameter is nil

docs/api/middleware/session.md, middleware/session/store.go, middleware/session/store_test.go
This pull request introduces a new `Delete` method to the `Store` struct in the Fiber's session middleware. The `Delete` method is designed to delete a specific session id from the storage.
The motivation behind this change is to provide more control over individual session management, especially in scenarios like administrator-enforced user logout or user-initiated logout from a specific device session. With the `Delete` method, we can easily delete a specific session, providing a more efficient and flexible way to manage individual user sessions.
This pull request also includes relevant test code to ensure the correct functionality of the `Delete` method. 
```go
app.Post("/admin/session/:id/logout", func(c *fiber.Ctx) error {
// Get session …
```
=> ✨ feat: add Delete method to Store struct in session middleware

ctx.go, ctx_test.go
Method JSONP ignores the custom json encoder
Fixes #2657 
=> Fix jsonp ignoring custom json encoder

middleware/compress/compress_test.go, middleware/filesystem/filesystem_test.go, middleware/pprof/pprof_test.go
by running `go vet ./...` with go latest version there are some warning about loop variable captured by func literal
this is linked to
https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable
and
https://github.com/golang/go/wiki/LoopvarExperiment
```shell
$ go version
go version go1.21.1 linux/amd64
$ go vet ./...
internal/go-ole/variant.go:15:21: possible misuse of unsafe.Pointer
internal/go-ole/variant.go:23:22: possible misuse of unsafe.Pointer
internal/go-ole/variant.go:33:42: possible misuse of unsafe.Pointer
middleware/compress/compress_test.go:60:30: loop variable level captured by func literal
middleware/filesystem/filesystem_test.go:124:63: loop variable tt captured by func literal
middleware/filesystem/filesystem_test.go:126:25: loop variable …
```
=> Fix loop variable captured by func literal

middleware/filesystem/filesystem.go
Set the status to 200 OK for the filesystem middleware `SendFile` func, just before the file is sent.
=> [filesystem middleware] improve status for SendFile

log/default.go, log/default_test.go
Fix incorrect log depth when use log.WithContex
https://github.com/gofiber/fiber/issues/2646
=> 🩹Fix incorrect log depth when use log.WithContext

helpers.go
Documentation for status codes (e.g. `fiber.StatusOK`) mentions that status codes in `helpers.go` were copied from [https://github.com/nginx/nginx/blob/67d2a9541826ecd5db97d604f23460210fd3e517/conf/mime.types](https://github.com/nginx/nginx/blob/67d2a9541826ecd5db97d604f23460210fd3e517/conf/mime.types). However, this source contains nothing about HTTP status codes.
This is most likely a typo, as the status codes appear to be copied from net/http, with two small updates. This PR updates the comment to reflect an accurate source for HTTP status codes.
=> 📚 [Doc] fix incorrect status code source

ctx.go, ctx_test.go, docs/api/ctx.md
Implemented a cookie parser, following the same convention used by BodyParser and QuerryParser context methods.
The parser is a context method which takes a struct pointer as argument and assigns all passed cookies to the relevant fields. It returns an error if any.
The feature was requested as an issue, and provides an easier way to handle multiple cookies, and improves developer experience and development time.
=> Cookie parser

app.go, app_test.go, listen_test.go
Fixes https://github.com/gofiber/fiber/issues/2671
=> :bug: bug: fix path checking on route naming

app.go, app_test.go
Fixes https://github.com/gofiber/fiber/issues/2685
=> :bug: bug: fix method validation on route naming

mount_test.go, router.go
Fixes #2688
Enables the use of routes with names after apps have been mounted
=> 🐛 [Bug]: Naming of routes works wrong after mount #2688

docs/api/ctx.md
Added additional information as to why GetReqHeaders returns a map where the values are slices of strings (instead of a single string as one might expect)
In a (more or less) recent breaking change, the signature of [GetReqHeaders](https://docs.gofiber.io/api/ctx#getreqheaders) was changed to return a map where the values are not single strings anymore but instead slices of strings. As someone who encountered this breaking change after upgrading fiber, it was not clear why this was changed and - more importantly - what exactly would be contained in these slices. Therefore I added a short and simple explanation what one can expect to be returned by this method.
Documents the intent of #2594
=> 📚 Doc: Add additional information as to why GetReqHeaders returns a map where the values are slices of strings 

docs/api/ctx.md, helpers.go, helpers_fuzz_test.go, helpers_test.go
Attempts to approach the level of support offered by express, but behavior may differ in unusual corner cases.
Some key behaviors from Express that are implemented:
- If an offer does not have every parameter listed in the given Accept, it is rejected.
- Parameters do not affect specificity.
- In a given specificity, more parameters gives greater precedence
- Parameters are unordered
- Matching is case-insensitive
- Surrounding quotes behave strangely (buggy?) in Express, so we only explicitly handle what RFC-9110 allows, which is a quoted value (right side of the equal sign)
Behaviors that were intentionally **not** implemented:
- RFC 9110 defines quoted-pairs as octet pairs consisting of a backslash followed by another character. It states that recipients (i.e., servers) must parse …
=> ✨ feat: add support for parameters in content negotiation

middleware/pprof/pprof.go
Concatenate the custom and fixed prefixes beforehand, so the trimmed path can be switched on against constant strings.
Here's a simple benchmark:
```go
package pprof
import (
"crypto/rand"
"errors"
"strings"
"testing"
"unsafe"
)
var errBadPath = errors.New("bad path")
func doSlow(prefix, path string) error {
if len(path) < 12 || !strings.HasPrefix(path, prefix+"/debug/pprof") {
return errBadPath
}
// Switch to original path without stripped slashes
switch path {
case prefix + "/debug/pprof/":
return errBadPath
case prefix + "/debug/pprof/cmdline":
return errBadPath
case prefix + "/debug/pprof/profile":
return errBadPath
case prefix + "/debug/pprof/symbol":
return errBadPath
case prefix + "/debug/pprof/trace":
return errBadPath
case prefix + "/debug/pprof/allocs":
return errBadPath
case …
```
=> ⚡ middleware/pprof: improve performance

ctx.go, ctx_test.go
`strings.Split` was causing extra allocations where `strings.Cut` can suffice. Also switch from `strconv.Atoi` because it causes an allocation when parsing a non-integer, which is common for Ranges.
The remaining allocation (see benchmarks) comes from the returned slice.
```
│  master.txt  │             branch.txt              │
│    sec/op    │   sec/op     vs base                │
_Ctx_Range/bytes=-700-8       197.80n ± 0%   65.06n ± 0%  -67.11% (p=0.000 n=20)
_Ctx_Range/bytes=500--8       198.10n ± 0%   63.70n ± 0%  -67.84% (p=0.000 n=20)
_Ctx_Range/bytes=500-1000-8   162.30n ± 0%   64.76n ± 0%  -60.10% (p=0.000 n=20)
_Ctx_Range/bytes=500-700-8    161.75n ± 0%   64.48n ± 0%  -60.14% (p=0.000 n=20)
geomean                        179.1n        64.50n       -63.98%
│ master.txt  │ …
```
=> ⚡️ perf(ctx.Range): reduce allocations

middleware/limiter/limiter_test.go
The limiter middleware unit tests are failing due to a race between the storage garbage collector and the unit test itself. The sliding window limiter tracks requests using memory storage. In several of the unit tests, this storage expiry ends up being 4 seconds. The test waits for 4 seconds, then sends a request, expecting it to succeed. However, the unit test occasionally wakes up before the storage GC kicks in. As an effect of the very coarse timer (using seconds as units), the middleware correctly rejects the request, causing the test to fail.
Update the sleep to 4.5 seconds. This will not slow down the execution of the test suite, as these tests run in parallel with a separate 9 second long test.
I'm not 100% sure this solves the issue, and ideally we'd be able to run tests without …
=> test(limiter): fix intermittent failures

client.go, client_test.go, ctx.go, ctx_test.go, docs/api/ctx.md
I have added support for RFC7807 application/problem+json alongside the existing implementation for application/json. According to the RFC, there are no mandatory fields for problem+json that distinguish it from regular json content; so, I have only added the `ProblemJson` methods that send requests/responses and associated tests that require the mime type.
This is my first PR to this project so please let me know if I need to change anything. Thanks.
EDIT:
I have changed the `ProblemJSON` methods to `CustomJSON` methods that take in the Content-Type header as a parameter. This allows us to support all JSON mime type extensions, such as "application/problem+json".
Fixes #2701
Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. …
=> 🔥 Add support for application/problem+json

docs/api/middleware/csrf.md, middleware/csrf/config.go, middleware/csrf/csrf_test.go
- fix issues with `X-Csrf-Token` capitalization inconsistency.
- add package name to `ConfigDefault.HandlerContextKey` in example.
- reduce redundancy and repetition.
- improve grammar.
=> 📄 docs: improve csrf docs

utils/ips.go, utils/ips_test.go
Fix utils.IsIPv4 to include 255.
=> [Bug]: utils.IsIPv4 and net.ParseIP have inconsistent results #2735

ctx_test.go
Tests that call SetParserDecoder were causing a race condition with other tests that read from decoderPoolMap. Fix by making the offending tests not run in parallel.
This often manifested as CI failures.
To reproduce, run ` go test -race -v . -count=1 -run=Test_Ctx_QueryParser`. It will fail virtually every time.
=> 🚨 Test: fix race condition in parallel tests

helpers_test.go
Split getOffers benchmarks into individual cases for easier analysis.
This makes explicit two scenarios with allocations:
1. The Accept contains 3 or more media type parameters: the code uses a stack allocated slice of length 2, so this is expected. 
2. The Accept contains an unknown mime extension (in this case iso-8859-1).  I'm not sure if this is expected or not.
<details>
<summary>Benchmarks</summary>
```
Benchmark_Utils_GetOffer/simple-8               37348665                31.14 ns/op            0 B/op          0 allocs/op
Benchmark_Utils_GetOffer/simple-8               37296252                31.19 ns/op            0 B/op          0 allocs/op
Benchmark_Utils_GetOffer/simple-8               37496180                31.25 ns/op            0 B/op          0 allocs/op …
```
=> 🚨 Test: improve benchmarks for getOffer

middleware/session/session_test.go
A Session must not be accessed after Save() is called, but a unit test calls Session.ID() after Session.Save(), sometimes causing the test to fail when -race is enabled. The assertions that ID() was being used in were redundant with the previous two assertions (checking that the session name header is empty), so we can just remove the offending code.
=> 🚨 Test: race in session middleware tests

docs/api/middleware/logger.md, middleware/logger/config.go
middleware/logger/ doesn't log client IP address by default, this PR fixes it.
=> 🩹 middleware/logger/: log client IP address by default

middleware/cors/cors.go, middleware/cors/cors_test.go
Current CORS middleware always returns the header `Access-Control-Allow-Origin` with the value of `*` when `AllowOriginsFunc` is defined and the function does not return `true`. It was due to the middleware always setting the default origin value with `*` whenever the `AllowOrigins` config is empty. So whenever the request origin is not allowed by the function (returns false), the middleware will return `*` in the `Access-Control-Allow-Origin` header which makes the function useless.
This PR sets the default origin value of `*` only when both `AllowOrigins` and `AllowOriginsFunc` configs are not defined so that it will not return the `Access-Control-Allow-Origin` header with the value of `*` when the function does not return `true`. Instead, it will return an empty origin when the …
=> 🩹 Fix: CORS middleware should use the defined AllowedOriginsFunc config when AllowedOrigins is empty

middleware/adaptor/adaptor.go, middleware/adaptor/adaptor_test.go
It solves Adaptator + otelfiber issue bug where combination of Adaptator + Otelfiber contrib Middleware, c.BaseURL() returns wrong value (http:// instead of http://localhost:3000)
[issue link](https://github.com/gofiber/fiber/issues/2641)
Detailed explanation of solution of this issue is mentioned in [here](https://github.com/gofiber/fiber/issues/2641#issuecomment-1741785618)
Fixes #2641
=> 🐛 [Bug]: Adaptator + otelfiber issue #2641

middleware/redirect/redirect.go, middleware/redirect/redirect_test.go
fix redirect to add query params (if applicable) to the redirected url, add tests.
=> 🩹🚨 - fix for redirect with query params

docs/api/middleware/logger.md, middleware/logger/config.go, middleware/logger/tags.go
Color for the error tag of the logger and error tag by default in default format
=> ♻️ logger/middleware colorize logger error message #2593

ctx.go, docs/api/ctx.md, docs/api/middleware/basicauth.md, docs/api/middleware/csrf.md, docs/api/middleware/earlydata.md, docs/api/middleware/idempotency.md, docs/api/middleware/keyauth.md, docs/api/middleware/requestid.md, middleware/basicauth/basicauth.go, middleware/basicauth/basicauth_test.go, middleware/basicauth/config.go, middleware/csrf/config.go, middleware/csrf/csrf.go, middleware/csrf/csrf_test.go, middleware/earlydata/earlydata.go, middleware/idempotency/idempotency.go, middleware/keyauth/README.md, middleware/keyauth/config.go, middleware/keyauth/keyauth.go, middleware/logger/logger_test.go, middleware/requestid/config.go, middleware/requestid/requestid.go, middleware/requestid/requestid_test.go
Fixes context key collision issues in middleware and `ctx.go`. Follows best practice/convention from [context](https://pkg.go.dev/context) by using unexported key types to avoid collisions.
Related to #2684 which outlines the issue and rationale for change.
Please use emojis in commit messages for an easy way to identify the purpose or intention of a commit. Check out the emoji cheatsheet here: [CONTRIBUTING.md](https://github.com/gofiber/fiber/blob/master/.github/CONTRIBUTING.md#pull …
=> ♻️ v3: fix!: ContextKey collisions

ctx.go, ctx_interface.go, ctx_test.go, docs/api/ctx.md, error.go
While the existing Ctx.Format provides a concise convenience method for basic content negotiation on simple structures, res.format allows developers to set their own custom handlers for each content type.
Docs: moved the existing Ctx.Format docs to a section called AutoFormat and added docs for the new Ctx.Format.
I'm taking suggestions for better names than `Fmt` for the mediaType-handler struct...was just worried about making it overly long since people will need to type it over and over.
<details>
<summary>Benchmarks</summary>
Performs ever so slightly better than AutoFormat (formerly known as Format)
```
Benchmark_Ctx_Format/with_arg_allocation-8               2578868               464.5 ns/op            96 B/op          1 allocs/op
Benchmark_Ctx_Format/with_arg_allocation-8 …
```
=> 🔥 v3: update Ctx.Format to match Express's res.format

ctx.go, ctx_test.go, docs/api/client.md, docs/api/ctx.md, docs/api/middleware/adaptor.md, docs/api/middleware/recover.md, docs/api/middleware/session.md, docs/guide/templates.md, docs/guide/validation.md, docs/partials/routing/handler.md, log/default.go, log/default_test.go, log/fiberlog.go, log/log.go, middleware/adaptor/adaptor.go, middleware/adaptor/adaptor_test.go, middleware/csrf/csrf.go, middleware/logger/logger.go, middleware/recover/recover.go, router_test.go
Fix all occurrences of the `use-any` lint issue from `revive` and update the documentation accordingly.
List the new features or adjustments introduced in this pull request. Provide details on benchmarks, documentation updates, changelog entries, and if applicable, the migration guide.  There is no functional change as `any` is an alias of `interface{}`.
=> chore: change interface{} to any

.golangci.yml, addon/retry/exponential_backoff_test.go, ctx_test.go, middleware/filesystem/filesystem_test.go, middleware/session/session_test.go
In some cases, loop variables had to be reassigned to a local variable to avoid concurrent access. This will no longer be needed when fiber's minimum go version is bumped to 1.22 or later, where each loop iteration gets its own variable.
=> ci: re-enable tparallel linter

middleware/adaptor/adaptor_test.go, middleware/cache/cache_test.go, middleware/compress/compress_test.go, middleware/csrf/csrf_test.go, middleware/envvar/envvar_test.go, middleware/etag/etag_test.go, middleware/favicon/favicon_test.go, middleware/filesystem/filesystem_test.go, middleware/keyauth/keyauth_test.go, middleware/logger/logger_test.go, middleware/pprof/pprof_test.go, middleware/proxy/proxy_test.go, middleware/redirect/redirect_test.go, middleware/requestid/requestid_test.go, middleware/rewrite/rewrite_test.go, middleware/session/session_test.go, middleware/session/store_test.go
Update various assertions in the middleware packages to match testify best practices in preparation for an upcoming update to golangci-lint. For float comparisons, an epsilon of 0.1% was chosen somewhat arbitrarily.
https://github.com/Antonboom/testifylint
=> chore: Fix testifylint errors in middleware

app_test.go, bind_test.go, client_test.go, ctx_test.go, helpers_test.go, hooks_test.go, internal/storage/memory/memory_test.go, listen_test.go, mount_test.go, prefork_test.go, redirect_test.go, router_test.go
If this is too big, I can split this into multiple PRs.
In preparation for the upcoming linter update, fix testifylint errors.
Where possible, `require.ErrorContains` was avoided. Using `require.ErrorContains` [is planned to eventually be made a lint error](https://github.com/Antonboom/testifylint/blob/master/CONTRIBUTING.md#error-compare).
https://github.com/Antonboom/testifylint
=> chore: Fix remaining testifylint errors

middleware/session/session_test.go
This pull request addresses the issue of force type assertions in our test cases. The purpose of the change is to ensure that each type assertion is checked for validity and errors are handled accordingly, enhancing the robustness of our test suite. 
♻️  Improve error handling in test cases by adding checks for type assertions.
=> chore: fix force type assertions in session_test.go

ctx.go, ctx_test.go, docs/api/ctx.md
Introduced a new function, Locals, that utilizes Go's generics to handle and retrieve type-specific local values within a request context. This enhancement provides more accurate data type control within the context. Included are tests for generic and custom struct use-cases to ensure the function performs as expected.
This pull request presents an alternative version of the Locals function using Go's generics. This new implementation of Locals function provides enhanced type safety and allows for more specific data type handling within the request context.
Key features of this implementation:
- It utilizes the Go's generics feature allowing it to handle varying data types dynamically. It takes a generic parameter [V any].
- The function tries to convert the input context to a DefaultCtx …
=> Addition of Locals Function with Go Generics as an Alternative to c.Locals

.github/workflows/linter.yml, .golangci.yml, binder/mapping.go, error.go, middleware/adaptor/adaptor_test.go, redirect_test.go
Update golangci-lint to the latest version.
New linters and failing rules were commented out for visibility and tagged with TODO comments.
Related to #2816
=> ci: Update golangci-lint to v1.55.2

ctx.go, ctx_test.go
Added respects body immutability to ctx.Body() and ctx.BodyRaw() functions.
Related to #2757
=> 🩹[Fix]: Added respects body immutability to ctx.Body() and ctx.BodyRaw() functions.

middleware/logger/default_logger.go, middleware/logger/logger_test.go
We log to stderr if logging fails when a custom format is used, but not for the default format. This change addresses this inconsistency.
=> fix(logger): print to stderr if log fails for default format

ctx.go, ctx_interface.go, ctx_test.go
Adding GetReqHeaders and GetRespHeaders, that had not been copied from v2 to v3
Fixes #2799
Both features and tests (unit and benchamark) were copied and adapted from v2, without major changes.
=> 🔥 v3 (feature): Adding GetReqHeaders and GetRespHeaders

docs/guide/routing.md
=> Fix: Typo in routing.md

.golangci.yml, ctx.go, ctx_test.go, log/default.go, log/default_test.go, middleware/etag/etag.go, middleware/logger/default_logger.go, middleware/session/store.go, redirect.go, redirect_test.go
Globally ignore several methods that always return nil error. Disable revive and gosec rules for error checking in favor of errcheck.
=> 🎨 Style: Clean up errcheck config

docs/api/middleware/logger.md, middleware/logger/default_logger.go
While not all implementations of io.Write will be goroutine safe, the vast majority of users of the logger middleware are likely to use os.File, which does implement safe concurrent writes. If users require locking, they can implement this on an as-needed basis. The risk of having global locking is that a slow write can hold up the entire server.
Users migrating to v3 that are using a logger Output that requires locking will need to implement this themselves.
Note that no locking was actually being performed when the default log pattern was used.
Before you submit …
=> ♻️ Refactor: Remove mutex lock in logger middleware

.golangci.yml, docs/api/middleware/csrf.md, middleware/csrf/config.go, middleware/csrf/csrf.go, middleware/csrf/extractors.go, middleware/limiter/config.go, middleware/limiter/limiter.go
The `exported` rule of revive warns to not repeat the package name in method names. For example, prefer `csrf.FromCookie` over `csrf.CsrfFromCookie`.
It appears that these issues will not be caught by the linter until the `exported` rule is reenabled. This requires comments on all exported symbols, which is a much broader effort.
BREAKING CHANGE: This is a breaking change for v3.
Related to #2817
Users will be required to change to the new function and type names when upgrading to v3.  This change is beneficial to API longevity by being more in line with Go style standards.
Please delete options that are not …
=> 🎨 Style!: Update CSRF and Limiter to remove repetitive names

.golangci.yml, bind.go, ctx.go, log/log.go
inamedparam enforces that parameters in interface definitions be named. This is important for clarity so that users and implementers can easily understand the purpose of each parameter.
Related to #2817 
=> 🎨 Style: Add inamedparam linter

.github/workflows/test.yml
Add support for running the tests against the newly released arm64 M1 runner. This is based on Apple M1 platform with MacOS.
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/?trk=feed_main-feed-card_feed-article-content
=> Run tests against Apple M1 platform

docs/api/middleware/keyauth.md
Removes an an extra level of indentation in line 51 of `keyauth.md` [here](https://github.com/gofiber/fiber/blob/main/docs/api/middleware/keyauth.md?plain=1#L51)
Fixes #2866
- Decremented indentation level in line 51 of /docs/api/middleware/keyauth.md
=> :books: Doc: Fix code snippet indentation in /docs/api/middleware/keyauth.md

middleware/healthcheck/healthcheck.go, middleware/healthcheck/healthcheck_test.go
Fixing PR #2860 
I have changed the checking method of routes to use a regex which checks if the route ends with the specified liveness or readiness route and included tests for the strict routing mode, all passing with no issues.
As far as the benchmark, here are the results with the changes in this PR:
And without the changes in this PR:
=> fix: healthcheck middleware not working with route group

.github/workflows/test.yml
Reporting flaky tests is important so they can be fixed. Also this allows to discover data races which else might go completely unnoticed.
=> feat(ci): do not retry flaky tests

middleware/csrf/csrf.go, middleware/csrf/csrf_test.go
This PR addresses a bug in the CSRF middleware test suite and enhances the referer header validation logic for improved efficiency. Here's a summary of the changes:
- **Bug Fix**:
- Fixed a bug in the benchmark tests of `csrf_test.go` where headers were not properly set for POST requests, causing incorrect test results. The fix ensures that the referer header is correctly set with different schemes and hosts, covering various scenarios.
- Fixed a bug in the benchmark tests of `csrf_test.go` where there were two contexts and only one had anything set, causing all requests to be made with an empty context.
- **Code Logic Enhancement**:
- Refactored the logic to convert the referer header to lowercase before comparison, ensuring consistent handling of the header case.
- Simplified the …
=> test(middleware/csrf): Fix Benchmark Tests

docs/api/middleware/earlydata.md
Fix merge conflict in `EarlyData` middleware documentation
Fixes #2956 
=> 🧹 Maintenance: Fix merge conflict in documentation

middleware/cache/cache.go
This PR optimize cache middleware's performace, with the following changes:
* Use Go's `slices.Contains` to replace original for loop (This should not increase performance but only reduce code)
* Use `strings.Builder` for concat strings for `key`
* `requestMethod := c.Method()` to avoid call `Method()` multiple times
before
```
Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -bench ^Benchmark_Cache$ github.com/gofiber/fiber/v3/middleware/cache
goos: linux
goarch: amd64
pkg: github.com/gofiber/fiber/v3/middleware/cache
cpu: AMD Ryzen 7 PRO 5850U with Radeon Graphics
=== RUN   Benchmark_Cache
Benchmark_Cache
Benchmark_Cache-16       4430882               271.5 ns/op            16 B/op          2 allocs/op
PASS
ok      github.com/gofiber/fiber/v3/middleware/cache    1.485s
``` …
=> 🩹 Fix: Optimize Cache middleware handler

ctx.go
Improve the `ctx.Locals` inlone godocs to clarify the behavior of stored variables and their lifecycle to avoid unintentional resource closures. Following #3030 this adds inline docs to `ctx.go` file.
- **Documentation Update:** 
- Added a clarification that stored variables are removed after the request is handled.
- Specified that if any stored data implements the `io.Closer` interface, its `Close` method will be called before it's removed.
- **File Modified:** `ctx.go`
- **Benchmark Impact:** None
- **Documentation Updates:** Improved clarity in the `Locals` method documentation.
- **Changelog Entries:** 
- Clarified behavior of `ctx.Locals` regarding variable removal and `io.Closer` interface handling.
- **Migration Guide:** Not applicable
These changes aim to prevent issues with …
=> docs: Improve ctx.Locals method documentation

ctx.go, ctx_interface_gen.go, docs/api/ctx.md
Improve the `ctx.Locals` documentation to clarify the behavior of stored variables and their lifecycle to avoid unintentional resource closures, and provide best practices with keys and values.
- **Documentation Update:** 
- Added a clarification that stored variables are removed after the request is handled.
- Specified that if any stored data implements the `io.Closer` interface, its `Close` method will be called before it's removed.
- **Example Code Enhancement:**
- Demonstrated the use of a non-exported type as a key to avoid collisions.
- Included type assertions when retrieving stored data to ensure it is of the expected type.
- **Files Modified:** `docs/api/ctx.md` and `ctx.go`
- **Benchmark Impact:** None
- **Documentation Updates:** Improved clarity and provided best practices in …
=> docs: Improve ctx.Locals method description, godoc and example

.github/README.md, docs/intro.md
Update README to mention the `Zero Allocation` aspect of Fiber. Add LINK to documentation for further explanation. Update the wording in the "intro.md" section of the Docs.
=> Add zero-allocation section to README

middleware/monitor/monitor.go
The monitPIDCPU should be consistent with the monitOSCPU and should be changed instantaneously rather than using the cumulative value since program startup
The value should be calculated based on the actual number of CPU cores, rather than a fixed value of 10.
Fixes #2978 
=> fix: monitor middleware reporting of CPU usage

middleware/session/session_test.go
Remove extra release and aquire ctx calls in session_test.go so Test_Session_Types passes in -race
=> test(middleware/session): Remove extra release and acquire ctx calls in session_test.go

redirect.go, redirect_test.go, router.go
🐞 [Bug]: v3 Flash Message with redirect is not working #3038
fixes #3038
=> fixes #3038 "v3 Flash Message with redirect is not working"

middleware/session/session.go, middleware/session/session_test.go, middleware/session/store.go
This pull request adds a mutex to the session middleware to ensure thread safety when accessing session data. The mutex is used to protect non-data fields and prevent race conditions. This improves the reliability and stability of the session middleware.
=> fix(middleware/session): mutex for thread safety

middleware/session/session.go, middleware/session/store.go
fixes https://github.com/gofiber/fiber/pull/3049#issuecomment-2198323260
=> fix(middleware/session): fix data-race with sync.Pool

.github/workflows/test.yml, Makefile
- Added support for running tests 15 times with go1.21 and go1.22 using `ubuntu-latest`.
- Renamed `build` to `unit` in the test.yml workflow
- Remove installation of gotestsum, since it can be called using `go run`
- Always use `latest` gotestsum.
This should help detect future race-conditions that only happen when tests are run more than once but using GitHub Actions.
=> feat: Add support for longtests during CI

ctx.go, ctx_test.go, docs/api/ctx.md, docs/whats_new.md
Add support for partitioned cookies.
Fixes https://github.com/gofiber/fiber/issues/3002
=> :sparkles: v3 (feature): add CHIPS support to Cookie

docs/api/log.md, log/default_test.go, log/fiberlog_test.go, middleware/cors/cors_test.go
- Added missing Benchmarks for fiberlog
- Added missing Parallel benchmarks for fiberlog
- Renamed some of the `cors` benchmarks to have consistent names
- Rewrote the docs for `log.md`. 
Related to #3048 
=> v3: Updates to fiberlog benchmarks and documentation

middleware/logger/logger_test.go
- Add more benchmarks for the logger middleware
- Add parallel benchmarks for the logger middleware
Note: The logger middleware adds a significant amount of overhead compared to not using it:
```
Benchmark/NoMiddleware-8                       25532379           44.41 ns/op           0 B/op           0 allocs/op
Benchmark/DefaultFormat-8                       4304126           268.7 ns/op          16 B/op           2 allocs/op
```
Related to #3048 
=> v3: Update benchmarks for Logger Middleware

.github/workflows/test.yml, docs/middleware/encryptcookie.md, docs/whats_new.md, middleware/encryptcookie/config.go, middleware/encryptcookie/encryptcookie_test.go, middleware/encryptcookie/utils.go
- Enforce key length for default encryptor/decryptor in `EncryptCookie` middleware.
- `AES-GCM` only works with `16`, `24`, `32` bytes keys.
- This will allow the user to use AES-128 if speed is critical.
- Add `length` param to `encryptcookie.GenerateKey`.
- Add unit-test for `encryptcookie.GenerateKey`.
- Add benchmarks for `EncryptCookie` middleware.
- Add parallel benchmarks for `EncryptCookie` middleware.
- Increase Middleware Test Coverage by `+12.37%`
Related to #3048 
=> v3: Enforce key length for EncryptCookie middleware default functions

ctx.go, ctx_test.go
Fixes https://github.com/gofiber/fiber/issues/2832
=> :bug: bug: fasthttp errors cause panic when Params is used

ctx.go, router_test.go
- Removed unnecessary variable declaration: The var err error declaration is not needed; you can return the error directly where it occurs.
- Simplified control flow: The nested if-else logic has been streamlined to improve readability and reduce branching.
- Min: 37.92 ns/op
- Max: 40.04 ns/op
- Mean: 38.75 ns/op
- Min: 37.64 ns/op
- Max: 39.19 ns/op
- Mean: 38.68 ns/op
- Min Percent Difference: 0.74%
- Max Percent Difference: 2.12%
- Mean Percent Difference: 0.18%
- Min Iterations: 29071340
- Max Iterations: 31355298
- Mean Iterations: 30071851
- Min Iterations: 28509068
- Max Iterations: 31645021
- Mean Iterations: 30259517
- Min Percent Difference: 1.93%
- Max Percent Difference: 0.93%
- Mean Percent Difference: 0.62%
- Run 2 is slightly faster than Run 1 based on the min and mean …
=> v3: Improve and simplify logic of ctx.Next()

middleware/logger/logger_test.go, middleware/logger/tags.go
- Use `Content-Length` header when calculating the `bytesSent` and `bytesReceived` tags in the Logger Middleware.
- The current implementation will load big files to memory to calculate the len causing Fiber to use a high amount of RAM.
Fixes #3060
=> 🐛 bug: Use Content-Length for bytesReceived and bytesSent tags in Logger Middleware in v2

docs/whats_new.md, middleware/adaptor/adaptor.go
Improve performance of the Adaptor middleware by using `sync.Pool` to re-use `fasthttp.RequestCtx` objects.
Overall Percent Change
- Execution Time: Reduced by ~47.57%
- Memory Usage: Reduced by ~89.97%
- Allocations: Reduced by ~68.75%
- 100KB: 1056 ns/op, 2644 B/op, 16 allocs/op
- 500KB: 1061 ns/op, 2644 B/op, 16 allocs/op
- 1MB: 1080 ns/op, 2646 B/op, 16 allocs/op
- 5MB: 1093 ns/op, 2654 B/op, 16 allocs/op
- 10MB: 1044 ns/op, 2665 B/op, 16 allocs/op
- 25MB: 1069 ns/op, 2706 B/op, 16 allocs/op
- 50MB: 1137 ns/op, 2734 B/op, 16 allocs/op
- 100KB: 588.6 ns/op, 254 B/op, 5 allocs/op
- 500KB: 562.9 ns/op, 248 B/op, 5 allocs/op
- 1MB: 629.7 ns/op, 267 B/op, 5 allocs/op
- 5MB: 540.3 ns/op, 254 B/op, 5 allocs/op
- 10MB: 533.1 ns/op, 258 B/op, 5 allocs/op
- 25MB: 540.7 ns/op, 289 B/op, 5 …
=> v3: Improve performance of Adaptor Middleware

ctx_test.go
This pull request fixes a race condition in the `Test_Ctx_SendFile_Compress_CheckCompressed` test in the `ctx_test` file.
=> test(ctx_test): Fix race condition

.github/workflows/benchmark.yml
- Updated Benchmarks workflow based on practices seen in other projects.
- The cache is now store/restored using the latest `SHA` and the cpu-model.
- During a PR the Benchmarks are compared with the latest results from `main`
- During a merge, the Benchmark results are updated and saved to cache
- GitHub Pages will also be updated, although it's disabled right now until v3 is official.
=> v3: Refactor Benchmark Results Workflow

.github/workflows/benchmark.yml
We are using an older version of the `benchmark-action` in the v2 branch, this is causing the parsing when comparing to v3 to be broken.
This can be seen here https://github.com/gofiber/fiber/actions/runs/10040932098 where the values in the right column are not parsed correctly. This was a bug that was fixed a few versions ago after we reported it.
=> v2: Update benchmark-action to v1.20.3

middleware/cache/cache.go, middleware/cache/cache_test.go, middleware/cache/heap.go, middleware/cache/manager.go, middleware/cache/manager_test.go
Fixes #3072 
The bug happens due to some scenarios together: 
- The cache middleware always create a pointer `item` even though the cache entry was not found. 
- The application can define a `CacheInvalidator` that commands to expire the cache **even though** it doesn't not have any entry
In case the application defines a `MaxBytes` size for the cache, it will try to remove it from the heap, resulting in a runtime error due to the heap not having even initialized.
To fix the issue, I made the following changes:
- The cache will return `nil` in case it does not found the entry. 
- The expiration flow will not be triggered if no cache entry was found, this will avoid unexpected behaviors.
List the new features or adjustments introduced in this pull request. Provide details on benchmarks, …
=> 🐛 [Bug]: cache middleware: runtime error: index out of range [0] with length 0

.github/workflows/benchmark.yml, Makefile, helpers.go, helpers_test.go
- Improve performance of `getOffer` helper function.
- Improve performance of `paramsMatch` helper function.
- Only add benchmark comments if branch is **not** from a fork.
- Note: Most of these optimizations were found using `GPT4o`.
=> v3: Improve performance of helper functions

client/response.go, ctx.go, go.mod, go.sum, helpers.go, middleware/cache/manager_msgp_test.go, middleware/cors/cors.go, middleware/csrf/csrf.go, middleware/csrf/csrf_test.go, middleware/csrf/manager_msgp_test.go, middleware/limiter/manager_msgp_test.go, middleware/pprof/pprof.go, mount.go, path.go, redirect.go, router.go
=> Use utils Trim functions instead of the strings/bytes functions

ctx.go, ctx_test.go
- Improved performance of `Body()` across all cases by using the `Content-Encoding` from the request instead of iterating through all headers.
- I found this improvement by accident while adding tests for `BodyRaw()`.
- Added missing unit-tests for `BodyRaw()`.
- Added missing benchmarks for `BodyRaw()`.
- Iterations: Approximately 124-126 million iterations
- Time per Operation: Around 9.498 to 9.529 nanoseconds per operation
- Iterations: Approximately 281-289 million iterations
- Time per Operation: Around 4.149 to 4.202 nanoseconds per operation
=> v3: Improve Performance of c.Body() by 125%

middleware/rewrite/rewrite_test.go
- Added Benchmarks for Rewrite Middleware
- Added Parallel Benchmarks for Rewrite Middleware
- Improvements to Middleware will be done in a separate PR.
Related to #3048
=> v3: Add Benchmarks for Rewrite Middleware

ctx.go
This PR proposed to reduce redundant call when get request body
=> v3: Consolidate Logic of Handling the Request Body

binder/form.go
Add missing error check in Form binder.
=> 🩹 Fix: error check in Form binder

docs/guide/templates.md
This issue proposes to provide more snippets of ways to use templates in [Go Fiber’s templates guide](https://docs.gofiber.io/guide/templates).
Fixes #3108 
=> 📚 Doc: Add detailed documentation for the templates guide

client/client.go, client/client_test.go, go.mod, go.sum
Fixes https://github.com/gofiber/fiber/issues/3085
=> client: fix SetProxyURL functionality

ctx.go, ctx_test.go
Add logic to keep count of open brackets. If there's a mismatch between the number of open and close brackets, then return error.
Fixes #3120 
=> 🩹 Fix: handle un-matched open brackets in the query params

.github/CODEOWNERS
This will allow github to auto assign the `gofiber/maintainers` team as reviewers of each new `v2` Pull Request. Currently this is a manual process.
=> v2: Add CODEOWNERS file

binder/mapping.go, binder/mapping_test.go
Add logic to keep count of open brackets. If there's a mismatch between the number of open and close brackets, then return error.
Fixes #3120 
=> 🩹 Fix (v3): handle un-matched open brackets in the query params

docs/middleware/recover.md
Update the documentation for the recover middleware to demonstrate using an alias instead of directly importing. This is important since `recover` is a reserved word in Go (recover function). If you don't explicitly write the import first and instead rely on code actions, lsp, autoformatting, autoimporting etc, you will get an error using `recover` and it won't import. Therefore I suggest using an alias for the import to avoid conflicting with editors/LSP's and so on. I'm using `recoverer` since that's the standard naming in other middleware's such as Chi's.
Please delete options that are not …
=> 📚 Doc: Update recover docs to not use reserved keyword

.github/workflows/linter.yml, Makefile, middleware/cache/cache.go, middleware/etag/etag.go
- Bump golangci-lint to v1.61.0
=> Bump golangci-lint to v1.61.0

middleware/adaptor/adaptor.go, middleware/adaptor/adaptor_test.go
- Use `Noop Logger` when creating RequestCtx for Adaptor Middleware.
- Added benchmark for `No Content`.
Fixes #3130
=> v3: Fix issue with default logger when creating RequestCtx

ctx.go, ctx_interface_gen.go, ctx_test.go
- Add Benchmarks for `ctx.IsFromLocal()`
- Optimize performance of `ctx.IsFromLocal()` by using `net.IP` functions to detect if IP is from loopback address.
- Reduce memory allocations by using `net.IP` directly instead of strings.
| **Benchmark**                  | **Before ns/op** | **After ns/op** | **Speedup**     | **Before Allocations** | **After Allocations** | **Improvement**        |
|--------------------------------|-----------------|-----------------|-----------------|-----------------------|-----------------------|-------------------------|
| **Non_Localhost**              | 26.45           | 7.51            | ~3.52× faster    | 1 allocs/op            | 0 allocs/op            | Allocations Eliminated  |
| **Non_Localhost_Parallel**     | 6.824           | 1.30            | …
=> v3: Optimize IsFromLocal() performance

docs/middleware/logger.md
Documentation improvements were made in this branch.
Deleted zero width whitespace (u200b) character in logger documentation.
=> 📚 Doc: removed zero width white space from logger docs

middleware/cache/cache.go
There was a comment `Cache Entry not found` before the process when the cache was hit.
I think this is a typo, please check them.
thank you.
=> chore(middleware/cache): fix typo

ctx.go, ctx_test.go
If 'Last-Modified' and 'If-Modified-Since' are equal, then `DefaultCtx.Fresh` returns false.
However, if no updates have been made, the cache should not to be stale.
Thank you.
```sh
go test -v -run=^$ -bench=Benchmark_Ctx_Fresh_LastModified -benchmem -count=4
```
```
goos: linux
goarch: amd64
cpu: AMD EPYC 7763 64-Core Processor                
Benchmark_Ctx_Fresh_LastModified
Benchmark_Ctx_Fresh_LastModified-2      10880254               123.4 ns/op             0 B/op          0 allocs/op
Benchmark_Ctx_Fresh_LastModified-2      10743270               109.9 ns/op             0 B/op          0 allocs/op
Benchmark_Ctx_Fresh_LastModified-2      10766181               114.0 ns/op             0 B/op          0 allocs/op
Benchmark_Ctx_Fresh_LastModified-2 …
```
=> 🩹 Fix: behavior of `DefaultCtx.Fresh` when 'Last-Modified' and 'If-Modified-Since' are equal

middleware/adaptor/adaptor.go, middleware/adaptor/adaptor_test.go
In `adapter.go`, add a step to clear existing cookies before introducing new ones in the `HTTPMiddleware` section, so that cookies are not duplicated after passing through the middleware.
Fixes [#3089](https://github.com/gofiber/fiber/issues/3089)
=> 🩹Fix: Adaptor middleware duplicates cookies

bind.go
=> docs: Fix typo on comment

docs/api/hooks.md, hooks.go
This PR fixes a typo in the hooks documentation.
=> 📚 Doc: typo in hooks documentation

.github/README.md
This reverts commit 9dd3d94ff24735c4e018e0b94db5bba22d8f45f3.
=> Revert "Update README.md (#3165)"

.github/workflows/linter.yml, Makefile, client/hooks_test.go, client/response_test.go, ctx_test.go, log/default.go, middleware/adaptor/adaptor.go, middleware/cache/heap.go, middleware/cache/manager.go, middleware/limiter/manager.go, middleware/logger/default_logger.go, middleware/logger/logger_test.go, middleware/logger/tags.go, router.go
- Bump golangci-lint to v1.62.0
=> Bump golangci-lint to v1.62.0

ctx.go
- Add missing Close() when opening file
=> 🩹 fix: Close File After SaveFileToStorage

docs/intro.md
- Update the `intro` documentation using `o1-mini` OpenAI model.
- Plan is to go through as many .md files and fix them using `AI`. Will create separate PR's per section.
Related to #2712 
=> 📚 Doc: Update intro documentation

bind.go, client/client_test.go, ctx.go, ctx_interface_gen.go, ctx_test.go, docs/api/ctx.md, docs/middleware/timeout.md, docs/whats_new.md, middleware/adaptor/adaptor.go, middleware/adaptor/adaptor_test.go, middleware/cache/cache_test.go, middleware/compress/compress.go, middleware/etag/etag.go, middleware/expvar/expvar.go, middleware/idempotency/idempotency.go, middleware/logger/logger_test.go, middleware/pprof/pprof.go, middleware/redirect/redirect.go, middleware/static/static.go, middleware/timeout/timeout.go, middleware/timeout/timeout_test.go, redirect.go, redirect_test.go
- The standard practice in golang is to have a function named `Context()` that returns the `context.Context`. In Fiber's case this function was named `UserContext()` which is confusing to users. This PR renames `UserContext()` to `Context()`.
- At the same time we were using `Context()` for returning the FastHTTP `RequestCtx` object. This function has been renamed `RequestCtx()`.
Fixes #3186
=> 🐛 fix: Improve naming convention for Context returning functions

.github/README.md, docs/api/app.md, docs/api/bind.md, docs/api/hooks.md, docs/api/log.md, docs/api/redirect.md
- Auto update the API documentation using `o1-mini` from OpenAI
- Auto update the `README` USING `o1-mini` from OpenAI
Related to #2712
=> 📚 Doc: Updates to API documentation and README

docs/api/ctx.md
- Auto update the Context documentation using `o1-mini` from OpenAI
Related to #2712
=> 📚 Doc: Updates to Context documentation

client/client.go, client/client_test.go, docs/client/rest.md
Add support for passing a custom fasthttp client to the fiber http client, to allow more granular fine tuning by the users.
Fixes #3107 
- Add `NewWithClient` method to client.
- Add method to [client docs](https://github.com/gofiber/fiber/blob/main/docs/client/rest.md#usage).
- The `New` method calls `NewWithClient` internally.
- Add unit tests for valid fasthttp client and nil client.
=> 🔥 feat: Add support for creating Fiber client from existing FastHTTP client

.github/README.md, .github/workflows/benchmark.yml, .github/workflows/linter.yml, .github/workflows/test.yml, docs/intro.md, docs/whats_new.md, go.mod
Mark Go 1.23 as min go version in order to support new iterators.
=> chore: mark go1.23 as minimum go version

.github/workflows/test.yml, ctx.go
For request bodies without encoding, the Immutable configuration was not being respected, leading to potential data races.
`go run -race` no longer produces warnings for the example in the original issue.
Fixes #3236 
=> 🐛 fix: Respect Immutable config for Body()

docs/api/fiber.md, docs/whats_new.md, listen.go, listen_test.go
This pull request introduces a new configuration option to set the minimum TLS version in the `listen.go` file. The most important changes include adding the `TLSMinVersion` field to the `ListenConfig` struct and updating the default configuration and relevant methods to use this new field.
* [`listen.go`](diffhunk://#diff-8a6813f17ba53a53b4ca15776268eb3d32519867058e03351b87b7aea23b4978R53-R57): Added `TLSMinVersion` field to the `ListenConfig` struct to allow setting the minimum TLS version.
* [`listen.go`](diffhunk://#diff-8a6813f17ba53a53b4ca15776268eb3d32519867058e03351b87b7aea23b4978R136): Set the default value of `TLSMinVersion` to `tls.VersionTLS12` in the `listenConfigDefault` function.
* [`listen.go`](diffhunk://#diff-8a6813f17ba53a53b4ca15776268eb3d32519867058e03351b87b7aea23b497 …
=> 🔥 feat: Add support for configuring TLS Min Version

client/client.go, client/hooks_test.go, client/request.go, client/request_test.go, docs/client/request.md
Fixes #3251
**Preserved `AddFormData` and `SetFormData`:**
I kept `AddFormData` and `SetFormData` unchanged because "FormData" is an HTTP-specific term. Moreover, the term aligns with the existing `formData` field, making it consistent.
**Renamed `*FormDatas` to `*FormDataWithMap`:**
Since there is already a method called `*FormDatasWithStruct`, I renamed `*FormDatas` to `*FormDataWithMap` for better clarity and intuitiveness during usage. The `WithMap` and `WithStruct` suffixes provide a clear indication that these methods can handle multiple key-value pairs.
**Renamed  `AddData` and `SetData` (in `FormData`) to `Add` and `Set`:**
The methods `AddData` and `SetData` in `FormData` were renamed to `Add` and `Set` to align with the naming convention in `fasthttp.Args`, which also uses `Add` …
=> ♻️ Refactor: Rename the Method Names of FormData and FormDatas (#3251)

router_test.go
- Add `b.RunParallel()` version of the `Next()` benchmark.
```bash
ubuntu@ubuntu:~/Desktop/git/fiber$ go test -benchmem -run=^$ -bench ^Benchmark_Router_Next_Default_Parallel$ github.com/gofiber/fiber/v2 -count=10
goos: linux
goarch: amd64
pkg: github.com/gofiber/fiber/v2
cpu: AMD Ryzen 7 7800X3D 8-Core Processor           
Benchmark_Router_Next_Default_Parallel-4   	143252916	         9.433 ns/op	       0 B/op	       0 allocs/op
Benchmark_Router_Next_Default_Parallel-4   	145309903	         8.137 ns/op	       0 B/op	       0 allocs/op
Benchmark_Router_Next_Default_Parallel-4   	146474128	         8.073 ns/op	       0 B/op	       0 allocs/op
Benchmark_Router_Next_Default_Parallel-4   	146365718	         8.013 ns/op	       0 B/op	       0 allocs/op
Benchmark_Router_Next_Default_Parallel-4 …
```
=> 🧹 chore: Add parallel benchmark for Next()

ctx.go, ctx_interface_gen.go, ctx_test.go, docs/api/ctx.md, middleware/cache/manager_msgp.go
This pull request introduces the Drop method to the DefaultCtx structure. The Drop method allows developers to silently terminate client connections without sending any HTTP headers or response body. This functionality is particularly useful for scenarios such as:
- Mitigating DDoS attacks.
- Blocking access to sensitive endpoints.
- Enhancing resource management by closing unwanted connections.
This addition aligns with Fiber’s goal of providing high-performance web server functionalities with fine-grained control.
Fixes #3252 
Please use emojis in commit messages for an easy way to identify the purpose or intention of a commit. Check out the emoji cheatsheet here: …
=> feat: Add Drop method to DefaultCtx for silent connection termination

docs/middleware/session.md
In the documentation(next version), the menu item text of the middleware session is displayed abnormally, I view to fix this issue.
I checked the docs(v2), and realized that the current title was actually the first sentence of the text at the time. Then I checked the docs(next) and realized that there was already a similar description in the text, so I just cut it down to what a title should look like.
=> 📚 Doc: Optimize the menu item text

ctx.go, ctx_test.go, go.mod, go.sum, helpers.go
=> Support Square Bracket Notation in Multipart Form data

ctx.go, ctx_interface_gen.go, docs/api/ctx.md
bind parameter of Render method has been converted from `any` to `map[string]any` by me a long time ago to keep the parameter type-safe. However this change breaks some usecases such as using bind as struct etc. Therefore, let's revert the change.
Example usecase that `html/template` supports struct types as binding data: https://pkg.go.dev/html/template#example-package, 
Fixes https://github.com/gofiber/fiber/issues/3219
=> :bug: bug: make Render bind parameter type any again

app.go, app_test.go, ctx_test.go, helpers.go, helpers_test.go
This PR fixes the bug where `app.Test()` auto-fails by returning `testConn is closed` if the underlying connection is closed during a `fiber.Handler`. Namely, `c.Drop()` falls under this category, as it calls `c.RequestCtx().Conn().Close()`.
To fix this, we do not return an error if the error matches with `errTestConnClosed`. If there was truly an error, it should return as `ErrTestGotEmptyResponse` due to an empty response (which should be expected when `c.Drop()` is called).
Fixes #3278
- This PR is a step to ensure that `app.Test()` is working as expected for new corner cases introduced in v3.
Before you …
=> 🩹 Fix: Fix app.Test() auto-failing when a connection is closed early

docs/whats_new.md
Added missing Drop() documentation to whats_new.md
Fixes #3282 
- [ :heavy_check_mark:  ] Documentation Update: Added missing Drop() documentation to whats_new.md. Link to the changed file: https://github.com/aliziyacevik/fiber/blob/master/docs/whats_new.md
- [ :heavy_check_mark: ] Documentation update (changes to documentation)
- [:heavy_check_mark:  ] Updated the documentation in the `/docs/` directory for [Fiber's documentation](https://docs.gofiber.io/).
=> 📒 doc: Add ctx.Drop() to whats_new.md

docs/whats_new.md
This PR adds a `Drop` section with an example in [`whats_new.md`](https://github.com/gofiber/fiber/blob/main/docs/whats_new.md). It also reorders `c.Drop()` and `c.End()` in `whats_new.md` to match the [source code order](https://github.com/gofiber/fiber/blob/main/ctx.go#L1985).
Fixes #3282 
=> 📚 Docs: Add `c.Drop()` example to `whats_new.md`

docs/middleware/cache.md, docs/whats_new.md, middleware/cache/cache.go, middleware/cache/cache_test.go
This pull request updates the cache middleware to avoid caching uncacheable status codes.
This change improves cache accuracy and saves cache storage size.
> Responses with status codes that are defined as cacheable by default
(e.g., 200, 203, 204, 206, 300, 301, 404, 405, 410, 414, and 501 in
this specification)
https://datatracker.ietf.org/doc/html/rfc7231#section-6.1
See also: 
- https://developer.mozilla.org/en-US/docs/Glossary/Cacheable
- https://cpdos.org
However, for 418: TeaPot, although not actually cacheable, it continues to be cacheable since it is used in benchmark tests.
Thank you.
Fixes -
```log
goos: linux
goarch: amd64
pkg: github.com/gofiber/fiber/v3/middleware/cache
cpu: AMD EPYC 7763 64-Core Processor                
Benchmark_Cache
Benchmark_Cache-2 …
```
=> 🐛 fix: Align cache middleware with RFC7231

app.go, app_test.go
As mentioned in the #3304 , I modified the channel of the Test function to use a buffered channel, and added a unit test to verify goroutine leakage with and without a timeout.
Fixes #3304 
=> 🩹 Fix: goroutine leakage

ctx_test.go, helpers.go
`genericParseType` parsing a large `uint` leads to overflow. When parsing `uint` string, the `bitSize` of `strconv.ParseUint` should be `0` instead of `32`.
=> 🩹 Fix: genericParseType parsing large uint leads to overflow

docs/extra/faq.md, docs/middleware/adaptor.md
=> docs: Update adapter middleware documentation

middleware/cache/cache.go
When the value of a map is not used, using `struct{}` instead of `any`  can significantly reduce memory usage. The following experiment demonstrates the improvement:
+ Go 1.24: Memory usage reduced from **616** bytes to **456** bytes. (**-26%**)
+ Go 1.23: Memory usage reduced from **576** bytes to **288** bytes. (**-50%**)
This change helps optimize memory consumption, making it more efficient when the value is not needed.
Go 1.24 introduced optimizations in the map implementation, further affecting memory consumption.
```go
func main() {
before := getMemUsage()
ignoreHeaders := map[string]any{
"Connection":          nil,
"Keep-Alive":          nil,
"Proxy-Authenticate":  nil,
"Proxy-Authorization": nil,
"TE":                  nil,
"Trailers":            nil,
"Transfer-Encoding":   nil, …
```
=> ♻️ Refactor: Reduce the Memory Usage of ignoreHeaders

helpers.go, helpers_test.go
Improve the implementation of `getSplicedStrList`. 
1. The original `getSplicedStrList` calls `utils.TrimLeft`. In the new one, I integrated the trim-left functionality by tracking the leading space, without calling other functions.
2. The original `getSplicedStrList` copies the `dst` slice when it is not large enough. I believe this operation can be handled more efficiently using golang built-in `append` function.
```
goos: linux
goarch: amd64
cpu: AMD EPYC 7763 64-Core Processor                
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
_Utils_GetSplicedStrList-4   66.12n ± 1%   51.05n ± 1%  -22.79% (p=0.000 n=50)
│  old.txt   │            new.txt             │
│    B/op    │    B/op     vs …
```
=> ♻️ Refactor: Improve Performance of getSplicedStrList

.github/README.md, .github/codecov.yml, .github/workflows/test.yml
- Add go1.24 to CI matrix.
- Cleanup README.md
=> 🧹 chore: Add go1.24 to CI matrix

path.go
The string variable `patternPretty` in `RoutePatternMatch` can be changed into `[]byte`. The byte slice provides greater flexibility for modifying its bytes. Thus, in the benchmark test, we can observe a reduction in memory usage and allocation.
+ Add the new function `RemoveEscapeCharBytes`
+ Change the returned value type of `analyseConstantPart` and `analyseParameterPart`. Because we only use the length of the returned string, we can just return the number.
```
goos: linux
goarch: amd64
cpu: AMD EPYC 7763 64-Core Processor
│ route_pattern_match_old.txt │    route_pattern_match_new3.txt    │
│           sec/op            │   sec/op     vs base               │
_RoutePatternMatch//api/v1/const_|_match_|_/api/v1/const-4 …
```
=> ♻️ Refactor: reduce the memory usage of RoutePatternMatch

binder/README.md, binder/form_test.go, binder/mapping.go, error.go
Fix error binder in form_test.
=> 🐛 fix: Update binder in form_test

.github/workflows/linter.yml, .golangci.yml, app.go, app_test.go, bind_test.go, client/helper_test.go, ctx_test.go, helpers_test.go, internal/storage/memory/memory_test.go, listen.go, log/default.go, middleware/adaptor/adaptor_test.go, middleware/logger/default_logger.go, middleware/logger/logger_test.go, path.go, redirect_test.go, router.go, router_test.go
This PR targets another PR (branch: `fix-lint`) #3354.
This is a workaround to unlock your situation (the workaround is to use `goinstall` mode).
I also improved a bit your configuration and fixed some malformed `nolint` directives.
This is just a workaround. I'm still working on a proper fix, but as you can imagine, it is not quick or simple to debug on the GitHub Action runner.
=> 🧹 chore: Fix and update golangci-lint workflow

middleware/csrf/csrf_test.go
This PR uncomments `Test_CSRF_UnsafeHeaderValue` and marks it with `t.SkipNow()`.
Using [t.SkipNow](https://pkg.go.dev/testing#T.SkipNow) in tests allows the test to be skipped while still being compiled and visible in the test output, which helps in tracking and revisiting skipped tests. Commenting out tests removes them from the compilation and test output, making it easier to forget about them.
Please use emojis in commit messages for an easy way to identify the purpose or …
=> 🧹 chore: Mark unused tests with t.SkipNow

app.go, ctx.go, ctx_interface.go, ctx_interface_gen.go, helpers.go, router.go
In the default context, the 3-byte-long `treePath` can be encoded as an int. Therefore, reduce the size of `DefaultCtx` and `treeStack`
```
goos: linux
goarch: amd64
cpu: AMD EPYC 9J14 96-Core Processor                
│   old.txt     │               new.txt                │
│    sec/op     │    sec/op     vs base                │
_Router_NotFound-16                 546.5n ±  1%   467.3n ±  0%  -14.50% (p=0.000 n=20)
_Router_Handler-16                 101.50n ±  0%   96.75n ±  1%   -4.68% (p=0.000 n=20)
_Router_Handler_Strict_Case-16      91.91n ±  0%   86.66n ±  1%   -5.71% (p=0.000 n=20)
_Router_Chain-16                    308.1n ±  1%   305.4n ±  0%   -0.89% (p=0.000 n=20)
_Router_WithCompression-16          310.8n ±  0%   305.4n ±  0%   -1.72% (p=0.000 …
```
=> ♻️Refactor: reduce DefaultCtx from 736 to 728 bytes

router_test.go
Add two benchmarks to cover the most basic use-case with `Immutable` flag enabled
How to run:
```console
go test -v ./... -run=^$ -bench=Benchmark_Router_Next_Default -benchmem -count=4
```
Related #3367 
=> 🧹 chore: Add Immutable benchmarks for default case

path.go
In `path.go`, there is a function `findNextNonEscapedCharsetPosition` that searches for the next character position from the `charset` and skips escaped characters. However, many cases only use a single byte in the `charset`. I added a new function `findNextNonEscapedCharPosition` and refactored these cases.
```
goos: linux
goarch: amd64
cpu: AMD EPYC 9J14 96-Core Processor
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
_RoutePatternMatch//api/v1/const_|_match_|_/api/v1/const-16                      160.4n ± 1%   159.0n ± 0%  -0.84% (p=0.000 n=20)
_RoutePatternMatch//api/v1/const_|_not_match_|_/api/v1-16                        151.6n ± 0%   150.8n ± 0%  -0.53% (p=0.005 n=20) …
```
=> ♻️ Refactor: Add findNextNonEscapedCharPosition for single-byte charset cases

middleware/keyauth/keyauth.go, middleware/keyauth/keyauth_test.go
Reverts gofiber/fiber#3287
Following discussions in [issue #3358](https://github.com/gofiber/fiber/issues/3358), we have reverted changes that attempted to copy values into `context.Context` within various middlewares. These changes were removed to maintain Fiber’s lightweight design, improve performance, and avoid unnecessary complexity for users who do not require `context.Context`.  
- **Fiber prioritizes performance**, and modifying `context.Context` for every request introduces unnecessary overhead.  
- **Values are already accessible via `c.Locals()`**, making context modifications redundant.  
- **Users who need `context.Context` values can implement a trivial custom middleware** without affecting default behavior.
=> Revert "🔥 feat: Add support for context.Context in keyauth middleware"

docs/middleware/requestid.md, middleware/requestid/requestid.go, middleware/requestid/requestid_test.go
Reverts gofiber/fiber#3200
Following discussions in [issue #3358](https://github.com/gofiber/fiber/issues/3358), we have reverted changes that attempted to copy values into `context.Context` within various middlewares. These changes were removed to maintain Fiber’s lightweight design, improve performance, and avoid unnecessary complexity for users who do not require `context.Context`.  
- **Fiber prioritizes performance**, and modifying `context.Context` for every request introduces unnecessary overhead.  
- **Values are already accessible via `c.Locals()`**, making context modifications redundant.  
- **Users who need `context.Context` values can implement a trivial custom middleware** without affecting default behavior.
=> Revert "🔥 feat: Add Context Support to RequestID Middleware"

docs/middleware/csrf.md
Update the CSRF handler example to correctly retrieve the CSRF token and ensure proper error handling. Clarify the form key configuration in the comments.
=> 📒 docs: fix CSRF handler example

.github/workflows/linter.yml, docs/api/ctx.md
Update documentation of Ctx.Redirect in v2 branch after solutions decided in #3405.
Closes #3405
=> 📒 docs: Update usage of ctx.Redirect()

docs/middleware/session.md
The examples in middleware/session are using middleware/CSRF in a wrong way (also maybe just old version).
=> 📚 Doc: Fix examples in middleware/session

docs/api/ctx.md, docs/middleware/compress.md, docs/middleware/logger.md, docs/partials/routing/handler.md, docs/whats_new.md
fixes #3445
Enhance documentation to explain changes in middleware use of context Locals, the use of `CustomTags` in the logger middleware for logging Request IDs, ensuring compatibility with Fiber v3's context handling. Include examples for both recommended and alternative approaches.
=> 📝 docs: Document usage of Custom Tags in Logger middleware

app.go, mount.go, mount_test.go, router.go, router_test.go
Fixes #3104 #3442
[Bug]: Static server in sub app does not work #3104
[Bug]: When mounting a subapp with mount, the static route is inaccessible. #3442
=> 🐛 Fix routing with mount and static

app.go, middleware/static/static_test.go, mount.go, mount_test.go, router.go, router_test.go
Adoption of the better logic for building the routing tree from the v2 bug fix https://github.com/gofiber/fiber/pull/3454
=> 🚀 Improve routing treeBuild flow

redirect.go, redirect_test.go
This issue fixes redirection with flash messages breaks HTTP header format by encoding msgpack serialized binary data with hex. It has little overhead, but still we get benefit of using Messagepack. Here are the benchmark results:
```go
New:
Benchmark_Redirect_Route-16                         	 6792206	       173.7 ns/op	      16 B/op	       1 allocs/op
Benchmark_Redirect_Route_WithQueries-16             	 3043641	       391.3 ns/op	      40 B/op	       2 allocs/op
Benchmark_Redirect_Route_WithFlashMessages-16       	 2439327	       481.1 ns/op	     293 B/op	       3 allocs/op
Benchmark_Redirect_parseAndClearFlashMessages-16    	 2350215	       510.5 ns/op	     192 B/op	       7 allocs/op
Benchmark_Redirect_processFlashMessages-16          	 3483320	       344.6 ns/op	     288 B/op …
```
=> :bug: bug: fix redirection flash messages violate cookie structure

client/request_test.go, docs/api/ctx.md, docs/guide/templates.md, docs/whats_new.md
=> 📒 docs: Fix typos

app_test.go, docs/guide/routing.md, listen.go, router.go
- revert 'bound' typo fixes in bind.go
- keep `binded` terminology in templates guide
=> docs: Fix more typos across code base

helpers.go, helpers_test.go
- Expand the number of test cases for `parseAddr()`
- Fix parsing of ipv6 addresses (found by OpenAI Codex)
=> 🐛 fix: Parsing of IPv6 addresses

middleware/proxy/proxy_test.go
- adjust proxy tests to avoid external network dependencies
- add helper `createRedirectServer` used by updated tests
This change will help running the tests with agents like `codex` which disable internet access after environment is setup.
- `go test ./middleware/proxy -run Test_Proxy_Do_WithRealURL -v`
- `go test ./middleware/proxy -run Test_Proxy_Do_WithRedirect -v`
- `go test ./middleware/proxy -run Test_Proxy_DoRedirects_RestoreOriginalURL -v`
- `go test ./middleware/proxy -run Test_Proxy_DoRedirects_TooManyRedirects -v`
- `go test ./...`
=> 🧹 chore: Fix proxy middleware tests for offline environments

docs/middleware/proxy.md, docs/whats_new.md, middleware/proxy/config.go, middleware/proxy/proxy.go, middleware/proxy/proxy_test.go
This PR enhances the proxy middleware in Fiber v3 by improving API consistency and adhering to Go naming conventions:
- Renamed `TlsConfig` to `TLSConfig` in the `Config` struct to follow proper Go naming conventions for acronyms
- Removed the `WithTlsConfig` method in favor of configuring TLS directly via the `TLSConfig` property or using the `WithClient` method
- Updated all code references, comments, and tests to use the new property name
- Added a comprehensive migration guide in the "What's New" documentation to help users transition from v2 to v3
**Before (v2):**
```go
proxy.WithTlsConfig(&tls.Config{
InsecureSkipVerify: true,
})
```
**After (v3):**
```go
proxy.WithClient(&fasthttp.Client{
TLSConfig: &tls.Config{InsecureSkipVerify: true},
})
```
These changes are part of the broader …
=> Improve proxy middleware

ctx_test.go
- rely on fasthttp to sanitize header newlines
- add test verifying newline characters are replaced with spaces
=> 🧹 chore: Add unit-test for header injection

middleware/csrf/csrf_test.go
- fix session middleware test to read cookies via `fasthttp.Cookie`
- avoid clearing user values in `Test_CSRF_DeleteToken`
- `go test ./middleware/csrf -run Test_CSRF_DeleteToken -count=1`
- `go test ./...`
=> Fix CSRF middleware tests for fasthttp 1.62

AGENTS.md
- clarify vendor and Go cache check before running startup commands
- `go mod tidy && go mod download && go mod vendor`
- `go install gotest.tools/gotestsum@latest` *(fails: no route to host)*
- `make test` *(fails: missing gotestsum)*
=> Update AGENTS startup instructions

ctx.go, ctx_test.go
=> 🐛 fix: Embedded struct parsing

docs/middleware/keyauth.md, docs/whats_new.md, middleware/keyauth/config.go, middleware/keyauth/keyauth.go, middleware/keyauth/keyauth_test.go
- make authorization header parsing RFC 6750 compliant
- return standard `WWW-Authenticate` challenge when authentication fails
- add optional Realm config
- improve test-cases for the middleware
- document Realm option
=> 🧹 chore: Enhance KeyAuth middleware to better comply with RFC 6750

docs/middleware/basicauth.md, docs/whats_new.md, middleware/basicauth/basicauth.go, middleware/basicauth/basicauth_test.go, middleware/basicauth/config.go
- handle Basic authorization header more strictly
- quote `realm` parameter in `WWW-Authenticate` header
- document default challenge header
- add tests for whitespace around credentials
=> 🧹 chore: Enhance BasicAuth middleware to better comply with RFC 6750

binder/mapping.go, client/request.go, middleware/logger/tags.go
There is a [new function](https://pkg.go.dev/maps@go1.21.0#Copy) added in the Go 1.21 standard library, which can make the code more concise and easy to read.
=> ♻️ refactor: use maps.Copy to simplify code

middleware/encryptcookie/config.go, middleware/encryptcookie/config_test.go, middleware/encryptcookie/encryptcookie.go, middleware/encryptcookie/utils.go
- ensure cookies are removed when decryption fails
- validate user-provided encryption key early during middleware setup instead of during runtime.
- add invalid config keys unit tests
- refactor duplicate key validation code into one common function
=> 🧹 chore: Enhance config validation in EncryptCookie middleware

bind_test.go, binder/binder.go, binder/mapping.go, binder/mapping_test.go, ctx.go, docs/api/bind.md, docs/guide/utils.md, docs/middleware/encryptcookie.md, docs/whats_new.md, helpers.go, listen.go, middleware/cors/cors.go, middleware/cors/cors_test.go, middleware/earlydata/earlydata_test.go, middleware/static/static_test.go, path.go, path_test.go, prefork.go
- fix various spelling mistakes in code and docs
=> 🧹 chore: Fix typos in code and docs

docs/middleware/envvar.md, docs/whats_new.md, middleware/envvar/envvar.go, middleware/envvar/envvar_test.go
- Prevent exposure of environment variables when using the `EnvVar` middleware with default settings.
- Update tests to reflect the new behavior.
- Document that the default configuration no longer exports all environment variables.
=> 🧹 chore: Refactor EnvVar middleware

docs/middleware/cors.md
Improve the documentation for the CORS middleware by adding information about preflight requests and important infrastructure considerations to ensure proper configuration and functionality. Include debugging tips and common issues related to CORS headers in various deployment scenarios.
Closes #3501
=> 📒 docs: Enhance CORS middleware documentation with preflight request details and infrastructure considerations

middleware/earlydata/earlydata_test.go
- add missing tests for config.go
- refactor earlydata_test.go
- add missing test for `next()`.
=> 🧹 chore: Improve EarlyData middleware tests coverage

middleware/idempotency/idempotency_test.go, middleware/idempotency/stub_test.go
- Increased Test Coverage: Added numerous new test cases to improve coverage of the idempotency middleware, focusing on configuration edge cases and various error handling paths.
- Stub Implementations for Testing: Introduced stubLock and stubStorage types to simulate dependencies (Locker and fiber.Storage) and facilitate testing of error conditions and specific middleware interactions.
- Error Path Testing: Added specific tests to verify the middleware's behavior when encountering errors during storage operations (Get, Set), locking (Lock, Unlock), unmarshalling cached data, and when the main handler returns an error.
- Configuration Testing: Included tests to cover the default configuration (configDefault) and how overrides are handled, ensuring expected behavior for Next, …
=> 🧹 chore: Improve Idempotency middleware tests coverage

middleware/csrf/extractors_test.go
- add tests for missing CSRF token extractors
=> 🧹 chore: Add missing CSRF token extractor tests

.github/codecov.yml, .github/workflows/test.yml, hooks_test.go
- Improve test coverage of hooks.go
=> 🧹 chore: Improve hooks test coverage

.github/codecov.yml
- Ignore `root` level generated files from `codecov`.
- Codecov is now ignoring `msgp` everywhere. See here https://app.codecov.io/gh/gofiber/fiber/pull/3528/tree
=> 🧹 chore: Update codecov configuration

binder/binder_test.go
- add error-path tests for binder functions inside existing test file
- test custom parser decoding and map handling
=> 🧹 chore: Improve Binder tests coverage

middleware/cors/cors_test.go
- add regression test for warning when AllowOrigins is wildcard and AllowOriginsFunc is set.
=> 🧹 chore: Improve CORS tests coverage

docs/middleware/basicauth.md, docs/whats_new.md, middleware/basicauth/basicauth.go, middleware/basicauth/basicauth_test.go, middleware/basicauth/config.go
- Add new `StorePassword` config option. Defaults to `False` to avoid leaking credentials via `Context`.
- Add `charset` parameter. Defaults to `UTF-8`.
- Set `"no-store"` header for Cache Control.
=> 🧹chore: Improve BasicAuth middleware default security

middleware/csrf/csrf_test.go
- add regression tests covering CSRF config cookie SameSite warnings
- ensure deleteTokenFromStorage handles session and storage branches
=> 🧹 chore: Improve CSRF tests coverage

ctx.go, ctx_test.go
- handle parameters and casing when comparing MIME types in `Ctx.Is`.
- update tests for case-insensitive comparison.
- add test that mismatched subtype does not match.
=> 🐛 bug: Fix Content-Type comparison in Is()

ctx.go, ctx_test.go, docs/api/ctx.md
- enforce recognized `bytes` unit and trim whitespace when parsing Range header
- document Range behavior in API reference
- add regression tests for whitespace and unrecognized units
- improve rfc 9110 compliance.
=> 🐛 bug: Fix Range() parsing of bytes unit

.github/workflows/linter.yml, .golangci.yml, ctx.go, ctx_test.go, docs/middleware/etag.md, helpers.go, helpers_test.go
- enforce RFC 9110 quoted tags in `matchEtag`
- update ctx tests to use quoted ETags
- add tests for `matchEtag` and `isEtagStale`
- document requirement for quoting entity tags
- add strong ETag comparison helper
Related: #3383
=> 🐛 bug: Fix Etag validation per RFC 9110

ctx.go, ctx_test.go, docs/api/ctx.md
- send 416 status automatically for unsatisfiable ranges
- document automatic 416 handling in Range()
- test 416 Range Not Satisfiable response
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/416
=> 🐛 bug: Fix Range() handling of HTTP 416 per RFC 9110

ctx.go, ctx_test.go, docs/api/ctx.md, helpers.go, helpers_test.go
- follow RFC 4647 basic filtering for `Accept-Language`
- add tests for invalid and multi-language scenarios
Related #3383
=> 🐛 bug: Fix Accept-Language matching per RFC 4647

ctx_interface_gen.go, docs/middleware/cache.md, middleware/cache/cache.go, middleware/cache/cache_test.go, middleware/cache/manager.go, middleware/cache/manager_msgp.go, middleware/cache/manager_msgp_test.go, middleware/csrf/storage_manager_msgp_test.go, middleware/idempotency/response_msgp_test.go, middleware/session/data_msgp_test.go
- RFC 9111 Compliance for Age Header: The cache middleware now correctly calculates and sets the Age header for cached responses. It achieves this by storing the Age value received from the upstream server and adding the time the response has been resident in the cache, adhering to the specifications of RFC 9111.
- Stop Caching 418 I'm a teapot Responses: The middleware has been updated to no longer cache responses with the 418 I'm a teapot status code. This change removes a non-standard caching behavior and aligns the middleware with typical HTTP caching practices.
=> 🐛 bug: Fix Cache middleware handling of Age

constants.go, ctx.go, ctx_test.go, docs/api/ctx.md
- enforce RFC9110 handling for unknown content-encodings
- document new 415/501 behaviour in Body()
- test unsupported encodings
=> 🐛 bug: Fix Body() handling of Content-Encoding per RFC 9110

ctx.go, ctx_interface_gen.go, docs/api/ctx.md
- Update documentation for `Stale()`
=> 📒 docs: Add documentation for Stale()

client/request.go, client/response.go
Reduce iterator time complexity from **O(n<sup>2</sup>)** to **O(n log n)**
+ `Request.Params()`
+ `Request.AllFormData()`
```
goos: darwin
goarch: arm64
pkg: github.com/gofiber/fiber/v3/client
cpu: Apple M4
│   old.txt    │           new.txt           │
│    sec/op    │   sec/op     vs base        │
_Request_Params-10        135.70n ± 0%   41.01n ± 0%  -69.78% (n=50)
_Request_AllFormData-10   135.60n ± 0%   94.67n ± 0%  -30.18% (n=50)
geomean                    135.6n        62.31n       -54.07%
│   old.txt   │          new.txt           │
│    B/op     │    B/op     vs base        │
_Request_Params-10        232.00 ± 0%   88.00 ± 0%  -62.07% (n=50)
_Request_AllFormData-10    232.0 ± 0%   184.0 ± 0%  -20.69% (n=50)
geomean                    232.0        127.2       -45.15%
│  old.txt …
```
=> ♻️ Refactor: improve iterator performance.

client/cookiejar.go, client/cookiejar_test.go
- simplify expired cookie removal using kept slice technique
- avoid unnecessary string conversions in cookiejar and allocate keys via utils.CopyString
- adjust cookie lookup path matching to use prefix logic
=> Fix cookiejar key handling and cleanup

helpers.go, helpers_test.go, radix/radix_test.go, router_radix_test.go
- ensure `routeConstPrefix` handles optional parameters without trailing slashes
- cover radix tree implementation with additional tests
- test router features while `UseRadix` is enabled
- add tests for constant prefix helper
This PR is to enhance #3591
=> 🧹 chore: Improve Radix router test coverage

Makefile, docs/middleware/csrf.md, docs/whats_new.md, middleware/csrf/config.go, middleware/csrf/csrf.go, middleware/csrf/csrf_test.go, middleware/csrf/extractors.go, middleware/csrf/extractors_test.go, middleware/csrf/token.go
Simplify CSRF configuration by removing unnecessary components and improving extractor functionality. Add support for route-specific extractors and enhance documentation for clarity and accuracy. Improve error handling and validation within the CSRF middleware.
Supersedes #3589
=> Refactor CSRF middleware and enhance documentation

app_test.go, middleware/static/static.go, middleware/static/static_test.go
before:
```
Benchmark_SanitizePath/nilFS_-_urlencoded_chars
Benchmark_SanitizePath/nilFS_-_urlencoded_chars-12         	 4756809	       234.2 ns/op	     168 B/op	       5 allocs/op
Benchmark_SanitizePath/nilFS_-_urlencoded_chars-12         	 5268462	       228.8 ns/op	     168 B/op	       5 allocs/op
Benchmark_SanitizePath/nilFS_-_urlencoded_chars-12         	 5243587	       228.7 ns/op	     168 B/op	       5 allocs/op
Benchmark_SanitizePath/nilFS_-_urlencoded_chars-12         	 5228282	       228.9 ns/op	     168 B/op	       5 allocs/op
Benchmark_SanitizePath/dirFS_-_urlencoded_chars
Benchmark_SanitizePath/dirFS_-_urlencoded_chars-12         	 4437174	       269.1 ns/op	     192 B/op	       6 allocs/op
Benchmark_SanitizePath/dirFS_-_urlencoded_chars-12         	 4466428	       270.7 …
```
=> [Static]: Improve sanitizePath performance

ctx.go
- use equality instead of prefix when parsing request body
=> 🐛 bug: Fix MIME type equality checks

app.go, ctx.go, ctx_interface.go, ctx_interface_gen.go, radix/radix.go, radix/radix_test.go, router.go, router_radix_test.go
- switch radix tree implementation to use generics instead of `any`
- update router and app to use `radix.Tree[[]*Route]`
- adjust radix tests for typed tree
- clean up duplicated comments
=> Enhance radix tree with generics

docs/middleware/limiter.md, middleware/limiter/config.go, middleware/limiter/limiter_fixed.go, middleware/limiter/limiter_sliding.go, middleware/limiter/limiter_test.go
- introduce `DisableHeaders` option for limiter middleware
- set X-RateLimit headers only when not disabled
- document how to disable the headers
- test limiter without headers
=> 🔥 feat: Support for disabling response headers in Limiter Middleware

docs/middleware/basicauth.md, docs/whats_new.md, middleware/basicauth/basicauth.go, middleware/basicauth/basicauth_test.go, middleware/basicauth/config.go
- add `HeaderLimit` option to BasicAuth middleware
- enforce authorization header length in middleware
- document `HeaderLimit` in docs
- note the change in what's new
- test header limit handling
- add unit tests for empty or whitespace-only auth headers
=> 🔥 feat: Add HeaderLimit option to BasicAuth middleware

docs/middleware/session.md, docs/whats_new.md, middleware/csrf/csrf_test.go, middleware/session/config.go, middleware/session/config_test.go, middleware/session/extractors.go, middleware/session/extractors_test.go, middleware/session/middleware.go, middleware/session/middleware_test.go, middleware/session/session.go, middleware/session/session_test.go, middleware/session/store.go, middleware/session/store_test.go
Implement a flexible Extractor function pattern for session ID retrieval, replacing the previous string-based KeyLookup. Enhance session middleware to support extraction from cookies, headers, queries, and forms. Add a Regenerate method to maintain session data while changing session IDs and improve session lifecycle management by requiring manual session release. Update tests and introduce error handling for missing session IDs in various contexts.
=> feat(middleware/session): Introduce Extractor pattern for session ID retrieval

docs/middleware/requestid.md
- clarify RequestID middleware docs on header reuse and context storage
=> 📒docs: Fix RequestID docs

docs/middleware/keyauth.md, middleware/keyauth/config.go
- clarify default behaviour for `AuthScheme`
=> 📒docs: Fix KeyAuth middleware docs

bind.go, bind_test.go
- add internal validation skip to Bind
- merge all sources without early validation and skip empty bodies
- avoid body binding when Content-Type header is missing
- expand All() tests for query precedence, validators, and missing Content-Type cases
Fixes #3658
=> 🐛 bug: Fix bind All() merging logic

app_test.go, ctx_test.go
- extend context tests with response content-type and size assertions
- add coverage for missing Accept header
=> 🧹 chore: Add missing checks in Ctx tests

docs/middleware/timeout.md
- clarify what the timeout middleware does
- add a full runnable example and curl instructions
- warn against registering the timeout middleware with `app.Use`, which will panic
Fixes #3674
=> 📒 docs: Improve Timeout middleware documentation

docs/middleware/encryptcookie.md, docs/middleware/keyauth.md, docs/whats_new.md, middleware/keyauth/config.go, middleware/keyauth/config_test.go, middleware/keyauth/extractors.go, middleware/keyauth/extractors_test.go, middleware/keyauth/keyauth.go, middleware/keyauth/keyauth_test.go
This PR modernizes the `keyauth` middleware by replacing the legacy string-based key extraction configuration (`KeyLookup`, `AuthScheme`, `CustomKeyLookup`) with a robust, type-safe extractor system. This update improves flexibility, composability, and clarity for users implementing API key authentication in Fiber.
- **Extractor-Based API Key Retrieval:**  
- Introduces a new `Extractor` field for configuration, allowing explicit selection of where to extract the API key (header, auth header, query, param, cookie, form).
- Provides helper functions:  
- `FromHeader(header string)`
- `FromAuthHeader(header, scheme string)`
- `FromCookie(name string)`
- `FromQuery(param string)`
- `FromParam(param string)`
- `FromForm(name string)`
- `Chain(...)` for chaining multiple extractors.
- **Config …
=> Refactor KeyAuth Middleware: Extractor-Based Configuration and Enhanced Flexibility

middleware/filesystem/filesystem.go, middleware/filesystem/filesystem_test.go
When using `os.DirFS` as the filesystem root and accessing an invalid path the server return a HTTP status 500. This PR changes this to return 404.
Minimal example to reproduce the issue:
```go
package main
import (
"log"
"net/http"
"os"
"github.com/gofiber/fiber/v2/middleware/filesystem"
)
func main() {
app.Use("/", filesystem.New(filesystem.Config{
Root: http.FS(os.DirFS("./static")),
}))
log.Fatal(app.Listen(":3000"))
}
```
Run and navigate to `http://localhost:3000/](//invalid` which causes an internal error.
=> 🐛 bug: Handle invalid path in filesystem

docs/extra/learning-resources.md, docs/intro.md
This PR adds a **Learning Resources** section to the Fiber documentation, featuring the **Go Interview Practice** platform - an interactive learning environment where developers can practice Fiber concepts through hands-on challenges. This addresses the community request from issue #3663 to include interactive learning resources similar to how the Gin framework showcases community tools.
The integration provides developers with a structured learning path covering essential Fiber concepts: basic routing, middleware development, input validation, and authentication systems. This complements the existing documentation by offering practical, hands-on experience with Fiber's high-performance features.
Related #3663
This pull request introduces community-driven learning resources to help …
=> 📒 docs: Add Learning Resources section with Go Interview Practice platform

docs/middleware/keyauth.md, middleware/keyauth/config.go, middleware/keyauth/extractors.go, middleware/keyauth/extractors_test.go, middleware/keyauth/keyauth.go, middleware/keyauth/keyauth_test.go
- send a generic error message for all KeyAuth failures
- update KeyAuth tests and docs to use the generic message
=> 🧹 chore: Return generic errors in KeyAuth middleware

docs/guide/advance-format.md, docs/guide/error-handling.md, docs/guide/faster-fiber.md, docs/guide/grouping.md, docs/guide/templates.md, docs/intro.md, docs/whats_new.md
- polish intro and routing docs for clearer guidance
- refine JSON encoder advice and fix syntax example
- clarify error handling, templating, advanced format, and grouping docs
=> 📒 docs: Improve wording and fix typos

docs/middleware/compress.md, docs/whats_new.md, middleware/compress/compress.go, middleware/compress/compress_test.go, middleware/etag/etag.go
- skip compression when Content-Encoding already set
- add Accept-Encoding to Vary header when compressing
- tokenize Vary merging and avoid appending when header is `*`
- recompute strong ETags after compression using shared generator
- skip compression for status codes with no body or range/206 responses
- honor `Cache-Control: no-transform` on requests and responses
- propagate compression headers on HEAD responses while omitting the body
- emit `Vary: Accept-Encoding` even when compression is skipped, including when the request lacks `Accept-Encoding`
- cover Vary header, pre-encoded responses, ETag recalculation, no-body skips, range requests, no-transform, HEAD metadata, and skip-branch Vary merging in tests
- document compression behavior in middleware docs and whats_new
Related …
=> 🧹 chore: Improve Compress middleware RFC compliance

docs/middleware/keyauth.md, docs/whats_new.md, middleware/keyauth/config.go, middleware/keyauth/extractors.go, middleware/keyauth/extractors_test.go, middleware/keyauth/keyauth.go, middleware/keyauth/keyauth_test.go
- use `Proxy-Authenticate` on 407 responses
- validate bearer error tokens and require `error_description` to pair with `error`
- default to an `ApiKey` challenge when no Authorization scheme is present
- include optional Bearer `error_uri` parameter
- advertise all configured auth schemes in `WWW-Authenticate` headers
- reject tabs between auth scheme and credentials
- support Bearer `scope` parameter for `insufficient_scope` errors
- trim mixed leading/trailing spaces and tabs around Authorization headers
- reject Authorization credentials containing spaces or tabs
- validate `error_uri` as an absolute URI
- validate Authorization credentials as RFC 7235 token68 strings with trailing `=` padding only at the end
- enforce RFC 6750 scope-token syntax
Related #3383
=> 🧹 chore: Improve KeyAuth middleware RFC compliance

middleware/cache/cache.go, middleware/cache/cache_test.go, middleware/cache/manager.go, middleware/cache/manager_test.go, middleware/csrf/csrf.go, middleware/csrf/csrf_test.go, middleware/csrf/storage_manager.go, middleware/csrf/storage_manager_msgp.go, middleware/limiter/limiter_fixed.go, middleware/limiter/limiter_sliding.go, middleware/limiter/limiter_test.go, middleware/limiter/manager.go, middleware/session/data_msgp.go
- Improve handling of errors when using a storage driver
Replaces #3597
=> 🧹 chore: Improve error handling when using storage drivers

path.go
+ Refactor functions `findNextCharsetPosition`, `findNextCharsetPositionConstraint`, and `findNextNonEscapedCharsetPosition` to reduce time complexity from **O(len(search)len(charset))** to **O(len(search))** and inline them into the function `analyseParameterPart`.
+ Improve the performance of `findNextParamPosition`.
```
goos: linux
goarch: amd64
cpu: AMD EPYC 7763 64-Core Processor                
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
_RoutePatternMatch//api/v1/const_|_match_|_/api/v1/const-2                      227.8n ± 2%   207.8n ± 5%   -8.82% (p=0.000 n=20)
_RoutePatternMatch//api/v1/const_|_not_match_|_/api/v1-2                        218.5n ± 5%   202.2n ± 3%   -7.44% (p=0.000 …
```
=> ♻️ Refactor: Improve performance analyseConstantPart

readonly.go, readonly_strict.go
- restrict the runtime rodata alignment helper to platforms other than s390x/ppc64/ppc64le
- provide a strict-alignment fallback that always treats pointers as writable on those platforms
Fixes #3771
=> 🐛 bug: Fix usage of runtime RO data for ppc64 and s390x platforms

client/client.go, client/hooks.go, client/hooks_test.go, client/request.go
- add client and request options to disable path normalizing and plumb them through request configuration
- update URL parsing to preserve encoded paths when normalization is disabled and add regression tests
Fixes #3096
=> 🐛 bug: Respect DisablePathNormalizing during client requests

client/hooks.go, client/hooks_test.go
Currently file doesn't get closed if any of errors at lines 299 or 303 return:
https://github.com/gofiber/fiber/blob/e8f639a4d9f58fda8424f32610abc9c4d048dc26/client/hooks.go#L288-L308
=> 🐛 fix: Always close form file
