gofiber/fiber

- docs/context.md
- go.mod
- request_test.go
- response.go
- response_test.go
- utils.go
```go
// Raw http request
raw := "GET / HTTP/1.1\r\nHost: localhost:8080\r\n\r\n"
// Fiber app
app := New()
app.Get("/", func(c *Ctx) {
fmt.Println(c.BaseURL())
})
// Disable Listen if you are testing local requests
// app.Listen(8080)
// Send fake request
resp, err := app.FakeRequest(raw)
// Check for errors and if route was handled
if err != nil {
panic(err)
}
```
> Add FakeRequest for testing locally

- request.go
- request_test.go
Add more tests to `request_test.go`, aiming for 80% coverage +/-
> More tests x.x

- request.go
- request_test.go
Add more tests to `request_test.go`
> Add tests for 85.1% coverage

- listen.go
- request_test.go
- response_test.go
- utils.go
- https://fiber.wiki/#/application?id=test
- https://github.com/gofiber/fiber/issues/41#issuecomment-583017442
```go
package main
import (
"fmt"
"io/ioutil"
"net/http"
"github.com/gofiber/fiber"
)
func main() {
app.Post("/test", func(c *fiber.Ctx) {
fmt.Println(c.Hostname()) // => example.com
})
req, _ := http.NewRequest("POST", "/test", nil)
req.Host = "example.com"
resp, _ := app.Test(req)
if resp.StatusCode == 200 {
body, _ := ioutil.ReadAll(resp.Body)
fmt.Println(string(body))
}
}
```
> Release Test function for Fiber

- application.go
- listen.go
- listen_test.go
- methods_test.go
- request_test.go
- response.go
- response_test.go
- static_test.go
- utils.go
> Add Shutdown

- .github/readme2.md
- request.go
https://github.com/gofiber/docs/pull/3
> Add optional offset arg to Subdomains

- application.go
- go.mod
- go.sum
> Use colorable for Windows

- application.go
- router.go
- utils.go
```go
func main(){
// The actual method name is still up for a vote: group vs route
v1 := app.Group("/v1")
v1.Use(midware()) // => /v1
v1.Get("/read", read()) // => /v1/read
v1.Post("/write", write()) // => /v1/write
v1.Delete("/delete", delete()) // => /v1/delete
app.Listen(3000)
}
```
> Add grouping

- .github/README_CH.md
> update Chinese translate 😀

- README.md
> Grammar fix for the english README

- .github/README_de.md
Hi, first of all congratulations on such an awesome hype 🚀 
I have translated the whole `README.md` to German.
This is a draft because I want to look over it again tomorrow, so that I can find mistakes, if there are any that I don't see now.
If somebody else finds some, feel free to write them down :)
> German README

- .github/README_ko.md
Greetings, 
I translated README.md to korean. 
Hope this will be helpful to korean gophers using fiber.
> Add korean readme

- .github/README_pt.md
The translation wasn't 100% accurate, so i edited some of then and some semantic structure.
> Fix README_pt translation

- .github/README_ko.md
Hi,
I made a small update to README_ko.md to match README.md 🙂
> Update korean readme

- .github/README_ja.md
hello!
I'm a japanese programmer
I made a small update to `.github/README_ja.md` to match `.github/README.md`
> Update japanese readme

- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_zh-CN.md
Hi ! 
here's a PR implementing the translation of the README, in french.
> Add French translation for README

- .github/workflows/security.yml
Well, I am testing this project because I think of getting used to it. So I resolve to run `GoSec` to valid security this code then it identifies a little problem that looks `false positive` according to below. However, I believe that we must propose a new pipeline for this project to validate security.
```
[gosec] 2020/02/20 23:33:41 Including rules: default
[gosec] 2020/02/20 23:33:41 Excluding rules: default
[gosec] 2020/02/20 23:33:41 Import directory: /Users/renanbastos/git/folks/fiber
[gosec] 2020/02/20 23:33:42 Checking package: fiber
[gosec] 2020/02/20 23:33:42 Checking file: /Users/renanbastos/git/folks/fiber/application.go
[gosec] 2020/02/20 23:33:42 Checking file: /Users/renanbastos/git/folks/fiber/request.go
[gosec] 2020/02/20 23:33:42 Checking file: …
```
> feat: pipeline to valid security this project using GoSEC

- app.go
- utils.go
https://github.com/gofiber/fiber/issues/159
> Fix flag bug

- .travis.yml
- app.go
https://github.com/gofiber/fiber/issues/159
> Fix flag redefined

- .github/README.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
add [go.dev](https://go.dev/) iocn
> Upddate README.md add go.dev

- context.go
https://github.com/gofiber/fiber/issues/168
> Remove conn.Close()

- .github/README.md
- .github/README_ru.md
- Add media link
- Add new v1 code examples
> Add media link, Add new v1 code examples

- .github/README_zh-CN.md
> update chinese README

- context.go
- context_test.go
- go.mod
Support for range header
https://expressjs.com/en/api.html#req.range
Don't support the option of "combine". If you think it is necessary, I can add it later.
> support for range header

- .github/README.md
- .github/README_ru.md
- EN - Add CORS and Logger examples
- RU - Add CORS, Logger and WebSocket examples
> Add new examples to README (EN, RU)

- .github/README.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
Thanks for this beautiful project, hopefully this translation useful for Indonesian Gophers.
> Translated Readme to Indonesian

- .github/README.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
- Add [Creating Fast APIs In Go Using Fiber](https://dev.to/jozsefsallai/creating-fast-apis-in-go-using-fiber-59m9) article to Media block.
> Add new article to Media block

- .github/README.md
- .github/README_de.md
- .github/README_es.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
I added Dutch translations for Fiber.
For the flag, I have created a PR in gofiber/docs (https://github.com/gofiber/docs/pull/66).
> Add Dutch translation

- .github/workflows/security.yml
Based on documentation from Gosec change our file to run workflow security.
Reference: https://github.com/securego/gosec#github-action
> refactor: workflow to Gosec

- app.go
Added ASCII Fiber logo for branding
```
_______ __
____ / ____(_) /_  ___  _____
_____ / /_  / / __ \/ _ \/ ___/
__ / __/ / / /_/ /  __/ /
/_/   /_/_.___/\___/_/
```
> Add ASCII Fiber logo

- .github/README.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
- Update video tutorial on all readme's
- Add crowdin badge
> Update media + localizer

- ctx_test.go
> ctx_test: impl Test_FormFile

- ctx_test.go
Impl function: `Test_SaveFile`
> ctx_test: impl Test_SaveFile

- ctx.go
- utils.go
#311, copied from [jshttp/fresh](https://github.com/jshttp/fresh/blob/10e0471669dbbfbfd8de65bc6efac2ddd0bfa057/index.js#L33)
> Fresh(#311)

- .github/README_es.md
Completed missing translations.
> 📚 Update README_es.md

- .github/README.md
Is it I need to add to all `README.md`s as well?
> add media blog post

- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
relates to https://github.com/gofiber/fiber/pull/333#issuecomment-622321128
> add media blog post to all READMEs

- dev/bench/data.js
- dev/bench/index.html
- index.html
> Mobile responsive charts

- .github/README.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
I Added link to all README_*.md
> Added link to README_ar_SA

- .gitignore
- app_test.go
- utils.go
Reduce pre allocated memory, fix Etag benchmark, cleanup unused stuff
> Reduce pre allocated memory, fix Etag benchmark, cleanup unused stuff

- ctx.go
https://github.com/gofiber/fiber/issues/405 @ReneWerner87
> Hot fix delimiter miss match

- app.go
- ctx.go
- ctx_test.go
https://github.com/gofiber/fiber/issues/441
> 🗎 Add layout support in Render

- app.go
add predefined flags to avoid errors
> 🐛 flag.Parse not working when using Prefork on Fiber #469

- .github/README.md
- .github/README_ar_SA.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
Removed stargazers and releases badges.
> Remove unnecessary badges in README files

- app.go
- app_test.go
- router.go
- router_test.go
- utils.go
https://github.com/gofiber/fiber/issues/492
> Add 405 response for methods not allowed

- app.go
https://github.com/gofiber/fiber/issues/489
> Update timeout comments

- app.go
- ctx.go
- router_test.go
- utils_test.go
> 🚀 Added possibility to work with urlencoded special characters in the route

- .github/README.md
- .github/README_ar_SA.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
This it the first media/tutorial on spanish? I hope this could help someone
> Doc: Add media tutorial on spanish

- .github/README.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
Creating this PR due to unable to add a new translation on crowdin.
> Add zh-TW translation

- middleware/logger.go
- middleware/logger_test.go
> Set logger config default values

- app.go
- go.mod
- middleware/README.md
- middleware/compress.go
- middleware/compress.md
- middleware/filesystem.go
- middleware/logger.go
- prefork.go
- Add filesystem middleware
- Add middleware readme
- Update logger middleware
- Fix typo's
> Disable colors if not supported

- middleware/compress.go
- middleware/compress.md
- middleware/favicon.md
- middleware/filesystem.go
- middleware/logger.go
- middleware/logger.md
- middleware/logger_test.go
- middleware/recover.md
- middleware/request_id.go
- middleware/request_id.md
- middleware/timeout.md
- Update readme descriptions and examples
> Update internal middleware

- middleware/compress.go
- middleware/logger.go
- middleware/request_id.go
- middleware/timeout.go
Co-Authored-By: RW <renewerner87@googlemail.com>
> Fix timeout panic

- app.go
Co-Authored-By: RW <renewerner87@googlemail.com>
> Bump v1.12.3

- app_test.go
- ctx.go
- ctx_test.go
- middleware/compress.go
- middleware/logger.go
- middleware/request_id.go
- middleware/timeout.go
- middleware/timeout_test.go
- utils.go
Co-Authored-By: kiyon <kiyonlin@163.com>
> Micro optimization

- ctx.go
Co-Authored-By: RW <renewerner87@googlemail.com>
> Add default value support

- .github/README.md
fix broken code with proper markdown syntax.
> docs(README.md): fix README.md documentation

- ctx.go
- ctx_test.go
- router.go
- router_test.go
- https://github.com/gofiber/fiber/pull/545
> 🔨 Make Params Public

- .github/README_pt.md
In this PR, I've tried to improve some of parts of the Portuguese translated README.
> 📝 Improve PT translation for README

- app.go
- https://github.com/gofiber/fiber/issues/555
> 💡 Show possible signatures

- .github/README.md
- .github/README_ar_SA.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
Co-Authored-By: Demby Genesis M. Abella <dembygenesis@users.noreply.github.com>
> ✏ Correct Static Example

- prefork.go
https://github.com/gofiber/fiber/issues/575
> 📦 Detect Child process

- ctx.go
- ctx_test.go
Related to https://github.com/gofiber/fiber/pull/581
> 🚀 Improve JSON response

- ctx.go
- ctx_test.go
🚀  New Function: QueryParser; separated from BodyParser #572
> 🚀 feat: created method QueryParser in context; separated from BodyParser

- app.go
- ctx.go
Closes #592 
I've tried to be as descriptive as I can in the commit messages, and also follow your commit message guidelines.
This PR aims to improve the GoDoc documentation for `app.go` and `ctx.go` (the two files I had a chance to read through tonight).
> 📚 Docs improvements

- app.go
- group.go
- router.go
- utils.go
> 👷 Add use methodInt and Extract "USE" to a global const variable

- app_test.go
- prefork.go
currently, there are some lint issues about master code , details  look like:
```
golint ./...
app_test.go:615:2: var gApi should be gAPI
prefork.go:76:22: error strings should not be capitalized or end with punctuation or a newline
```
So I make a pull request for it.
> Update for golint

- app.go
- app_test.go
- ctx.go
- ctx_test.go
- middleware/request_id_test.go
- utils_test.go
```
go test -count=1 -cover
PASS
coverage: 87.0% of statements
```
close #598
> Improve coverage

- ctx.go
- utils.go
* Changed many `if` to a `switch case`
* Removed unused variable
* Defined alias tag when needed
> 🚀 refactor: improve logic method BodyParser

- ctx.go
- ctx_test.go
After #611 merged, will improve `ctx.BodyParser` performance
> 🆕 Create ctx.BodyParser benchmark

- ctx.go
- ctx_test.go
- prefork.go
- prefork_test.go
- reuseport.go
```
go test -count=1 -cover
PASS
coverage: 95.6% of statements
```
> 💯 improve ctx test coverage

- ctx.go
OLD:
```
Benchmark_Ctx_BodyParser_JSON
Benchmark_Ctx_BodyParser_JSON-4                  1452151               817 ns/op             368 B/op          7 allocs/op
Benchmark_Ctx_BodyParser_JSON-4                  1461086               821 ns/op             368 B/op          7 allocs/op
Benchmark_Ctx_BodyParser_JSON-4                  1458460               819 ns/op             368 B/op          7 allocs/op
Benchmark_Ctx_BodyParser_JSON-4                  1430881               825 ns/op             368 B/op          7 allocs/op
Benchmark_Ctx_BodyParser_XML
Benchmark_Ctx_BodyParser_XML-4                    341536              2947 ns/op            1312 B/op         26 allocs/op
Benchmark_Ctx_BodyParser_XML-4                    404234              2923 ns/op            1312 B/op         26 …
```
> 🚀 improve ctx.BodyParser performance

- app_test.go
- ctx_test.go
- prefork.go
- prefork_dummy.go
- prefork_dummy_windows.go
- prefork_test.go
96.8% -> 97.6%(98.1% without deprecated feature code)
>  👷 improve app and prefork test coverage

- ctx_test.go
Add extra statements to cover #625
> 📗 improve ctx.Render test

- app_test.go
- prefork_test.go
> 💯 remain code coverage

- app.go
- ctx.go
> ✏️  Fix typo for app and ctx warnings

- app.go
- middleware/logger.go
Fix https://github.com/gofiber/fiber/issues/639
> 🎨 Fix colors for Windows

- middleware/logger.go
- middleware/logger_test.go
Co-Authored-By: KallyDev <kallydev@gmail.com>
Followup for https://github.com/gofiber/fiber/pull/652
> ⏲ Optimize time zone support

- ctx.go
Co-Authored-By: RW <renewerner87@googlemail.com>
Fix for https://github.com/gofiber/fiber/issues/650
> 🧉 Allow missing space in Content-Type's using BodyParser

- .github/SECURITY.md
Update supported version to 1.12.6, added `team@gofiber.io` e-mail address to report security problems.
> 📝 Update Security Policy

- .github/.editorconfig
> ✍ Update editorconfig

- ctx_test.go
- router.go
Handle invalid http method directly
If the http method is invalid, it will cause panic(runtime error: index out of range [-1] [recovered]) because of `lenr := len(app.stack[ctx.methodINT]) - 1` in `app.next`. If users don't set recovery middleware, their apps will crash.
> 🩹 handle invalid http method

- app.go
- ctx.go
- utils.go
> 🧹 Remove deprecated Templates

- utils.go
- utils_test.go
Add more test cases and benchmark
> ✈️ improve isNoCache a little bit

- middleware/logger.go
To improve the performance and precision
`time.Sleep(500 * time.Millisecond)` will impact precision when user set the time format which accurate to milliseconds.
And seems that `atomic.Value` has better performance.
OLD:
```
Benchmark_Middleware_Logger-8             993579              1215 ns/op             281 B/op          3 allocs/op
Benchmark_Middleware_Logger-8            1000000              1184 ns/op             281 B/op          3 allocs/op
Benchmark_Middleware_Logger-8            1000000              1127 ns/op             281 B/op          3 allocs/op
Benchmark_Middleware_Logger-8 …
```
> 🚀 use atomic.Value instead of sync.Mutex

- .github/README.md
- .github/README_ar_SA.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
> Added fiber boilerplate

- middleware/logger.go
Update the default values, as they have changed.
Update a comment regarding the update of date/time.
> Update LoggerConfig documentation

- .github/testdata/index.html
- middleware/filesystem/filesystem.go
- middleware/filesystem/filesystem_test.go
* Add feature to filesystem middleware that returns specified file if path is not found
* Also add test cases
Fixes #708
> ✨ Add feature to filesystem middleware that returns specified file if path is not found

- middleware/cors/cors.go
See file change for more details
```go
if cfg.AllowMethods == "" {
cfg.AllowOrigins = ConfigDefault.AllowMethods
}
```
to
```go
if cfg.AllowMethods == "" {
cfg.AllowMethods = ConfigDefault.AllowMethods
}
```
> Fix CORS config bug

- .github/workflows/benchmark.yml
Co-Authored-By: RW <7063188+ReneWerner87@users.noreply.github.com>
> 💪 add pipefail to benchmarks

- utils/common_test.go
Co-Authored-By: RW <7063188+ReneWerner87@users.noreply.github.com>
> 🔨 fix test

- middleware/proxy/proxy_test.go
> 🔨 fix proxy test

- .github/README.md
- .github/README_ar_SA.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
- middleware/filesystem/README.md
> 📖 update readme

- middleware/filesystem/filesystem.go
Fix `NotFoundFile` config option by adding a `/` like for `Index` in filesystem middleware
> 🐛 Update filesystem.go to fix NotFoundFile

- .github/README.md
- .github/README_ar_SA.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
Re-adding my cache middleware to the READMEs since it vanished at some point. I also sorted them alphabetically.
> 📝 Re-add fiber-cache middleware

- app.go
- app_test.go
- prefork_test.go
> 👷 improve app and prefork test cases

- helpers_test.go
> 👷 improve helpers test cases

- middleware/pprof/pprof.go
- middleware/pprof/pprof_test.go
> 👷 improve pprof test cases

- .github/README.md
- .github/README_ar_SA.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
- middleware/limiter/limiter.go
> 📦 fix limiter

- middleware/basicauth/basicauth_test.go
- middleware/compress/compress.go
- middleware/compress/compress_test.go
- middleware/cors/cors.go
- middleware/cors/cors_test.go
- middleware/csrf/csrf.go
- middleware/csrf/csrf_test.go
- middleware/favicon/favicon_test.go
- middleware/filesystem/filesystem.go
- middleware/filesystem/filesystem_test.go
- middleware/limiter/limiter_test.go
- middleware/logger/logger__test.go
- middleware/recover/recover.go
- middleware/recover/recover_test.go
- middleware/requestid/requestid.go
- middleware/requestid/requestid_test.go
Co-authored-by: Rene rene@gofiber.io
> Improve test

- prefork.go
> Bind master process to 1 thread/CPU

- .github/FUNDING.yml
> 🎖 add sponsor link

- .github/README.md
- .github/README_ar_SA.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
> 🎨 improve READMEs

- middleware/compress/README.md
> 🎨 : Updated navigation for the examples

- router.go
clean error handler
When a 405 error occurs, we can just pass it to the `app.handler`, so that there is only one place to call `ErrorHandler`.
> 🧹 pass ErrMethodNotAllowed to handler

- .github/README.md
- .github/README_ar_SA.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
Added prometheus middleware implementation to 3rd party middlewares list.
Will help users integrate a metrics end point easily in their applications.
> update readme prometheusmiddleware

- prefork.go
See [here](https://github.com/gofiber/fiber/issues/799#issuecomment-695751995) (#799) for more details.
And in order to maintain light weight, temporarily do not increase the configuration to control the number of threads.
> 🉑 revert GOMAXPROCS in master process

- .github/CODEOWNERS
- middleware/cache/README.md
- middleware/cache/cache.go
- middleware/cache/cache_test.go
Co-Authored-By: Tom <tom@tdpain.net>
> 📦 introduce cache mw

- middleware/filesystem/README.md
https://github.com/gofiber/fiber/issues/834
> ⚠ add disclaimer to fs mw

- middleware/compress/README.md
- middleware/pprof/README.md
> 📚 fix typo

- middleware/monitor/index.go
- middleware/monitor/index.html
> 🕐 fix timeout

- middleware/monitor/monitor.go
- middleware/monitor/monitor_test.go
Add test casts.
Make it 100% coverage.
> 👷 add monitor middleware test cases

- middleware/logger/logger.go
- middleware/logger/utils.go
> 🎨 add colors to default format

- middleware/requestid/README.md
the prop Generetor doesn't exists, is Generator
👍
> fix name prop in doc

- middleware/cache/cache.go
- middleware/cache/cache_test.go
This PR addresses the following:
- Fixes an issue with a magic number on cache middleware.
- Adds a basic test for cache middleware.
- Fixes an issue with cache expiration.
- Adds more tests thus increasing coverage for the cache middleware.
> Fix minor issue on cache middleware and add tests

- middleware/cache/cache.go
- middleware/cache/cache_test.go
fix https://github.com/gofiber/fiber/pull/863
> 📦 fix race condition in cache mw

- .github/README.md
- .github/README_ar_SA.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
There is a ton of examples on usage of either WebSockets or simple REST. I've not found any long polling example still. So here it is.
There is no problem actually. Just added a way to use long polling technique with Fiber.
:sparkles:
> Added long-polling

- app.go
> 👷 handle error of fmt.Fprintf

- app_test.go
```
coverage: 96.8% of statements
ok      github.com/gofiber/fiber/v2     7.085s
```
> 👷 add app test case to improve coverage

- ctx_test.go
```
coverage: 97.1% of statements
ok      github.com/gofiber/fiber/v2     6.755s
```
> 👷 add ctx test case to improve coverage

- app_test.go
- group.go
`group.Mount` should combine the prefix with group's prefix.
BTW, improve the test coverage.
```
coverage: 97.6% of statements
ok      github.com/gofiber/fiber/v2     6.714s
```
> 👷 fix group.Mount

- .github/README.md
Right now the readme links to different third party licenses. The last part has some of the doubled (maybe a previous conflict?). This PR removes the doubled ones.
✅ done
> 🩹fix the duplicated third party license links in the readme

- middleware/cache/cache_test.go
Increases coverage in cache middleware by adding an extra test.
```
coverage: 89.1% of statements
```
> Increase coverage in cache middleware

- app_test.go
Refactor the app test to use the constants to access the header fields and the http methods.
✅ done
> ♻️ refactor app test to use the constants to access the http methods and headers

- .github/README.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_sa.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
…requestreview-504575447
fix  Translated languages links in [Fiber Website](https://gofiber.io) [#10](https://github.com/gofiber/website/pull/10#issue-499195670) we need change README_ar_SA.md to README_sa.md to make live easy  :recycle:
> renaming to README_sa

- ctx.go
> 🐛 Make SendFile return 404 if file not found

- middleware/monitor/monitor.go
fix #903
We should make sure everything get from `gopsutil` is legal.
> 🩹 Avoid panic when updating statistics

- app.go
> Fix for #912

- app.go
> Fix for #914

- ctx_test.go
Improve test case for `Ctx.SendFile` to cover #908 as #911 mentioned
> 🩹 Improve test case for Ctx.SendFile to cover #908 as #911 mentioned

- middleware/etag/README.md
- middleware/etag/etag.go
- middleware/etag/etag_test.go
Move etag to a middleware.
For users to have more control. #909 
> Add Etag middleware

- app.go
> 🔥 Deprecate ETag option and bump version to 2.1.0

- middleware/proxy/proxy.go
- middleware/proxy/proxy_test.go
- Refactor the proxy middleware.
- Update coverage from 0% to 92%.
> Refactor proxy middleware and increase coverage

- middleware/proxy/proxy_test.go
- Fix broken tests on proxy middleware
> Replace localhost with IP

- .github/CONTRIBUTING.md
- .github/README_id.md
- Fix typo in CONTRIBUTING.md
- Improve Indonesian translation in README_id.md
> Fix typo and improve Indonesian translation in README_id

- router.go
- router_test.go
Reset Ctx param value to empty string while parsing star route
> 🩹 Fix #945

- middleware/proxy/README.md
- middleware/proxy/proxy_test.go
Related to https://github.com/gofiber/fiber/issues/947
> ✏ fix example

- app_test.go
- ctx_test.go
- router_test.go
> 🍀 Improve test coverage

- app.go
Adds a storage interface into `app.go`.
> Add storage interface

- app.go
- internal/fwd/LICENSE.md
- internal/fwd/reader.go
- internal/fwd/writer.go
- internal/fwd/writer_appengine.go
- internal/fwd/writer_unsafe.go
- internal/msgp/read.go
> 📦 bump v2.1.2

- middleware/csrf/csrf.go
> 🩹 Keep csrf token per session

- internal/gopsutil/mem/mem.go
- internal/gopsutil/mem/mem_linux.go
- internal/gopsutil/net/net_windows.go
- internal/gopsutil/process/process_fallback.go
- internal/gopsutil/process/process_freebsd.go
- internal/gopsutil/process/process_freebsd_arm64.go
- internal/gopsutil/process/process_linux.go
- internal/gopsutil/process/process_openbsd.go
- internal/gopsutil/process/process_windows_386.go
- middleware/requestid/requestid.go
- middleware/requestid/requestid_test.go
Format the code by executing `go fmt ./...`
> refactor: format the code

- app_test.go
Just a few constants to avoid duplicate code
> Code refractor to avoid duplicate lines

- .github/README_es.md
Translation of some stuff from English to Spanish for the README_es
> Update on spanish translation

- .github/README_sa.md
> update installation tags in readme_sa.md

- app.go
https://github.com/gofiber/fiber/issues/1020
> ✏ add process information

- .github/README_ja.md
- Translate untranslated parts
- Remove duplicated text of English and Japanese.
- Just improve docs
> 📝 Improve README_ja.md

- middleware/session/session.go
See https://github.com/gofiber/fiber/issues/1048
`setCookie()` to first order. If this is not a simple problem or is intended, please add comments to the middleware guide.
> 🐛 session middleware setCookie order to first

- app.go
- internal/storage/memory/memory.go
- middleware/session/session_test.go
- middleware/session/store.go
And update test case for https://github.com/gofiber/fiber/issues/1048
> 🩹 fix session storage

- ctx.go
Co-Authored-By: Mones Zarrugh <11161902+moneszarrugh@users.noreply.github.com>
#1067
> 🚧 refactor bodyparser

- app.go
https://github.com/gofiber/fiber/issues/1077
> 📦 introduce ListenTLS

- .github/README_zh-TW.md
Translation of how to install.
> 📚 Doc: Update READ_zh-TW.md for how to install

- app_test.go
- helpers_test.go
>  👷 Add test cases for group router empty prefix path

- app.go
> 📦 bump v2.3.2

- .github/README.md
**Is your feature request related to a problem?**
Missing firebase authentication middleware library for Go Fiber
**Describe the solution you'd like**
I wrote[ **gofiner-firebaseauth**](https://github.com/sacsand/gofiber-firebaseauth) library to authenticate endpoints with firebase auth .
I have included necessary information and guideline such as ,  
_Unit Testing and CI
Contribution Guide 
How to configure, install and use
How to test and develop_
in the repo readme.mg
And also created PR here  https://github.com/gofiber/recipes/pull/86 describing how to use the middleware with go fiber. 
Please review 
Thanks And Happy New Year
**Describe alternatives you've considered**
-- This library is similar to https://github.com/sacsand/express-firebase-auth
**Additional context**
> 📚 Request for new 3rd party middleware listing !!! Firebase Authentication Middleware for Go Fiber 

- middleware/basicauth/config.go
see [issue in gin](https://github.com/gin-gonic/gin/issues/2226)
> fix timing attack in basicauth

- middleware/monitor/index.go
- middleware/monitor/index.html
- middleware/monitor/monitor.go
> 🚀 Adding total ram to monitor

- middleware/csrf/config.go
- middleware/csrf/csrf.go
- middleware/csrf/csrf_test.go
> 🚀Add Custom Error Func for CSRF Middleware

- middleware/recover/README.md
- middleware/recover/config.go
- middleware/recover/recover.go
- middleware/recover/recover_test.go
The intention of this PR is to address the issue raised here: [1119](https://github.com/gofiber/fiber/issues/1119)
It allows for configuration of printing debug stacktrace.
Add variable to control whether print debug stacktrace  and can define custom print stack trace function.
> 🔥 Feature: recover middleware support print stack trace

- prefork.go
> 👷 start process before prefork server starting

- .github/README.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_sa.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
It is an inertia.js server-side adapter which helps creating single-page apps without building an API, using classic server-side routing and controllers.
> ✨ Add fiber-inertia to README.md

- internal/storage/memory/memory.go
> Remove duplicate line

- middleware/proxy/proxy.go
I've replace balancing mechanism in the proxy middleware to the fasthttp.LBClient.
This solves the bug with setting host header.
When you proxy requests to backends:
```go
Servers: []string{
"http://127.0.0.1:81",
"http://127.0.0.2:81",
"http://127.0.0.3:81",
},
```
there is no way set host header. He will always be 127.0.0.1:81, 127.0.0.2:81 or 127.0.0.3:81, not the domain name you are proxying (even if force set req.SetHost()).
Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: …
> 🐛 Fix setting host header in proxy middleware

- middleware/proxy/proxy_test.go
Try to fix random CI failure about proxy middleware.
- Add t.Parallel()
- Use random port
> 👷 Improve proxy middleware test case

- .github/README_tr.md
Fixed typos and translated English sentences.
>  ✏️ Fix typos and translate some sentences English to Turkish

- middleware/csrf/README.md
> CSRF Docs - Add note about how to get token

- middleware/filesystem/README.md
It's quite common that web developers want to pack static files in binary file, so i add few lines for example.
> ✏️ FS MW: add example of embedding directory

- .github/README_ru.md
> Update code snippets for RU language

- middleware/csrf/config.go
- middleware/csrf/csrf.go
- middleware/csrf/extractors.go
* Moves extractors to their own file
* Move logic that selects extractor to `configDefault` function
* Add `extractor` field to Config
> CSRF MW Restructuring

- .github/README.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_sa.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
> ✏️ fix broken links in README

- .github/README.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_sa.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
update broken links for ErrorHandler hyperlink in READMEs
#1253
> :memo: Doc: Updated broken links for ErrorHandler hyperlink in readme

- path.go
- path_test.go
🚀 new possibility to escape special routing parameters,
which gives the possibility to follow the google api design guide https://cloud.google.com/apis/design/custom_methods
> 🚀 new possibility to escape special routing parameters

- .github/README_de.md
I just translated some paragraphs that were still in English and fixed some grammar.
> ✏️ update german translation

- middleware/cache/cache.go
After a not quite successful attempt to fix flaky tests for the cache middleware in #1229  I'd want to propose to get current timestamp every time when the middleware is executed, since it's the most stable way to expire cache in time.
Alternative way would be to not check the expiration at all and leave it up to caching the backend.
> 🐛 Cache Middleware - Race condition in the cache expiration logic. Round 2

- app.go
- app_test.go
- group.go
- router.go
Use atomic instead of mutex when counting.
> Use atomic instead of mutex when counting the route handler.

- .github/README.md
Fixed my GitHub profile link 😄
> ✏️ Fix link to GitHub account

- .github/README.md
:bulb: Fix to a comment pointing to wrong endpoint
> small comment fix

- middleware/proxy/config.go
✏️fix a little comment wrong in proxy middleware
> ✏️fix comments 

- .github/README.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_sa.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
✏️add link to third party middlewares of all readmes
> ✏️add link to third party middlewares of all readmes

- middleware/pprof/pprof.go
- middleware/pprof/pprof_test.go
it fix the reported bug #1360 
> 🐛 fix - pprof middleware redirect index page to wrong url #1360

- middleware/session/session.go
- middleware/session/session_test.go
- middleware/session/store.go
> Fix session delete when there is one key

- helpers.go
Feature policy [deprecation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy)
> deprecate feature-policy

- .github/README_zh-CN.md
> fix readme zh-CN

- ctx_test.go
Hi! ,,, I try to learn more about testing by reading *_test.go, so I found this duplicated line in ctx_test.go ...
> 🧹 remove duplicate line in test

- .github/README_pt.md
The Installation section to Portuguese language was not translated. So I translated that. Hope this helps!
> 🩹 Fix: installation section translation

- ctx_test.go
- internal/schema/decoder.go
#1414 
https://github.com/gorilla/schema/issues/176
> Schema parser: use full match instead of strings.HasPrefix

- middleware/recover/README.md
spotted a small mistake in the docs
> Low priority: small spelling fix in docs

- ctx.go
- ctx_test.go
- middleware/logger/README.md
- middleware/logger/logger.go
- middleware/logger/logger_test.go
> [Logger]: add tag for response header

- middleware/skip/README.md
- middleware/skip/skip.go
- middleware/skip/skip_test.go
Add a generic middleware for skipping middleware, so there is no need to implement this feature in every middleware.
See #1440 
> 🔥 Feature: Add Skip middleware

- router.go
Fixed route path copying in `app.copyRoute`.
Fixed issue in #1470.
Was gonna do that on squash & merge
> Fix `route.Path` on copy

- .github/README_zh-CN.md
Provides translation of internal middleware part for Chinese Rademe.
> Add Chinese translation for internal middleware

- app.go
- helpers_test.go
- prefork_test.go
> 🩹  Fix: corrects ipv6 loopback ip shown on UI

- .github/README_zh-CN.md
Translate `External Middleware` section of README to Chinese.
> Translate `External Middleware` section of README to Chinese.

- .github/README_tr.md
I fixed translation issues and i translated more area. i added localization.
Why i added localization?
Cuz English and Turkish is different language (grammamicly). 
Understandable sentences in English can be incomprehensible in Turkish.
I fixed weird translate issues. i fixed not understandable phrases.
Why i push one commit?
Cuz I was sleepy while typing this and translating.
> fixed translation issues and translate more area in turkish readme

- middleware/monitor/README.md
- middleware/monitor/config.go
- middleware/monitor/monitor.go
- middleware/monitor/monitor_test.go
> Add next support for Monitor middleware.

- middleware/cache/cache_test.go
- middleware/cache/config.go
> 🐛 Get unexpected results from cache #1529

- .github/README_ja.md
The untranslated sentences of the Japanese version of the Readme have been translated. However, sentences that may not convey the exact meaning as a result of translation have not been translated.
> Translated some sentences for ja-version

- .github/README_tr.md
Many language and punctuation mistakes were fixed on the Turkish version of the README.
> 📚 Fix language mistakes in Turkish

- .github/README_es.md
Improve Spanish translation by fixing some spelling issues, and vague translations. Also, finish several sections where the translation was missing.
> :ledger: Update Spanish documentation

- app_test.go
- router.go
- router_test.go
Fixes: https://github.com/gofiber/fiber/issues/1490#issuecomment-932321685
> Fix: register static file routing with trailing slash

- middleware/cache/README.md
> fix cache docs error

- middleware/cache/README.md
- middleware/cache/cache.go
- middleware/cache/cache_test.go
- middleware/cache/config.go
Cache generate custom Expiration
> Feature: [Cache] add ExpirationGenerator for generate custom Expiration

- .github/README_zh-CN.md
Hi, this is a gopher from China. I find that there are some inappropriate translation in the documentation.
I'm sorry that I'm not good at English. But I have tried my best to improve it.
Hope it helps you!
> 📚 Doc: Change some Chinese translation

- app_test.go
- group.go
> 🐛 Fix: error handler of app not saved when mounted in group

- internal/go-json/cmd/generator/vm.go.tmpl
- internal/go-json/encoder/decode_rune.go
- internal/go-json/encoder/encoder.go
- internal/go-json/encoder/map112.go
- internal/go-json/encoder/map113.go
- internal/go-json/encoder/opcode.go
- internal/go-json/encoder/string.go
- internal/go-json/encoder/vm/vm.go
- internal/go-json/encoder/vm_color/vm.go
- internal/go-json/encoder/vm_color_indent/vm.go
- internal/go-json/encoder/vm_indent/vm.go
Fixes https://github.com/gofiber/fiber/issues/1658.
> Fix goccy/go-json for go1.18-beta1.

- .github/README_id.md
* translate untranslated words
* fix unconsistent translate of `project`, every project word should be `proyek` instead of `projek` or the original one `project`
* fix wrong translation of Authentication, it should be `Autentikasi` instead of `Authentikasi`
-
Added in pull request title, need to squash and merge.
> 📝 docs: tweaks README_id.md

- .github/README_tr.md
> Update Turkish translation

- .github/README_id.md
> 📝docs: fix ID translation typo

- .github/README_ckb.md
> Add Central Kurdish README

- app.go
`json:"print_routes"` => `json:"enable_print_routes"`
> change json tag for EnablePrintRoutes

- middleware/limiter/config.go
> Fixing a mistake of the comment in the limiter package

- middleware/cache/manager.go
:pencil2: This PR fixes a comment typo in `manager.go`
> ✏️ Cache middleware: Fix comment typo in manager.go.

- app.go
- ctx.go
- ctx_test.go
closes https://github.com/gofiber/fiber/issues/1785
> :sparkles: feature: add SendFileWithConfig method to ctx

- .github/README.md
- .github/README_ckb.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fa.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_it.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_sa.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
I don't recall using this project or donating to it 2 years ago, it looks like someone with the same username donated it :smile:
> chore: remove incorrect links from supporter table

- app.go
📝  make code more clear to people!
> ♻️ reduce duplicate in Get method

- internal/isatty/isatty_tcgets.go
Add z/OS compatibility on build command.
> z/OS Compatibility

- ctx.go
> fix typo for paramsInt function

- .github/workflows/test.yml
Add macos-latest to platform of testing action.
> :construction_worker: ci: actions for MacOS

- hooks.go
To improve the code,  I would like to delete a blank line.
> :recycle:delete a blank line

- app.go
close: https://github.com/gofiber/fiber/issues/1938
> ♻️ refactor: default error handler & example

- .github/README_id.md
this pr for fix translation from en to id
- fix translation on awesome list
> :books: Doc: Translate to Indonesian Awesome List

- internal/gopsutil/load/load_bsd.go
> :bug: bug: fix gopsutil when compiling for bsd

- .github/README.md
> Update README.md 📝

- .github/README_it.md
Update italian readme that had some parts that were not in Italian. Also fix some bad grammar and things that did make sense. (Native Italian speaker)
> 📝 docs: Update Italian readme

- app_test.go
fix unhandled errors in `app_test.go`
> :mag_right: fix unhandled errors

- app_test.go
- helpers.go
- helpers_test.go
> 🐛 [Fix]: unhandle in strictmode

- go.mod
- I upgraded go version to 1.19 in go.mod.
- I executed `go mod tidy -go=1.19`.
> :white_check_mark: Upgrade go version to 1.19 in go.mod

- ctx.go
- ctx_test.go
Fixes https://github.com/gofiber/fiber/issues/2100
> :bug: fix: same struct parse param failed

- .github/README_ja.md
- I corrected some mistakes in README_ja.
> ✍ Correct README_ja

- app.go
- app_test.go
Fixes https://github.com/gofiber/fiber/issues/2111
> :sparkles: feat: Add GetRoutes

- middleware/timeout/README.md
> ✏️ Fix: typos

- .github/README.md
- .github/README_ckb.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fa.md
- .github/README_fr.md
- .github/README_id.md
- .github/README_it.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_sa.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
Updated the language count in READMEs to match the 18 languages Fiber is translated in (considering we're counting English).
> 📝 docs: Update language count

- client.go
> fix - agent.Struct fails to unmarshal response since 2.33.0 #2134

- middleware/encryptcookie/README.md
fixes https://github.com/gofiber/fiber/issues/2125
> :memo: docs: add doc about usage of CSRF and EncryptCookie middlewares.

- middleware/proxy/proxy.go
> :bug:  fix: solve data race in middleware/proxy's test

- middleware/logger/logger.go
> style: update logger's comment

- middleware/cache/README.md
- middleware/cache/cache.go
Updated cache request directives description
> 📝 Cache readme and docs update

- middleware/session/store.go
I think there's a typo "unmashal" for "unmarshal"
> ✏️ Fix: comment typo

- app.go
- app_test.go
- group.go
- register.go
- router.go
- router_test.go
See: https://github.com/gofiber/fiber/issues/2160
This is PR Part 2 (requires Part 1: https://github.com/gofiber/fiber/pull/2175)
> :sparkles: v3 (feature): router interface changes

- path.go
- path_test.go
This PR allows users to define routes with both optional parameters and constraints.
This PR fixes #2170.
> 🚀 [Feature]: Allow optional params with route constraints

- .github/README_zh-CN.md
Fixes # ([2181](https://github.com/gofiber/fiber/issues/2181))
> 📝 Update README_zh-CN.md

- app.go
- app_test.go
- group.go
- router.go
- router_test.go
Fixes https://github.com/gofiber/fiber/issues/2196
> :bug: bug: fix naming of routes inside groups

- utils/bytes.go
https://github.com/gofiber/utils/blob/f33fd2c5f7f02d398bc996ddcc53d6b6a567e4d9/bytes.go
> utils: reduce diff to external utils package

- .github/README_ko.md
Add korean translate to README_ko.md installation section.  
> Add korean translate in Installation section

- .github/README.md
- .github/README_ckb.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fa.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_it.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_sa.md
- .github/README_tr.md
- .github/README_uk.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
This PR fixes the CI badge errors on `README.md`. This was introduced by the recent update of shields.io. You can read the details here: https://github.com/badges/shields/issues/8671
Fixes # (issue) (skipped as this is a minor change, not a bug of fiber.)
**Before**
**After**
This only affects `README.md`.
Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.dev/
👌🏻
> 📝 docs: fix ci badge errors

- internal/gopsutil/mem/mem.go
Fixes https://github.com/gofiber/fiber/issues/2293
> :bug: bug: fix gopsutil compilation

- middleware/filesystem/README.md
I try use fiber's filesystem middleware to embed my front-end bundle files as the example codes do, but there seems to be a little bit of typos in example codes. So I solve it and make my app work.
> 📝 docs(filesystem): fix statik filesystem middleware example typo

- .github/README.md
- .github/README_ckb.md
- .github/README_de.md
- .github/README_es.md
- .github/README_fa.md
- .github/README_fr.md
- .github/README_he.md
- .github/README_id.md
- .github/README_it.md
- .github/README_ja.md
- .github/README_ko.md
- .github/README_nl.md
- .github/README_pt.md
- .github/README_ru.md
- .github/README_sa.md
- .github/README_tr.md
- .github/README_zh-CN.md
- .github/README_zh-TW.md
There were some links in readme that didn't work due to a refactoring of the official fiber website, so I fixed them.
> 🐛 [Bug-Fix] Fix all inaccessible links in docs

- middleware/limiter/README.md
nothing too much but it's a fix :p
In [rate limit middleware docs](https://github.com/gofiber/fiber/tree/master/middleware/limiter), there's a missing comma. This pull request fixes it. Nothing too much, but it's a fix :p
Add missing comma in docs.
> fix(docs): add missing comma

- docs/partials/routing/handler.md
> Fix typo in docs

- .github/README_az.md
@eld4niz To be honest, I spend a whole day for this stuff and that was a lot of work, which might actually worth it. Hopefully, you'll approve this request soon.
> Correct grammar errors in Azerbaijani translation.

- middleware/cache/config.go
- middleware/cors/cors.go
- middleware/csrf/config.go
- middleware/idempotency/idempotency.go
- middleware/limiter/config.go
- middleware/proxy/proxy.go
- middleware/session/config.go
- middleware/timeout/timeout.go
> 🚀 Consistent way of logging and fix middleware log format #2432

- .github/README_ru.md
Translated 3 blocks: Limitations, Awesome list, License
> :memo: docs: update README_ru.md 

- .github/README_fa.md
I just translated some texts in `README_fa.md`.
> 📚 translate README_fa.md

- .github/workflows/vulncheck.yml
> Revert "Migrate to Golang official govulncheck action"

- docs/guide/templates.md
> :memo: docs: update version of html template

- app.go
- ctx.go
- docs/guide/hooks.md
- hooks.go
- hooks_test.go
- listen.go
- prefork.go
add a function in listener.go to print out the developer provided custom message
> 🔥 Feature: add ability to print custom message on startup

- client.go
> Fix comment in client.go

- docs/api/ctx.md
Add a warning on security implications when using X-Forwarded-For improperly. I know this is also specified on the MDN docs, but it seems a large enough risk to include it here as well. People rarely chain read documentation (like they should)
> Update ctx.md: Add a warning on security implications when using X-Forwarded-For improperly

- docs/api/middleware/recover.md
> 📚 Docs: Fix link

- docs/api/ctx.md
Added a description what ctx.Fresh does.
Why: For a more complete documentation.
> 📝 added documentation about ctx Fresh

- docs/api/ctx.md
> :memo: docs: fix wrong JSON docs

- .github/README_pt.md
- Added translations to Portuguese (pt-BR) in README_pt.md
> 📚 Doc: Translate README to Portuguese

- docs/api/app.md
Hello. I found out that the depreciated io/ioutil package is being used for [fiber documentation](https://docs.gofiber.io/api/app).
I think it would be better to check the [link](https://go.dev/doc/go1.16#ioutil) and update the document.
> 📝 Docs: update io/ioutil package to io package

- middleware/idempotency/config.go
Fixes https://github.com/gofiber/fiber/issues/2643
> :bug: bug: fix nil pointer dereference issue on idempotency middleware

- docs/api/middleware/requestid.md
Minor typo fix in requestid.md.
> 🩹 Fix: Typo in requestid.md

- docs/api/middleware/csrf.md
Enhance csrf middlware docs
documentation update
> 📄 docs: enhance csrf.md

- docs/api/app.md
Fix indentation typo for Route section unden app.md
- Docs
> 📚 Update app.md for indentation

- listen.go
I comment had one word with one letter missing so I added it.
I think this change will immensely improve the quality of this project and will lead to great success inte the future.
Related to # (issue)
The only issue here is me
I have not benchmarked it but it might take a CPU cycle or two longer to compile because of the additional token that has to be stripped.
- [ x] Documentation update (changes to documentation)
> 📚: Fix a misspelled comment

- ctx.go
In this PR https://github.com/gofiber/fiber/pull/2391, it seems the doc has not changed.
> Fix default value to false in docs of QueryBool

- docs/api/ctx.md
Please provide a clear and concise description of the changes you've made and the problem they address. Include the purpose of the change, any relevant issues it solves, and the benefits it brings to the project. If this change introduces new features or adjustments, highlight them here.
Related to # (issue)
Please use emojis in commit messages for an easy way to identify the purpose or intention of a commit. Check out the emoji cheatsheet here: …
> Update Typo documentation

- .github/workflows/test.yml
Add support for running tests against go1.22
> Add go1.22 to test matrix

- docs/api/middleware/keyauth.md
Removes an an extra level of indentation in line 51 of `keyauth.md` [here](https://github.com/gofiber/fiber/blob/v2/docs/api/middleware/keyauth.md?plain=1#L51)
Fixes #2866
- Decremented indentation level in line 51 of /docs/api/middleware/keyauth.md
> :books: Doc: Fix code snippet indentation in /docs/api/middleware/keyauth.md

- .github/workflows/linter.yml
> Bump golangci-lint to v1.56.2

- middleware/adaptor/adaptor_test.go
Simplified the Adaptor middleware benchmarks into two functions. Added benchmarks for several sized requests. Added RunParallel() benchmarks to test for concurrency.
> ♻️ v3: (refactor): Add parallel benchmarks to adaptor middleware

- client/hooks.go
- middleware/earlydata/earlydata.go
- path.go
> Fix some comments

- middleware/session/session_test.go
Remove extra release and aquire ctx calls in session_test.go so Test_Session_Types passes in -race
> test(middleware/session): Remove extra release and aquire ctx calls in session_test.go

- docs/api/ctx.md
Please provide a clear and concise description of the changes you've made and the problem they address. Include the purpose of the change, any relevant issues it solves, and the benefits it brings to the project. If this change introduces new features or adjustments, highlight them here.
Please use emojis in commit messages for an easy way to identify the purpose or intention of a commit. Check out the emoji cheatsheet here: …
> Replaced link to russian mozilla docs

- middleware/cors/utils.go
- middleware/cors/utils_test.go
**Backport of #3163 to v2.**
The Fiber CORS middleware unnecessarily restricts the scheme for the origins that can be configured. As already stated [here](https://github.com/gofiber/fiber/issues/3160#issuecomment-2402456061), the CORS spec does not define any restrictions on the scheme. However, the Fiber CORS middleware restricts the scheme to `http` or `https`.
Fixes #3160
Removes the scheme restriction of the CORS middleware configuration.
Please use emojis in commit messages for an easy way to identify the purpose or intention of a commit. Check out the emoji cheatsheet here: [CONTRIBUTING.md](https://github.com/gofiber/fiber/blob/master/.github/CONTRIBUTING.m …
> 🩹 fix: Middleware/CORS Remove Scheme Restriction

- docs/whats_new.md
Balance brakets in Router/Route chaining.
- [x ] Documentation Update: Balance brakets in Router/Route chaining.
- [x ] Documentation update (changes to documentation)
> 📚 Doc: Update What's New documentation

- docs/intro.md
In v3 the apps Static method has been removed and its functionality has been moved to the static middleware.
The given code example has been updated accordingly.
> 📚 Doc: Update intro.md Static Files section

- ctx.go
- path.go
The standard library `bytes` already includes `bytes.IndexByte`, which is implemented in assembly language. Its performance is superior to ours. Additionally, replacing `isInCharset` with the standard library function can reduce maintenance costs.
```go
func BenchmarkIsInCharset(b *testing.B) {
t := []byte("hello, world!")
for i := 0; i < b.N; i++ {
_ = isInCharset('!', t)
_ = isInCharset(',', t)
_ = isInCharset('w', t)
_ = isInCharset('a', t)
_ = isInCharset('b', t)
_ = isInCharset('c', t)
}
}
```
```go
func BenchmarkIsInCharset(b *testing.B) {
t := []byte("hello, world!")
for i := 0; i < b.N; i++ {
_ = bytes.IndexByte(t, '!') != -1
_ = bytes.IndexByte(t, ',') != -1
_ = bytes.IndexByte(t, 'w') != -1
_ = bytes.IndexByte(t, 'a') != -1
_ = bytes.IndexByte(t, 'b') != -1
_ = …
```
> ♻️ Refactor: replace isInCharset with bytes.IndexByte

- middleware/helmet/config.go
Please provide a clear and concise description of the changes you've made and the problem they address. Include the purpose of the change, any relevant issues it solves, and the benefits it brings to the project. If this change introduces new features or adjustments, highlight them here.
Please use emojis in commit messages for an easy way to identify the purpose or intention of a commit. Check out the emoji cheatsheet here: …
> docs: Update Helmet Middleware default values

- docs/middleware/helmet.md
Same as https://github.com/gofiber/fiber/pull/3348 but for the middleware docs
> docs: Update helmet.md default values

- docs/guide/validation.md
This PR improves the validation documentation by adding:
- Advanced validation examples with different validation types (email, url, min, max)
- Examples for handling validation errors properly
- Custom validator implementation example
These examples will help users better understand how to implement validation in their Fiber applications.
Please use emojis in commit messages for an easy way to identify the purpose or intention of a commit. Check out the emoji …
> 📚 Doc: Add more validation examples

- docs/middleware/healthcheck.md
- docs/whats_new.md
- middleware/healthcheck/config.go
- middleware/healthcheck/healthcheck.go
- middleware/healthcheck/healthcheck_test.go
- Simplify usage of middleware
> 🧹 chore: Simplify HealthCheck middleware

- docs/api/state.md
- Update entry paragraph for `State Management`.
- Add missing emoji
> 📒 docs: Update docs for State Management

- middleware/logger/logger_test.go
to reduce flaky test run, the time is no longer compared, but the format of the time which is in the logger format is looked at
> 🧪 fix: Logger Middleware tests to use regex for time validation

- .github/FUNDING.yml
This pull request fixes a broken URL found in the `.github/FUNDING.yml` file.
> 🧹 chore: Adjust Funding Custom URL

- AGENTS.md
- Backport `AGENTS.md` to `v2`.
> docs: Add AGENTS.md

- helpers.go
- middleware/adaptor/adaptor.go
- middleware/adaptor/adaptor_test.go
NEW
```
Benchmark_HTTPHandler-12    	 1762837	       640.6 ns/op	     696 B/op	      10 allocs/op
Benchmark_HTTPHandler-12    	 1924524	       616.5 ns/op	     696 B/op	      10 allocs/op
Benchmark_HTTPHandler-12    	 1838780	       650.4 ns/op	     696 B/op	      10 allocs/op
Benchmark_HTTPHandler-12    	 1876947	       644.0 ns/op	     696 B/op	      10 allocs/op
```
OLD
```
Benchmark_HTTPHandler-12    	 1864819	       667.2 ns/op	     720 B/op	      11 allocs/op
Benchmark_HTTPHandler-12    	 1892569	       677.0 ns/op	     720 B/op	      11 allocs/op
Benchmark_HTTPHandler-12    	 1811704	       639.5 ns/op	     720 B/op	      11 allocs/op
Benchmark_HTTPHandler-12    	 1879849	       644.0 ns/op	     720 B/op	      11 allocs/op
```
NEW
```
Benchmark_Utils_IsNoCache-12    	44307204 …
```
> ⚡️ Performance optimizations

- docs/middleware/session.md
- middleware/session/middleware.go
- middleware/session/middleware_test.go
- middleware/session/session.go
Enhance the session middleware by introducing a method to retrieve all keys in the current session. Update documentation to reflect these changes and key any type.
> ✨ feat: Add support for Keys() in session middleware

- middleware/helmet/helmet_test.go
- Test header Strict-Transport-Security with HTTPS requests
- Improve Helmet middleware coverage to 100%
> 🧹 chore: Improve Helmet middleware tests coverage

- state.go
Use `GetState` to reduce duplicate code.
Besides, fix inconsistent comment for `GetXXX`
> ♻️ refact(state): Use GetState to reduce duplicate code

- docs/middleware/skip.md
- middleware/skip/skip.go
- clarify how Skip middleware works and how to use it
- update function comment for greater clarity
> 📒docs: Fix Skip middleware docs

- docs/middleware/proxy.md
- fix docs for proxy middleware
> 📒docs: Fix Proxy middleware docs

- docs/middleware/compress.md
- middleware/compress/config.go
- clarify that `Level` sets the compression level
> 📒docs: Fix Compress middleware docs

- .github/labeler.yml
- binder/msgpack.go
- binder/msgpack_test.go
- client/request_test.go
Fix typos found via `codespell -L te,nd` and `typos --hidden --format brief`
> 📚 docs: Fix typos in documentation

- helpers.go
reflect.TypeAssert is a better api.
https://github.com/golang/go/issues/62121
> refactor: using reflect.TypeAssert

- internal/memory/memory.go
Avoid unneeded locking in gc()
> 🧹 chore: avoid locking in gc() if nothing to delete

- client/request.go
- client/request_test.go
1. Saves ~8% time on allocations in `Request::Params()`
```bash
benchstat old-params.txt new-params.txt                                                       
goos: darwin
goarch: arm64
pkg: github.com/gofiber/fiber/v3/client
cpu: Apple M3 Max
│ old-params.txt │           new-params.txt            │
│     sec/op     │    sec/op     vs base               │
_Request_Params      151.6n ± 0%   139.3n ± 11%  -8.11% (p=0.000 n=20)
│ old-params.txt │         new-params.txt         │
│      B/op      │    B/op     vs base            │
_Request_Params       184.0 ± 0%   184.0 ± 0%  ~ (p=1.000 n=20) ¹
¹ all samples are equal
│ old-params.txt │           new-params.txt           │
│   allocs/op    │ allocs/op   vs base                │
_Request_Params       6.000 ± 0%   5.000 ± 0%  -16.67% (p=0.000 …
```
> ⚡ perf: Improve allocations for Request Params()

- client/request.go
Avoids unneeded allocations in `Headers()`, results according to `Benchmark_Request_Headers`
```bash
benchstat old.txt new.txt                                                          
goos: darwin
goarch: arm64
pkg: github.com/gofiber/fiber/v3/client
cpu: Apple M3 Max
│   old.txt   │            new.txt            │
│   sec/op    │   sec/op     vs base          │
_Request_Headers-16   186.9n ± 1%   185.2n ± 1%  ~ (p=0.311 n=20)
│  old.txt   │              new.txt               │
│    B/op    │    B/op     vs base                │
_Request_Headers-16   200.0 ± 0%   168.0 ± 0%  -16.00% (p=0.000 n=20)
│  old.txt   │            new.txt             │
│ allocs/op  │ allocs/op   vs base            │
_Request_Headers-16   7.000 ± 0%   7.000 ± 0%  ~ (p=1.000 n=20) ¹
¹ all samples are equal
``` …
> ⚡ perf: reduce allocations in Request (saves ~16% B/op)

- client/hooks_test.go
- internal/storage/memory/memory.go
Avoid entering lock when there is no expired entries
> 🧹 chore: Skip locking garbage collector if nothing to delete
